// Core translation columns: Traditional Chinese, Simplified Chinese, English, Japanese, and Spanish.
// Hong Kong Traditional reuses the Traditional column; Cantonese applies runtime overrides from locales/yue-HK.json.
// Korean, German, and French are maintained as complete dictionaries under src/locales.
// i18n.spec.ts verifies all generated dictionaries; run `npm run locales` after adding table keys.

export const LANGS = ["zh-tw", "zh-hk", "yue-hk", "zh-cn", "en", "ja", "es", "ko", "de", "fr"] as const;
export type Lang = (typeof LANGS)[number];

export const LANG_LABEL: Record<Lang, string> = {
  "zh-tw": "繁體中文（台灣）",
  "zh-hk": "繁體中文（香港）",
  "yue-hk": "粵語（香港）",
  "zh-cn": "简体中文",
  en: "English",
  ja: "日本語",
  es: "Español",
  ko: "한국어",
  de: "Deutsch",
  fr: "Français",
};

type Row = [string, string, string, string, string];
// Supplemental locales use a core fallback column here; runtime text comes from locales/*.json.
const COL: Record<Lang, number> = { "zh-tw": 0, "zh-hk": 0, "yue-hk": 0, "zh-cn": 1, en: 2, ja: 3, es: 4, ko: 2, de: 2, fr: 2 };

export function tr(lang: Lang, key: string): string {
  const row = TABLE[key];
  return row ? row[COL[lang]] : key;
}

const TABLE: Record<string, Row> = {
  // ---- Tab names ----
  "tab.overview": ["總覽", "总览", "Overview", "概要", "Resumen"],
  "tab.dashboard": ["工作台", "工作台", "Dashboard", "ダッシュボード", "Panel"],
  "dash.actions": ["快捷操作", "快捷操作", "Quick actions", "クイック操作", "Acciones rápidas"],
  "dash.hint": ["拖動面板標題可重新排序，設定會保存在本機。", "拖动面板标题可重新排序，设置保存在本机。", "Drag a panel header to reorder; layout is stored locally.", "パネル見出しをドラッグして並べ替え。配置はローカルに保存。", "Arrastra el encabezado para reordenar; el diseño se guarda localmente."],
  "dash.reset": ["重設佈局", "重置布局", "Reset layout", "配置をリセット", "Restablecer diseño"],
  "dash.enterEdit": ["編輯佈局", "编辑布局", "Edit layout", "レイアウト編集", "Editar diseño"],
  "dash.exitEdit": ["完成編輯", "完成编辑", "Done editing", "編集終了", "Terminar edición"],
  "dash.hidden": ["已隱藏面板", "已隐藏面板", "Hidden panels", "非表示パネル", "Paneles ocultos"],
  "dash.hide": ["隱藏", "隐藏", "Hide", "非表示", "Ocultar"],
  "dash.wider": ["加寬面板", "加宽面板", "Widen panel", "パネルを広げる", "Ensanchar panel"],
  "dash.narrower": ["收窄面板", "收窄面板", "Narrow panel", "パネルを狭める", "Estrechar panel"],
  "dash.show": ["顯示", "显示", "Show", "表示", "Mostrar"],
  "tab.osc": ["OSC", "OSC", "OSC", "OSC", "OSC"],
  "tab.pusher": ["推播", "推送", "Pusher", "プッシャー", "Pusher"],
  "tab.heartbeat": ["心跳", "心率", "HeartBeat", "心拍", "Latido"],
  "tab.devices": ["裝置", "设备", "Devices", "デバイス", "Dispositivos"],
  "tab.hwinfo": ["硬體", "硬件", "HWInfo", "ハードウェア", "Hardware"],
  "tab.headset": ["頭顯", "头显", "HeadSet", "ヘッドセット", "Casco"],
  "tab.web": ["Web 遠端", "Web 远程", "Web Remote", "Web リモート", "Web Remoto"],
  "tab.apiserver": ["API 服務", "API 服务", "API Server", "API サーバー", "Servidor API"],
  "tab.settings": ["設定", "设置", "Settings", "設定", "Ajustes"],
  "tab.logs": ["日誌", "日志", "Logs", "ログ", "Registros"],
  "tab.console": ["命令列", "命令行", "Console", "コンソール", "Consola"],
  "tab.monitor": ["監測", "监测", "Monitor", "モニター", "Monitor"],
  "tab.about": ["關於", "关于", "About", "情報", "Acerca de"],

  // ---- Top bar and sidebar ----
  "topbar.title": ["心跳推播 V1", "心率推送 V1", "Heart Rate Pusher V1", "心拍プッシャー V1", "Pusher de Ritmo V1"],
  "topbar.refresh": ["重新整理", "刷新", "Refresh", "更新", "Actualizar"],
  "topbar.quit": ["離開", "退出", "Quit", "終了", "Salir"],
  "topbar.heart": ["心跳", "心率", "Heart", "心拍", "Ritmo"],
  "nav.brand": ["HR 心跳推播", "HR 心率推送", "HR Pusher", "HR プッシャー", "Pusher HR"],
  "nav.ping": ["延遲", "延迟", "Latency", "遅延", "Latencia"],
  "nav.pilloff": ["關閉", "关闭", "Off", "オフ", "Apagado"],
  "nav.sub": ["心跳監控 V1", "心率监控 V1", "Heart Rate Monitor V1", "心拍モニター V1", "Monitor de Ritmo V1"],
  "nav.connected": ["引擎已連線", "引擎已连接", "Engine connected", "エンジン接続済み", "Motor conectado"],
  "nav.themetoggle": ["切換明暗", "切换明暗", "Toggle dark/light", "明暗を切り替え", "Cambiar claro/oscuro"],
  "nav.waiting": ["等待引擎...", "等待引擎...", "Waiting for engine...", "エンジン待機中...", "Esperando motor..."],
  "nav.collapse": ["收起導覽", "收起导航", "Collapse sidebar", "サイドバーを畳む", "Contraer barra"],
  "nav.expand": ["展開導覽", "展开导航", "Expand sidebar", "サイドバーを開く", "Expandir barra"],

  // ---- Built-in shell window with a page-rendered title bar ----
  "win.section": ["視窗", "窗口", "Window", "ウィンドウ", "Ventana"],
  "win.close": ["關閉", "关闭", "Close", "閉じる", "Cerrar"],
  "win.min": ["最小化", "最小化", "Minimize", "最小化", "Minimizar"],
  "win.max": ["最大化", "最大化", "Maximize", "最大化", "Maximizar"],
  "win.restore": ["還原", "还原", "Restore", "元に戻す", "Restaurar"],
  "win.corner": ["視窗圓角", "窗口圆角", "Window corner", "ウィンドウ角丸", "Esquina de ventana"],
  "win.cornerhint": ["僅影響視窗外框（0＝直角，最大 24），不改變頁面內控件圓角。Win11 走系統原生圓角（小/大兩檔），Win10 按像素裁剪。", "仅影响窗口外框（0＝直角，最大 24），不改变页面内控件圆角。Win11 走系统原生圆角（小/大两档），Win10 按像素裁剪。", "Affects only the window frame (0 = square, max 24); in-page controls are unchanged. Win11 uses native DWM rounding (small/large tiers); Win10 clips by pixels.", "ウィンドウ枠のみに適用（0＝直角、最大 24）。Win11 は DWM ネイティブ丸角（小/大の 2 段階）、Win10 はピクセル裁ち切り。", "Solo afecta al marco (0 = recto, máx. 24). Win11 usa redondeo nativo del DDM (pequeño/grande); Win10 recorta por píxeles."],
  "win.fullscreen": ["全螢幕", "全屏", "Full screen", "全画面", "Pantalla completa"],
  "win.exitfullscreen": ["離開全螢幕", "退出全屏", "Exit full screen", "全画面を終了", "Salir de pantalla completa"],
  "win.fullscreenhint": ["也可用 F11 切換；F5 重新載入，F12 開發者工具。", "也可用 F11 切换；F5 重新加载，F12 开发者工具。", "F11 also toggles it; F5 reloads and F12 opens DevTools.", "F11 でも切替できます。F5 で再読み込み、F12 で開発者ツール。", "F11 también alterna; F5 recarga y F12 abre DevTools."],

  // ---- Window-close confirmation: exit or minimize to tray ----
  "close.title": ["關閉視窗", "关闭窗口", "Close window", "ウィンドウを閉じる", "Cerrar ventana"],
  "close.hint": ["最小化到系統匣不會中斷心率與懸浮視窗；退出會結束整個程式。", "最小化到托盘不会中断心率与悬浮窗；退出会结束整个程序。", "Minimizing keeps heart rate and overlays running; exiting stops the whole app.", "最小化しても心拍とオーバーレイは動作し続けます。終了はアプリ全体を停止します。", "Minimizar mantiene el ritmo y las superposiciones; salir detiene toda la aplicación."],
  "close.exit": ["退出程式", "退出程序", "Exit app", "アプリを終了", "Salir de la app"],
  "close.tray": ["最小化到系統匣", "最小化到托盘", "Minimize to tray", "トレイに最小化", "Minimizar a la bandeja"],
  "close.ask": ["每次詢問", "每次询问", "Ask every time", "毎回確認", "Preguntar siempre"],
  "close.dontask": ["不再詢問我", "不再询问我", "Don't ask again", "今後表示しない", "No volver a preguntar"],
  "close.action": ["關閉視窗時", "关闭窗口时", "On window close", "ウィンドウを閉じる時", "Al cerrar la ventana"],
  "close.actionhint": ["可隨時改回「每次詢問」。", "可随时改回「每次询问」。", "You can switch back to \"Ask every time\" anytime.", "いつでも「毎回確認」に戻せます。", "Puedes volver a \"Preguntar siempre\" cuando quieras."],
  "close.unsaved": ["有未保存的更改", "有未保存的更改", "Unsaved changes", "未保存の変更があります", "Cambios sin guardar"],
  "close.unsavedhint": ["有 {n} 處設定尚未保存，要先保存嗎？", "有 {n} 处设置尚未保存，要先保存吗？", "{n} setting form(s) are unsaved. Save them first?", "{n} 件の設定が未保存です。先に保存しますか？", "Hay {n} formulario(s) sin guardar. ¿Guardar primero?"],
  "close.save": ["保存並繼續", "保存并继续", "Save and continue", "保存して続行", "Guardar y continuar"],
  "close.discard": ["放棄更改", "放弃更改", "Discard changes", "変更を破棄", "Descartar cambios"],

  // ---- Connectivity watchdog: disconnect overlay and error panel ----
  "net.reconnecting": ["與後端斷線，正在重新連線...", "与后端断开连接，正在重连...", "Backend disconnected, reconnecting...", "バックエンドと切断、再接続中...", "Backend desconectado, reconectando..."],
  "net.failed": ["無法連線到後端", "无法连接到后端", "Cannot reach the backend", "バックエンドに接続できません", "No se puede conectar al backend"],
  "net.failedhint": ["已重試 30 次仍未成功。請確認主程式仍在執行，或檢查連接埠是否被佔用。", "已重试 30 次仍未成功。请确认主程序仍在运行，或检查端口是否被占用。", "30 attempts failed. Make sure the main app is still running and the port is free.", "30 回試行しても失敗しました。本体が動作中か、ポートが空いているか確認してください。", "30 intentos fallidos. Comprueba que la app principal sigue activa y el puerto está libre."],
  "net.retry": ["重新嘗試", "重新尝试", "Retry", "再試行", "Reintentar"],
  "net.wsdown": ["WebSocket 連接已斷開", "WebSocket 连接已断开", "WebSocket connection lost", "WebSocket 接続が切断されました", "Se perdió la conexión WebSocket"],
  "net.copy": ["點擊複製錯誤詳情", "点击复制错误详情", "Click to copy error details", "クリックで詳細をコピー", "Clic para copiar detalles"],
  "net.copied": ["已複製", "已复制", "Copied", "コピーしました", "Copiado"],
  "net.exportcfg": ["匯出設定", "导出配置", "Export settings", "設定を書き出す", "Exportar ajustes"],
  "net.closetab": ["關閉標籤頁", "关闭标签页", "Close tab", "タブを閉じる", "Cerrar pestaña"],

  // ---- Common ----
  "common.save": ["儲存", "保存", "Save", "保存", "Guardar"],
  "common.cancel": ["取消", "取消", "Cancel", "キャンセル", "Cancelar"],
  "common.ok": ["確定", "确定", "OK", "OK", "Aceptar"],
  "common.delete": ["刪除", "删除", "Delete", "削除", "Eliminar"],
  "common.edit": ["編輯", "编辑", "Edit", "編集", "Editar"],
  "common.test": ["測試", "测试", "Test", "テスト", "Probar"],
  "common.add": ["新增", "新增", "Add", "追加", "Añadir"],
  "common.clear": ["清空", "清空", "Clear", "クリア", "Limpiar"],
  "common.refresh": ["重新整理", "刷新", "Refresh", "更新", "Actualizar"],
  "common.export": ["匯出", "导出", "Export", "エクスポート", "Exportar"],
  "common.apply": ["套用", "应用", "Apply", "適用", "Aplicar"],
  "common.enabled": ["啟用", "启用", "Enabled", "有効", "Activado"],
  "common.disabled": ["停用", "停用", "Disabled", "無効", "Desactivado"],
  "common.on": ["開啟", "开启", "On", "オン", "Activo"],
  "common.off": ["關閉", "关闭", "Off", "オフ", "Inactivo"],
  "common.none": ["無", "无", "None", "なし", "Ninguno"],
  "common.name": ["名稱", "名称", "Name", "名前", "Nombre"],
  "common.value": ["數值", "数值", "Value", "値", "Valor"],
  "common.unit": ["單位", "单位", "Unit", "単位", "Unidad"],
  "common.filter": ["篩選", "筛选", "Filter", "フィルター", "Filtrar"],
  "common.format": ["格式", "格式", "Format", "形式", "Formato"],
  "common.status": ["狀態", "状态", "Status", "状態", "Estado"],
  "common.close": ["關閉", "关闭", "Close", "閉じる", "Cerrar"],
  "common.goto": ["前往", "前往", "Go to", "移動", "Ir a"],
  "common.source": ["資料來源", "数据源", "Source", "データソース", "Fuente"],
  "common.default": ["預設", "默认", "Default", "既定", "Predeterminado"],
  "common.saved": ["設定已儲存", "设置已保存", "Settings saved", "設定を保存しました", "Ajustes guardados"],
  "common.unsaved": ["未保存（將自動重試）", "未保存（将自动重试）", "Unsaved (retrying)", "未保存（自動再試行）", "Sin guardar (reintentando)"],
  "safe.banner": ["安全模式已啟用：自動連線、偵測、重新連線、OSC、系統採集與自動推送均已暫停。", "安全模式已启用：自动连接、检测、重连、OSC、系统采集与自动推送均已暂停。", "Safe mode is active: auto-connect, detection, reconnect, OSC, system collection, and automatic pushes are suspended.", "セーフモード有効：自動接続・検出・再接続・OSC・システム収集・自動送信はすべて停止中です。", "Modo seguro activo: la conexión, detección y reconexión automáticas, OSC, la recopilación del sistema y los envíos automáticos están suspendidos."],
  "safe.restart": ["正常重啟退出", "正常重启退出", "Restart normally", "通常再起動で終了", "Reiniciar normalmente"],
  "safe.entryhint": ["暫停自動連接、檢測、重連、OSC、系統採集與自動推送；可在一般模式下一秒內連按三次 R 進入。", "暂停自动连接、检测、重连、OSC、系统采集与自动推送；可在普通模式下一秒内连按三次 R 进入。", "Suspends auto-connect, detection, reconnect, OSC, system collection, and automatic pushes. In normal mode, triple-press R within 1 second to enter.", "自動接続・検出・再接続・OSC・システム収集・自動送信を停止します。通常モードでは1秒以内にRを3回押して起動できます。", "Suspende la conexión, detección y reconexión automáticas, OSC, la recopilación del sistema y los envíos automáticos. En modo normal, pulsa R 3 veces en 1 segundo."],
  "safe.enter": ["進入安全模式", "进入安全模式", "Enter safe mode", "セーフモードに入る", "Entrar en modo seguro"],
  "safe.mode": ["安全模式", "安全模式", "Safe mode", "セーフモード", "Modo seguro"],
  "safe.active": ["狀態：已啟用", "状态：已启用", "Status: active", "状態：有効", "Estado: activo"],
  "safe.normal": ["狀態：一般模式", "状态：普通模式", "Status: normal mode", "状態：通常モード", "Estado: modo normal"],
  "common.autosave": ["更改即時保存", "更改实时保存", "Changes save automatically", "変更は自動保存されます", "Los cambios se guardan automáticamente"],
  "common.reset": ["重設", "重置", "Reset", "リセット", "Restablecer"],
  "common.hint": ["提示", "提示", "Note", "ヒント", "Nota"],
  "card.collapse": ["摺疊卡片", "折叠卡片", "Collapse card", "カードを折りたたむ", "Plegar tarjeta"],
  "card.expand": ["展開卡片", "展开卡片", "Expand card", "カードを展開", "Expandir tarjeta"],
  wip: ["開發中", "开发中", "Work in progress", "開発中", "En desarrollo"],

  // ---- Exit confirmation ----
  "quit.title": ["確認離開", "确认退出", "Confirm quit", "終了の確認", "Confirmar salida"],
  "quit.body": ["確定要離開心跳推播 V1 嗎？", "确定要退出心率推送 V1 吗？", "Quit Heart Rate Pusher V1?", "心拍プッシャー V1 を終了しますか？", "¿Salir de Pusher de Ritmo V1?"],
  "crash.title": ["引擎異常退出", "引擎异常退出", "Engine crashed", "エンジンが異常終了しました", "El motor se bloqueó"],
  "crash.body": ["主程序（引擎）异常退出。可尝试重新启动后端，重连后界面自动恢复。", "主程序（引擎）异常退出。可尝试重新启动后端，重连后界面自动恢复。", "The engine exited unexpectedly. Restart the backend and the UI will reconnect automatically.", "エンジンが異常終了しました。バックエンドを再起動すると UI が自動で再接続されます。", "El motor finalizó inesperadamente. Reinicie el backend y la interfaz se reconectará sola."],
  "crash.restart": ["重啟後端", "重启后端", "Restart engine", "バックエンドを再起動", "Reiniciar el motor"],
  "crash.later": ["稍後", "稍后", "Later", "後で", "Después"],
  "crash.retrying": ["正在重啟後端...", "正在重启后端...", "Restarting engine...", "バックエンドを再起動中...", "Reiniciando el motor..."],
  "crash.retryfailtitle": ["重啟失敗", "重启失败", "Restart failed", "再起動に失敗しました", "Falló el reinicio"],
  "crash.retryfailbody": ["多次尝试仍未成功：端口可能被占用或程序已被移动。可再次重试，或查看崩溃现场与日志。", "多次尝试仍未成功：端口可能被占用或程序已被移动。可再次重试，或查看崩溃现场与日志。", "Several attempts still failed: the port may be in use or the program may have moved. Retry, or check the crash log and app log.", "複数回試行しても失敗しました：ポートが使用中か、プログラムが移動した可能性があります。再試行するか、クラッシュログをご確認ください。", "Varios intentos fallaron: el puerto puede estar ocupado o el programa puede haberse movido. Vuelva a intentarlo o revise los registros."],
  "crash.retry": ["重試", "重试", "Retry", "再試行", "Reintentar"],

  // ---- Settings ----
  "settings.language": ["語言", "语言", "Language", "言語", "Idioma"],
  "settings.theme": ["主題", "主题", "Theme", "テーマ", "Tema"],
  "settings.accent": ["強調色", "强调色", "Accent color", "アクセント色", "Color de acento"],
  "settings.bg": ["底層背景色", "底层背景色", "Base background", "ベース背景色", "Fondo base"],
  "settings.panel": ["面板背景色", "面板背景色", "Panel background", "パネル背景色", "Fondo del panel"],
  "settings.corner": ["圓角半徑", "圆角半径", "Corner radius", "角丸半径", "Radio de esquina"],
  "settings.thememode": ["明暗模式", "明暗模式", "Appearance mode", "外観モード", "Modo de apariencia"],
  "settings.palette": ["主題色", "主题色", "Color theme", "テーマカラー", "Color del tema"],
  "settings.systemhint": ["兩者的第一項都是「遵循系統」（Windows 深淺與強調色）。", "两者的第一项都是「遵循系统」（Windows 深浅与强调色）。", "The first option of each follows Windows (light/dark and accent color).", "どちらも先頭は「システムに従う」（Windows の明暗とアクセント色）。", "La primera opción de cada uno sigue a Windows (claro/oscuro y color de acento)."],
  "settings.debug": ["調試", "调试", "Debugging", "デバッグ", "Depuración"],
  "settings.debugmode": ["調試模式", "调试模式", "Debug mode", "デバッグモード", "Modo de depuración"],
  "settings.debughint": ["開啟後記錄 DEBUG 等級日誌，並開放開發者工具與狀態欄。", "开启后记录 DEBUG 等级日志，并开放开发者工具与状态栏。", "Logs at DEBUG level and enables DevTools and the status bar.", "DEBUG レベルのログを記録し、開発者ツールとステータスバーを有効化します。", "Registra en nivel DEBUG y habilita DevTools y la barra de estado."],
  "settings.debughint2": ["已即時生效並保存（控制台視窗需重啟）", "已即时生效并保存（控制台窗口需重启）", "Applied and saved (console window needs a restart)", "即時に適用・保存しました（コンソール窓は再起動が必要）", "Aplicado y guardado (la consola requiere reiniciar)"],
  "settings.updatecheck": ["啟動時檢查更新", "启动时检查更新", "Check for updates at startup", "起動時に更新を確認", "Buscar actualizaciones al iniciar"],
  "settings.updatecheckhint": ["啟動後從 GitHub Releases 檢查新版本；即使關閉，仍可手動重新整理專案資訊。", "启动后从 GitHub Releases 检查新版本；即使关闭，仍可手动刷新项目信息。", "Checks GitHub Releases for a new version after startup. Project information can still be refreshed manually when disabled.", "起動後に GitHub Releases で新しいバージョンを確認します。無効にしても、プロジェクト情報は手動で更新できます。", "Busca una nueva versión en GitHub Releases después del inicio. Aunque esté desactivado, la información del proyecto se puede actualizar manualmente."],
  "settings.density": ["介面密度", "界面密度", "UI density", "UI 密度", "Densidad de interfaz"],
  "settings.cornerhint": ["滑塊只覆蓋常用區間；輸入框可直接填更大的數值（超出區間時滑塊自動收起）。", "滑块只覆盖常用区间；输入框可直接填更大的数值（超出区间时滑块自动收起）。", "Slider covers the common range; type any larger value in the box (the slider hides beyond its range).", "スライダーはよく使う範囲のみ。入力欄には任意の大きな値を指定可能（範囲外ではスライダーが隠れます）。", "El control cubre el rango habitual; escribe cualquier valor mayor en el campo (el control se oculta fuera de rango)."],
  "settings.densityhint": ["滑塊只覆蓋 0.8～1.4；輸入框可直接填更大的數值（超出區間時滑塊自動收起）。", "滑块只覆盖 0.8～1.4；输入框可直接填更大的数值（超出区间时滑块自动收起）。", "Slider covers 0.8–1.4; type any larger value in the box (the slider hides beyond its range).", "スライダーは 0.8～1.4。入力欄には任意の大きな値を指定可能（範囲外ではスライダーが隠れます）。", "El control cubre 0,8–1,4; escribe cualquier valor mayor en el campo (el control se oculta fuera de rango)."],
  "settings.anim": ["介面動畫", "界面动画", "UI animations", "UI アニメーション", "Animaciones"],
  "settings.animhint": ["關閉後不播放任何過場動畫，換取最直接的響應。", "关闭后不播放任何过场动画，换取最直接的响应。", "Turning this off removes every transition for the most immediate response.", "オフにすると全ての遷移演出を止め、最速の応答になります。", "Al desactivarlo se eliminan todas las transiciones para la respuesta más inmediata."],
  "settings.autorestart": ["自動重啟後端", "自动重启后端", "Auto-restart backend", "バックエンドを自動再起動", "Reiniciar backend automáticamente"],
  "settings.autorestarthint": ["引擎（後端）意外退出後自動重新拉起，無需手動重啟。", "引擎（后端）意外退出后自动重新拉起，无需手动重启。", "If the engine (backend) exits unexpectedly it is relaunched automatically.", "エンジン（バックエンド）が異常終了したら自動で再起動します。", "Si el motor (backend) falla, se relanza automáticamente."],
  "settings.palettehint": ["配色與明暗互相獨立，均可跟隨系統或手動指定；圓角與密度對所有主題生效。", "配色与明暗互相独立，均可跟随系统或手动指定；圆角与密度对所有主题生效。", "Palette and light/dark mode are independent (each can follow the system or be chosen manually); radius and density apply to every theme.", "配色と明暗は独立（それぞれシステム追従か手動指定）。角丸と密度は全テーマに適用。", "La paleta y el modo claro/oscuro son independientes (ambos pueden seguir al sistema o elegirse); radio y densidad se aplican a todos los temas."],
  "settings.float": ["懸浮視窗樣式", "悬浮窗样式", "Floating window style", "フロート窓スタイル", "Estilo de ventana flotante"],
  "settings.about": ["關於", "关于", "About", "情報", "Acerca de"],
  "settings.behavior": ["介面行為", "界面行为", "Interface behavior", "インターフェース動作", "Comportamiento de la interfaz"],
  "settings.custom": ["自訂主題", "自定义主题", "Custom theme", "カスタムテーマ", "Tema personalizado"],
  "settings.customhint": ["開啟自訂配色後顯示強調/背景/面板取色器，並隱藏預設的明暗與主題色下拉。", "开启自定义配色后显示强调/背景/面板取色器，并隐藏默认的明暗与主题色下拉。", "Turning on custom colors shows accent/background/panel pickers and hides the preset light-dark and palette selectors.", "カスタム配色をオンにすると強調/背景/パネルのピッカーが表示され、既定の明暗・配色の選択肢は隠れます。", "Al activar los colores personalizados aparecen los selectores de color y se ocultan los selectores de modo claro/oscuro y paleta."],
  "settings.gotoabout": ["前往 About 頁", "前往 About 页", "Open the About page", "About ページを開く", "Ir a la página About"],
  "settings.webui": ["Web 介面", "Web 界面", "Web UI", "Web UI", "Interfaz Web"],
  "settings.testfront": ["啟動測試前端", "启动测试前端", "Launch test frontend", "テスト前端を起動", "Abrir frontend de prueba"],
  "settings.appearance": ["外觀", "外观", "Appearance", "外観", "Apariencia"],
  // Login autostart card (P1): method multi-select + silent option.
  "settings.autostart": ["登錄自啟動", "登录自启动", "Start at login", "ログイン時に起動", "Iniciar al iniciar sesión"],
  "settings.recording": ["統一記錄", "统一记录", "Unified recording", "統合記録", "Registro unificado"],
  "record.backends": ["記錄後端", "记录后端", "Recording backends", "記録バックエンド", "Backends de registro"],
  "record.categories": ["記錄類別", "记录类别", "Recording categories", "記録カテゴリ", "Categorías de registro"],
  "record.avatar": ["Avatar", "Avatar", "Avatar", "Avatar", "Avatar"],
  "record.vrchat": ["VRChat", "VRChat", "VRChat", "VRChat", "VRChat"],
  "record.devices": ["裝置連線", "设备连接", "Device connections", "デバイス接続", "Conexiones de dispositivos"],
  "record.heart": ["心率詳情", "心率详情", "Heart-rate details", "心拍数の詳細", "Detalles de frecuencia cardíaca"],
  "record.hardware": ["硬體資訊", "硬件信息", "Hardware information", "ハードウェア情報", "Información de hardware"],
  "record.retention": ["保留天數", "保留天数", "Retention days", "保持日数", "Días de retención"],
  "record.forever": ["永久", "永久", "Forever", "無期限", "Para siempre"],
  "record.directory": ["記錄目錄", "记录目录", "Recording directory", "記録ディレクトリ", "Directorio de registro"],
  "record.saved": ["記錄設定已儲存", "记录设置已保存", "Recording settings saved", "記録設定を保存しました", "Ajustes de registro guardados"],
  "record.savefail": ["記錄設定儲存失敗，已重新讀取", "记录设置保存失败，已重新读取", "Failed to save recording settings; configuration was reloaded", "記録設定の保存に失敗したため、設定を再読み込みしました", "No se pudieron guardar los ajustes; se recargó la configuración"],
  "record.sqlite": ["SQLite", "SQLite", "SQLite", "SQLite", "SQLite"],
  "record.jsonl": ["JSONL", "JSONL", "JSONL", "JSONL", "JSONL"],
  "record.csv": ["CSV", "CSV", "CSV", "CSV", "CSV"],
  "record.hint": ["可同時選擇多個記錄後端；保留天數 0 表示永久；硬體資訊依採集頻率記錄。", "可同时选择多个记录后端；保留天数 0 表示永久；硬件信息按采集频率记录。", "Multiple backends can be selected. Retention 0 means forever. Hardware information follows the collection frequency.", "複数のバックエンドを同時に選択できます。保持日数 0 は無期限です。ハードウェア情報は収集頻度に従います。", "Se pueden elegir varios backends. Retención 0 significa para siempre. El hardware sigue la frecuencia de recopilación."],
  "settings.autostarthint": ["選擇註冊方式（可多選）；全部註冊項都帶 --autostart，重複啟動會靜默讓位給已執行實例。", "选择注册方式（可多选）；全部注册项都带 --autostart，重复启动会静默让位给已运行实例。", "Pick the registration methods (multi-select); every registration passes --autostart and duplicate launches yield silently to the running instance.", "登録方式を選択（複数選択可）。すべての登録は --autostart 付きで、重複起動は実行中のインスタンスに静かに譲ります。", "Elige los métodos de registro (selección múltiple); todos pasan --autostart y los lanzamientos duplicados ceden silenciosamente a la instancia activa."],
  "autostart.task": ["計劃任務", "计划任务", "Task Scheduler", "タスク スケジューラ", "Programador de tareas"],
  "autostart.run": ["註冊表 Run", "注册表 Run", "Registry Run", "レジストリ Run", "Registro Run"],
  "autostart.startup": ["啟動資料夾", "启动文件夹", "Startup folder", "スタートアップ フォルダー", "Carpeta de inicio"],
  "autostart.disabled": ["已停用", "已停用", "Disabled", "無効", "Deshabilitado"],
  "autostart.silent": ["靜默啟動", "静默启动", "Start silently", "サイレント起動", "Inicio silencioso"],
  "autostart.silenthint": ["開機自啟時不打開介面，僅駐留系統匣。", "开机自启时不打开界面，仅驻留系统托盘。", "Autostart keeps the app in the tray without opening the window.", "自動起動時はウィンドウを開かずトレイに常駐します。", "El inicio automático mantiene la app en la bandeja sin abrir la ventana."],
  "autostart.registered": ["已註冊", "已注册", "Registered", "登録済み", "Registrado"],
  "autostart.none": ["無", "无", "none", "なし", "ninguno"],
  "autostart.stale": ["有註冊項指向其他位置或參數已變，重新保存以修復。", "有注册项指向其他位置或参数已变，重新保存以修复。", "A registration points elsewhere or has stale arguments; save again to repair it.", "登録が別の場所を指しているか引数が古いため、再保存すると修復されます。", "Un registro apunta a otra ubicación o tiene argumentos obsoletos; guarda de nuevo para repararlo."],
  // Advanced theme card (#7/#25): detailed frontend appearance settings are saved immediately.
  "settings.advtheme": ["高級主題設定", "高级主题设置", "Advanced Custom Settings", "テーマの詳細設定", "Ajustes avanzados del tema"],
  "settings.advthemehint": ["品牌標題、左上角指示燈、底欄懸停資訊與名稱寬度等細項，改完即存。", "品牌标题、左上角指示灯、底栏悬停信息与名称宽度等细项，改完即存。", "Fine-grained items: brand title, indicator light, status-bar hover info and name width; changes save automatically.", "ブランド名・左上インジケーター・ステータスバーのホバー情報・名前の幅などの細かな項目。変更は自動保存されます。", "Opciones finas: título de la marca, indicador superior, info al pasar el cursor y anchura del nombre; los cambios se guardan automáticamente."],
  "settings.chipw": ["底欄名稱最大寬度", "底栏名称最大宽度", "Max name width", "名前の最大幅", "Ancho máx. del nombre"],
  "settings.chipwhint": ["超出後名稱在懸停時橫向捲動，不會被截斷。", "超出后名称在悬停时横向滚动，不会被截断。", "Names longer than this scroll sideways on hover instead of being cut off.", "この幅を超える名前はホバー時に横へスクロールし、途切れません。", "Los nombres que lo superan se desplazan al pasar el cursor, sin cortarse."],
  "settings.barh": ["底欄高度", "底栏高度", "Bottom bar height", "ステータスバーの高さ", "Altura de la barra inferior"],
  "settings.barhhint": ["0 = 跟隨密度縮放（預設 26px × 密度）；>0 固定像素，側欄收起按鈕同步等高。", "0 = 跟随密度缩放（默认 26px × 密度）；>0 固定像素，侧栏收起按钮同步等高。", "0 = follow density (default 26px × density); >0 pins the height in px; the sidebar collapse button stays aligned.", "0 = 密度に追従（既定 26px × 密度）。>0 で px 固定。サイドバーの折りたたみボタンも同じ高さに。", "0 = seguir densidad (26px × densidad); >0 fija la altura en px; el botón de plegado del panel se mantiene alineado."],
  "settings.rollmode": ["數值動畫", "数值动画", "Number animation", "数値アニメ", "Animación de números"],
  "settings.animroll": ["平滑滾動＋閃爍（原樣）", "平滑滚动＋闪烁（原样）", "Smooth roll + flash (current)", "なめらかスクロール＋フラッシュ（現行）", "Desplazamiento suave + destello (actual)"],
  "settings.animodo": ["碼輪／電表", "码轮／电表", "Odometer (meter)", "オドメーター（メーター）", "Cuentakilómetros (medidor)"],
  "settings.animfade": ["漸隱漸顯", "渐隐渐显", "Fade in/out", "フェードイン／アウト", "Fundido (fade)"],
  "settings.listcap": ["列表顯示上限", "列表显示上限", "List cap (rows)", "リスト表示上限", "Límite de lista"],
  "settings.listcaphint": ["設備/OSC 等長列表只顯示此數量，超出在框內滾動查看。", "设备/OSC 等长列表只显示此数量，超出在框内滚动查看。", "Long lists (devices/OSC…) show this many rows; the rest scroll inside the box.", "長いリスト（デバイス/OSC など）はこの行数まで表示し、残りは枠内スクロール。", "Las listas largas muestran este número de filas; el resto se desplaza dentro de la caja."],
  "settings.advsave": ["儲存並套用", "保存并应用", "Save & apply", "保存して適用", "Guardar y aplicar"],
  "settings.advdraft": ["變更會在儲存後套用；套用後需確認保留，逾時自動還原。", "变更会在保存后应用；应用后需确认保留，超时自动还原。", "Changes apply after saving; confirm to keep, or they revert automatically.", "変更は保存後に適用。保持するには確認が必要で、期限を過ぎると自動的に戻ります。", "Los cambios se aplican al guardar; confírmalos para mantenerlos o se revierten solos."],
  "settings.advconfirm": ["確認保留這些主題設定嗎？", "确认保留这些主题设置吗？", "Keep these theme changes?", "これらのテーマ設定を保持しますか？", "¿Mantener estos ajustes de tema?"],
  "settings.advkeep": ["保留", "保留", "Keep", "保持", "Mantener"],
  "settings.advrevert": ["還原", "还原", "Revert", "元に戻す", "Revertir"],
  "settings.advtimeout": ["15 秒內未確認將自動還原", "15 秒内未确认将自动还原", "Reverts automatically if not confirmed within 15s", "15秒以内に確認がないと自動的に戻ります", "Se revierte automáticamente si no se confirma en 15s"],
  "settings.advanced": ["其他板塊進階設定", "其他板块高级设置", "Advanced settings from other tabs", "他タブの詳細設定", "Ajustes avanzados de otras pestañas"],
  "settings.advhint": ["此處集中各板塊的進階項，與原分頁內的設定同步。", "此处集中各板块的高级项，与原页面内的设置同步。", "Advanced options from other tabs, kept in sync with their own pages.", "各タブの詳細項目をここに集約。元のページと同期します。", "Opciones avanzadas de otras pestañas, sincronizadas con sus páginas."],
  "settings.running": ["運行中", "运行中", "Running", "実行中", "En ejecución"],
  "settings.stopped": ["已停止", "已停止", "Stopped", "停止", "Detenido"],
  "settings.webhint": ["提示：啟動參數 --web 會在程式啟動時自動開啟 Web 介面。", "提示：启动参数 --web 会在程序启动时自动开启 Web 界面。", "Note: the --web launch flag starts the Web UI automatically.", "ヒント：起動引数 --web で Web UI を自動起動します。", "Nota: el parámetro --web inicia la interfaz Web automáticamente."],
  "settings.version": ["版本", "版本", "Version", "バージョン", "Versión"],
  "settings.mode": ["模式", "模式", "Mode", "モード", "Modo"],
  "settings.started": ["啟動時間", "启动时间", "Started", "起動時刻", "Inicio"],
  "settings.dir": ["目錄", "目录", "Directory", "ディレクトリ", "Directorio"],
  "settings.brand": ["品牌標題", "品牌标题", "Brand title", "ブランドタイトル", "Título de marca"],
  "settings.pill": ["左上角指示燈", "左上角指示灯", "Indicator light", "左上のインジケーター", "Indicador superior"],
  "settings.statuspop": ["底欄懸停資訊", "底栏悬停信息", "Status-bar hover info", "ステータスバー ホバー情報", "Info al pasar por la barra inferior"],
  "settings.brandhint": ["左上角標題的 {} 模板，留空顯示預設名稱。可用系統變數（{BPM}/{CPU_USAGE}/{TIME_LOCAL_HMS} 等）與 {ping}/{oscRx}/{oscSent}/{oscFail}/{bpm}/{devices}/{connected}/{version}；未定義的佔位符顯示為空。", "左上角标题的 {} 模板，留空显示默认名称。可用系统变量（{BPM}/{CPU_USAGE}/{TIME_LOCAL_HMS} 等）与 {ping}/{oscRx}/{oscSent}/{oscFail}/{bpm}/{devices}/{connected}/{version}；未定义的占位符显示为空。", "Top-left title {} template; empty shows the default name. Supports system vars ({BPM}/{CPU_USAGE}/{TIME_LOCAL_HMS}…) and {ping}/{oscRx}/{oscSent}/{oscFail}/{bpm}/{devices}/{connected}/{version}; unknown placeholders render empty.", "左上タイトルの {} テンプレート。空欄で既定名。システム変数（{BPM}/{CPU_USAGE}/{TIME_LOCAL_HMS} など）と {ping}/{oscRx}/{oscSent}/{oscFail}/{bpm}/{devices}/{connected}/{version} が使えます。未定義のプレースホルダは空表示。", "Plantilla {} del título superior; vacío muestra el nombre por defecto. Admite variables del sistema ({BPM}/{CPU_USAGE}/{TIME_LOCAL_HMS}…) y {ping}/{oscRx}/{oscSent}/{oscFail}/{bpm}/{devices}/{connected}/{version}; las desconocidas quedan vacías."],
  "settings.path": ["儲存位置", "存储位置", "Storage location", "保存場所", "Ubicación de almacenamiento"],
  "settings.pathhint": ["config.json、日誌、資料庫、匯出與遠端帳戶都存此目錄；靜態資源（webui / 引擎 DLL）仍在程式目錄。", "config.json、日志、数据库、导出与远程账户都存此目录；静态资源（webui / 引擎 DLL）仍在程序目录。", "config.json, logs, database, exports and remote accounts live here; static assets (webui / engine DLL) stay next to the program.", "config.json・ログ・DB・エクスポート・リモートアカウントはここに保存。静的リソース（webui／エンジン DLL）はプログラムの隣に残ります。", "Aquí viven config.json, registros, base de datos, exportaciones y cuentas remotas; los recursos estáticos (webui / DLL del motor) quedan junto al programa."],
  "settings.pathappdata": ["AppData（預設）", "AppData（默认）", "AppData (default)", "AppData（既定）", "AppData (predeterminado)"],
  "settings.pathexedir": ["程式目錄", "程序目录", "Program directory", "プログラムディレクトリ", "Directorio del programa"],
  "settings.pathcurrent": ["目前位置", "当前位置", "Current location", "現在の場所", "Ubicación actual"],
  "settings.pathrestart": ["已保存，重啟後生效", "已保存，重启后生效", "Saved - takes effect after a restart", "保存しました。再起動後に有効です", "Guardado: surte efecto tras reiniciar"],
  "settings.pathfail": ["儲存失敗", "保存失败", "Failed to save", "保存に失敗しました", "No se pudo guardar"],
  "headset.plan": ["內網 UDP 頭顯硬體資訊回傳（規劃中）", "内网 UDP 头显硬件信息回传（规划中）", "In-LAN UDP headset telemetry (planned)", "LAN 内 UDP ヘッドセット情報（予定）", "Telemetría UDP del casco en LAN (planificado)"],

  // ---- Web Remote: secondary frontend ----
  "web.hint": ["第二前端與本機同一套介面，多一層本機認證：用戶庫 + Session（含瀏覽器指紋）+ 角色/板塊白名單。", "第二前端与本机同一套界面，多一层本地认证：用户库 + Session（含浏览器指纹）+ 角色/板块白名单。", "Second frontend serves the same UI but adds a local auth layer: user store + sessions (with browser fingerprint) + role/tab whitelist.", "第2フロントは同じ UI にローカル認証を追加：ユーザー庫＋セッション（指紋）＋役割/タブ白名單。", "El segundo frontend sirve la misma UI con autenticación local: usuarios + sesiones (con huella) + lista de pestañas por rol."],
  "web.session": ["目前會話", "当前会话", "Current session", "現在のセッション", "Sesión actual"],
  "web.logout": ["登出", "登出", "Log out", "ログアウト", "Cerrar sesión"],
  "web.config": ["監聽設定", "监听设置", "Listener", "リスナー設定", "Servidor"],
  "web.enabled": ["啟用第二前端", "启用第二前端", "Enable second frontend", "第2フロントを有効化", "Habilitar segundo frontend"],
  "web.host": ["監聽地址", "监听地址", "Bind host", "バインド先", "Dirección"],
  "web.port": ["監聽端口", "监听端口", "Port", "ポート", "Puerto"],
  "web.loopback": ["僅允許回環連線", "仅允许回环连接", "Loopback only", "ループバックのみ", "Solo bucle local"],
  "web.idle": ["會話閒置過期（分）", "会话闲置过期（分）", "Session idle timeout (min)", "セッション無操作期限（分）", "Caducidad por inactividad (min)"],
  "web.status": ["目前狀態", "当前状态", "Status", "状態", "Estado"],
  "web.on": ["運行中", "运行中", "Running", "実行中", "Activo"],
  "web.off": ["已停止", "已停止", "Stopped", "停止", "Detenido"],
  "web.save": ["儲存並套用", "保存并应用", "Save & apply", "保存して適用", "Guardar y aplicar"],
  "web.confighint": ["0.0.0.0 = 所有網卡；監聽任意地址時非管理員需一次 URL 預留：netsh http add urlacl url=http://+:端口/ user=Users。", "0.0.0.0 = 所有网卡；监听任意地址时非管理员需一次 URL 预留：netsh http add urlacl url=http://+:端口/ user=Users。", "0.0.0.0 = all interfaces; binding any-address as a normal user needs a one-time reservation: netsh http add urlacl url=http://+:port/ user=Users.", "0.0.0.0=全インターフェース。任意アドレスへのバインドは管理者で netsh http add urlacl url=http://+:ポート/ user=Users が必要。", "0.0.0.0 = todas las interfaces; para enlazar necesita reserva: netsh http add urlacl url=http://+:puerto/ user=Users."],
  "web.users": ["本機用戶", "本机用户", "Local users", "ローカルユーザー", "Usuarios locales"],
  "web.usershint": ["admin 可操作全部板塊與授權；user 只能訪問白名單板塊（預設排除 console / API 服務 / 設定 / Web）。", "admin 可操作全部板块与授权；user 只能访问白名单板块（默认排除 console / API 服务 / 设置 / Web）。", "admin gets every tab and privileges; user only sees whitelisted tabs (console / API server / Settings / Web excluded by default).", "admin は全タブと管理権限。user はホワイトリストのみ（console/APIサーバー/設定/Web は既定で除外）。", "admin ve todas las pestañas; user solo las permitidas (console/API/Ajustes/Web excluidas por defecto)."],
  "web.adduser": ["新增用戶", "新增用户", "Add user", "ユーザー追加", "Añadir usuario"],
  "web.username": ["用戶名", "用户名", "Username", "ユーザー名", "Usuario"],
  "web.password": ["密碼", "密码", "Password", "パスワード", "Contraseña"],
  "web.role": ["角色", "角色", "Role", "役割", "Rol"],
  "web.role.admin": ["管理員", "管理员", "Admin", "管理者", "Admin"],
  "web.role.user": ["一般用戶", "普通用户", "User", "一般", "Usuario"],
  "web.tabs": ["板塊白名單（逗號分隔，空=預設）", "板块白名单（逗号分隔，空=默认）", "Tab whitelist (comma separated; empty = default)", "タブ白名单（カンマ区切り、空=既定）", "Pestañas permitidas (separadas por comas; vacío = por defecto)"],
  "web.actions": ["操作", "操作", "Actions", "操作", "Acciones"],
  "web.changepass": ["改密", "改密", "Set password", "パスワード変更", "Cambiar contraseña"],
  "web.deluser": ["刪除", "删除", "Remove", "削除", "Eliminar"],
  "web.newpass": ["新密碼（至少 4 字元）", "新密码（至少 4 字符）", "New password (min 4 chars)", "新パスワード（4文字以上）", "Nueva contraseña (mín. 4 caracteres)"],
  "web.password2": ["確認密碼", "确认密码", "Confirm password", "パスワード確認", "Confirmar contraseña"],
  "web.passhint": ["密碼僅在本機以 PBKDF2-SHA256（20 萬次迭代 + 隨機鹽）雜湊後保存，不會以明文落盤或回顯。", "密码仅在本机以 PBKDF2-SHA256（20 万次迭代 + 随机盐）哈希后保存，不会以明文落盘或回显。", "Passwords are hashed locally with PBKDF2-SHA256 (200k iterations + random salt); never stored or echoed in clear text.", "パスワードはローカルで PBKDF2-SHA256（20万回＋ランダムソルト）によりハッシュ化され、平文で保存・表示されません。", "Las contraseñas se cifran localmente con PBKDF2-SHA256 (200k iteraciones + sal aleatoria); nunca se guardan ni muestran en claro."],
  "web.delhint": ["確定刪除用戶「{name}」？其所有 Session 會一併失效。", "确定删除用户「{name}」？其所有 Session 会一并失效。", "Remove user \"{name}\"? All of their sessions are destroyed too.", "ユーザー「{name}」を削除しますか？そのセッションもすべて失効します。", "¿Eliminar al usuario «{name}»? También se destruyen sus sesiones."],
  "web.err.name": ["請填寫用戶名", "请填写用户名", "Username is required", "ユーザー名を入力してください", "Introduce un usuario"],
  "web.err.short": ["密碼至少 4 個字元", "密码至少 4 个字符", "Password needs at least 4 characters", "パスワードは4文字以上", "La contraseña necesita 4 caracteres"],
  "web.err.mismatch": ["兩次輸入的密碼不一致", "两次输入的密码不一致", "Passwords do not match", "パスワードが一致しません", "Las contraseñas no coinciden"],
  "web.err.failed": ["操作失敗（用戶名可能已存在）", "操作失败（用户名可能已存在）", "Operation failed (the username may already exist)", "操作に失敗しました（ユーザー名が既に存在する可能性）", "Operación fallida (el usuario ya puede existir)"],
  "web.err.lastadmin": ["無法刪除：至少要保留一個管理員", "无法删除：至少要保留一个管理员", "Cannot remove: at least one admin must remain", "削除できません：管理者は1人以上必要です", "No se puede eliminar: debe quedar un administrador"],
  "web.sessions": ["線上 Session", "在线 Session", "Sessions", "セッション", "Sesiones"],
  "web.kick": ["銷毀", "销毁", "Destroy", "破棄", "Destruir"],
  "web.self": ["本機", "本机", "This device", "この端末", "Este dispositivo"],
  "web.ip": ["來源 IP", "来源 IP", "Source IP", "送信元 IP", "IP de origen"],
  "web.last": ["最後活躍", "最后活跃", "Last seen", "最終アクセス", "Última actividad"],
  "web.loginat": ["登入時間", "登录时间", "Signed in at", "ログイン時刻", "Sesión iniciada"],
  "web.bootat": ["後端啟動時間", "后端启动时间", "Backend started", "バックエンド起動", "Inicio del backend"],
  "web.portinfo": ["本機與遠端共用同一個監聽埠；按來源分級授權：回環＝本機管理員、內網＝LAN、公網＝WAN。", "本机与远程共用同一个监听端口；按来源分级授权：回环＝本机管理员、内网＝LAN、公网＝WAN。", "Local and remote share one listener port; authorization follows the source: loopback = local admin, private = LAN, public = WAN.", "ローカルとリモートは同じポートを共有し、送信元ごとに承認されます：ループバック＝ローカル管理者、プライベート＝LAN、パブリック＝WAN。", "Local y remoto comparten un puerto; la autorización sigue el origen: bucle local = admin local, privada = LAN, pública = WAN."],
  "web.lan": ["LAN 存取（內網）", "LAN 访问（内网）", "LAN access (private)", "LAN アクセス（プライベート）", "Acceso LAN (privada)"],
  "web.lanhint": ["允許同一內網（RFC1918/ULA）裝置登入使用；回環永遠免登入。", "允许同一内网（RFC1918/ULA）设备登录使用；回环永远免登录。", "Devices on the same private network (RFC1918/ULA) may sign in; loopback never needs login.", "同じプライベートネットワーク（RFC1918/ULA）の端末はログインして利用できます。ループバックはログイン不要です。", "Los equipos de la misma red privada (RFC1918/ULA) pueden iniciar sesión; el bucle local nunca requiere inicio."],
  "web.wan": ["WAN 存取（公網）", "WAN 访问（公网）", "WAN access (public)", "WAN アクセス（パブリック）", "Acceso WAN (pública)"],
  "web.wanhint": ["允許公網來源登入。埠一旦映射到公網即全世界可達，僅在必要時開啟，並務必使用強密碼。", "允许公网来源登录。端口一旦映射到公网即全世界可达，仅在必要时开启，并务必使用强密码。", "Public sources may sign in. A port mapped to the internet is reachable worldwide; enable only when needed and always with a strong password.", "パブリックな送信元からのログインを許可します。ポートが公開されると世界中から到達可能になるため、必要時のみ有効化し、必ず強いパスワードを使用してください。", "Permite inicios de sesión públicos. Un puerto expuesto a internet es accesible mundialmente; actívalo solo si es necesario y siempre con contraseña fuerte."],
  "web.wantitle": ["開啟 WAN（公網）存取", "开启 WAN（公网）访问", "Enable WAN (public) access", "WAN（パブリック）アクセスを有効化", "Habilitar acceso WAN (pública)"],
  "web.wanconfirm": ["我已了解風險，確認開啟公網存取", "我已了解风险，确认开启公网访问", "I understand the risk and want public access", "リスクを理解した上でパブリックアクセスを有効にします", "Entiendo el riesgo y quiero acceso público"],
  "web.wanpass": ["設定管理員密碼（≥8位，含字母和數字）", "设置管理员密码（≥8位，含字母和数字）", "Set admin password (>=8 chars, letters and digits)", "管理者パスワードを設定（8文字以上、英数字を含む）", "Configurar contraseña de admin (≥8 con letras y dígitos)"],
  "web.wanpass2": ["確認新密碼", "确认新密码", "Confirm new password", "新しいパスワードの確認", "Confirmar nueva contraseña"],
  "web.wanok": ["開啟 WAN", "开启 WAN", "Enable WAN", "WAN を有効化", "Habilitar WAN"],
  "web.wanweak": ["管理員密碼未初始化、仍為預設或強度不足，無法開啟 WAN。", "管理员密码未初始化、仍为默认或强度不足，无法开启 WAN。", "WAN blocked: the admin password is uninitialized, default, or too weak.", "管理者パスワードが未初期化・デフォルト・脆弱のため、WAN を有効化できません。", "WAN bloqueado: la contraseña de admin no está inicializada, es la predeterminada o es débil."],
  "web.zone": ["來源", "来源", "Source", "送信元", "Origen"],
  "web.zone.loopback": ["本機回環", "本机回环", "Loopback", "ループバック", "Bucle local"],
  "web.zone.private": ["內網 (LAN)", "内网 (LAN)", "Private (LAN)", "プライベート (LAN)", "Privada (LAN)"],
  "web.zone.public": ["公網 (WAN)", "公网 (WAN)", "Public (WAN)", "パブリック (WAN)", "Pública (WAN)"],
  "web.boundall": ["已綁定全部網卡（LAN/WAN 可達）", "已绑定全部网卡（LAN/WAN 可达）", "Bound to all interfaces (LAN/WAN reachable)", "全インターフェースでバインド（LAN/WAN 到達可能）", "Enlazado a todas las interfaces (LAN/WAN accesible)"],
  "web.boundloopback": ["僅回環綁定（LAN/WAN 不可達，需 URL ACL）", "仅回环绑定（LAN/WAN 不可达，需 URL ACL）", "Loopback-only bind (LAN/WAN unreachable; needs a URL ACL)", "ループバックのみ（LAN/WAN 不可、URL ACL が必要）", "Solo bucle local (LAN/WAN inaccesible; requiere URL ACL)"],
  "web.adminpass": ["管理員密碼", "管理员密码", "Admin password", "管理者パスワード", "Contraseña de admin"],
  "web.adminpassok": ["已加固", "已加固", "Hardened", "強化済み", "Reforzada"],
  "web.adminpassdefault": ["仍為預設密碼", "仍为默认密码", "Still the default password", "依然としてデフォルトのパスワード", "Sigue siendo la predeterminada"],
  "web.noadmin": ["未初始化管理員", "未初始化管理员", "Admin not initialized", "管理者が未初期化", "Admin sin inicializar"],
  "web.initlocal": ["請先在本機 Web 服務頁新增強密碼管理員，再開啟 LAN/WAN。", "请先在本机 Web 服务页新增强密码管理员，再开启 LAN/WAN。", "Create a strong-password administrator on the local Web page before enabling LAN/WAN.", "LAN/WAN を有効にする前に、ローカル Web ページで強力なパスワードの管理者を作成してください。", "Crea un administrador con contraseña segura en la página web local antes de habilitar LAN/WAN."],
  "remote.mustchange": ["首次登入需修改預設密碼", "首次登录需修改默认密码", "Change the default password to continue", "続行するにはデフォルトのパスワードを変更してください", "Cambia la contraseña predeterminada para continuar"],
  "remote.initweak": ["密碼需≥8位且包含字母和數字", "密码需≥8位且包含字母和数字", "Password must be >=8 chars with letters and digits", "パスワードは8文字以上で英数字を含む必要があります", "La contraseña debe tener ≥8 caracteres con letras y dígitos"],
  "remote.newpass": ["新密碼", "新密码", "New password", "新しいパスワード", "Nueva contraseña"],
  "remote.newpass2": ["確認新密碼", "确认新密码", "Confirm new password", "新しいパスワードの確認", "Confirmar nueva contraseña"],
  "remote.title": ["第二前端登入", "第二前端登录", "Second frontend sign in", "第2フロント サインイン", "Iniciar sesión en 2.º frontend"],
  "remote.hint": ["此頁面來自遠端，需本機用戶帳號登入後才能操作。", "此页面来自远程，需本机用户账号登录后才能操作。", "This page is served over the network; sign in with a local account first.", "このページはネットワーク経由です。ローカルアカウントでサインインしてください。", "Esta página llega por red; inicia sesión con una cuenta local."],
  "remote.err": ["帳號或密碼錯誤", "账号或密码错误", "Wrong username or password", "ユーザー名またはパスワードが違います", "Usuario o contraseña incorrectos"],
  "remote.submit": ["登入", "登录", "Sign in", "サインイン", "Entrar"],
  "web.denied": ["此板塊不在當前遠程角色白名單內", "此板块不在当前远程角色白名单内", "This tab is not in the current remote role whitelist", "このタブは現在のリモート役割では許可されていません", "Esta pestaña no está permitida por el rol remoto actual"],

  // ---- Scanning, recording, and connection toggles ----
  "scan.start": ["開始掃描", "开始扫描", "Start scan", "スキャン開始", "Iniciar escaneo"],
  "scan.stop": ["停止掃描", "停止扫描", "Stop scan", "スキャン停止", "Detener escaneo"],
  "scan.scanning": ["掃描中", "扫描中", "Scanning", "スキャン中", "Escaneando"],
  "scan.stopped": ["已停止", "已停止", "Stopped", "停止", "Detenido"],
  "record.start": ["開始記錄", "开始记录", "Start recording", "記録開始", "Iniciar registro"],
  "record.stop": ["停止記錄", "停止记录", "Stop recording", "記録停止", "Detener registro"],
  "record.label": ["記錄", "记录", "Recording", "記録", "Registro"],
  "osc.connect": ["連線 OSC", "连接 OSC", "Connect OSC", "OSC 接続", "Conectar OSC"],
  "osc.disconnect": ["中斷 OSC", "断开 OSC", "Disconnect OSC", "OSC 切断", "Desconectar OSC"],
  "osc.autostart": ["啟動程式後自動推送", "启动程序后自动推送", "Start pushing automatically", "起動後に自動送信", "Iniciar envío automáticamente"],
  "osc.autostarthint": ["主程式啟動後自動連線並開始 OSC 推送", "主程序启动后自动连接并开始 OSC 推送", "Connect and start OSC pushing when the main program starts", "メインプログラム起動後に接続して OSC 送信を開始します", "Conecta e inicia el envío OSC al arrancar el programa principal"],
  "osc.paramcount": ["個參數", "个参数", "parameters", "個のパラメータ", "parámetros"],
  "osc.noparams": ["暫無 OSC 回傳參數（確認 VRChat 正在執行，且 OSC 已設定為傳送至本機 9001）。", "暂无 OSC 回传参数（确认 VRChat 在运行并已配置 OSC → 发送至本机 9001）。", "No inbound OSC parameters yet (check VRChat is running and OSC sends to 127.0.0.1:9001).", "OSC パラメータがまだありません（VRChat が起動し、OSC が 127.0.0.1:9001 宛てになっているか確認）。", "Aún no hay parámetros OSC entrantes (verifica que VRChat esté activo y envíe OSC a 127.0.0.1:9001)."],
  "osc.pagehint": ["概覽顯示 VRChat 回傳的世界、姿態與 Avatar 資訊；資料頁列出全部位址。", "概览显示 VRChat 回传的世界、姿态与 Avatar 信息；数据页列出全部地址。", "Overview shows world, pose and avatar data from VRChat; Data lists every address.", "概要は VRChat から届くワールド・姿勢・アバター情報。データは全アドレス一覧。", "Resumen muestra mundo, postura y avatar desde VRChat; Datos lista todas las direcciones."],
  "osc.taboverview": ["概覽", "概览", "Overview", "概要", "Resumen"],
  "osc.tabdata": ["資料", "数据", "Data", "データ", "Datos"],
  "osc.avatar": ["Avatar", "Avatar", "Avatar", "アバター", "Avatar"],
  "osc.avatarid": ["Avatar 識別碼", "Avatar 标识", "Avatar ID", "アバター ID", "ID de avatar"],
  "osc.paramtotal": ["參數總數", "参数总数", "Parameters", "パラメータ数", "Parámetros"],
  "osc.world": ["世界 / 房間", "世界 / 房间", "World / instance", "ワールド / インスタンス", "Mundo / instancia"],
  "osc.worldhint": ["VRChat 的 OSC 不會回傳世界識別碼，此處僅顯示可由參數推得的房間狀態。", "VRChat 的 OSC 不回传世界标识，这里只显示能由参数推得的房间状态。", "VRChat's OSC does not expose the world ID; only instance state derived from parameters is shown.", "VRChat の OSC はワールド ID を送らないため、パラメータから分かる状態のみ表示。", "El OSC de VRChat no envía el ID del mundo; solo se muestra el estado deducible."],
  "osc.state": ["玩家狀態", "玩家状态", "Player state", "プレイヤー状態", "Estado del jugador"],
  "osc.motion": ["移動 / 速度", "移动 / 速度", "Motion", "移動 / 速度", "Movimiento"],
  "osc.gesture": ["手勢 / 表情", "手势 / 表情", "Gestures", "ジェスチャー", "Gestos"],
  "osc.tracking": ["World Transform（追蹤）", "World Transform（追踪）", "World Transform (tracking)", "World Transform（トラッキング）", "World Transform (tracking)"],
  "osc.trackinghint": ["未收到 /tracking/* 位址（需在 VR 模式或啟用全身追蹤時才會回傳）。", "未收到 /tracking/* 地址（需在 VR 模式或启用全身追踪时才会回传）。", "No /tracking/* addresses yet (sent only in VR mode or with full-body tracking).", "/tracking/* が未受信（VR モードまたはフルトラッキング時のみ送信）。", "Sin direcciones /tracking/* (solo en modo VR o con seguimiento corporal)."],
  "osc.custom": ["自訂參數", "自定义参数", "Custom parameters", "カスタムパラメータ", "Parámetros personalizados"],
  "push.custom": ["自訂發送", "自定义发送", "Custom send", "カスタム送信", "Envío personalizado"],
  "push.customhint": ["向 VRChat 等目標發送一條文本/參數（手機端遠端操作也走這裡）；文本支援 {BPM} 等 {} 變數。", "向 VRChat 等目标发送一条文本/参数（手机端远程操作也走这里）；文本支持 {BPM} 等 {} 变量。", "Send one text/parameter to VRChat etc. (also how a phone sends remotely); the text supports {} variables like {BPM}.", "VRChat などへ1件のテキスト/パラメータを送信（スマホ遠隔もこれ）。{BPM} 等の {} 変数対応。", "Envía un texto/parámetro a VRChat, etc. (también desde el móvil); el texto admite {} como {BPM}."],
  "push.pause": ["發送後暫停推送器（秒）", "发送后暂停推送器（秒）", "Pause pusher after send (s)", "送信後プッシャーを一時停止（秒）", "Pausar el pusher tras enviar (s)"],
  "push.kindlabel": ["發送類型", "发送类型", "Send as", "送信タイプ", "Enviar como"],
  "push.kindtext": ["文本", "文本", "Text", "テキスト", "Texto"],
  "push.kindfloat": ["數值", "数值", "Float", "数値", "Float"],
  "push.kindbool": ["開關", "开关", "Toggle", "トグル", "Interruptor"],
  "push.floatval": ["支援 {} 變量，渲染後轉為數值", "支持 {} 变量，渲染后转为数值", "Supports {} variables; rendered then sent as a number", "{} 変数対応。展開後に数値として送信", "Admite variables {}; se renderiza y envía como número"],
  "push.boolval": ["開關狀態", "开关状态", "Toggle state", "トグル状態", "Estado del interruptor"],
  "push.preview": ["模板預覽", "模板预览", "Template preview", "テンプレートプレビュー", "Vista previa de plantilla"],
  "push.previewhint": ["以當前系統變量實時渲染，每秒刷新", "以当前系统变量实时渲染，每秒刷新", "Rendered live with current system vars, refreshes every second", "現在のシステム変数で毎秒ライブ更新", "Se renderiza con las variables actuales; se actualiza cada segundo"],
  "push.previewempty": ["（模板為空或引擎離線）", "（模板为空或引擎离线）", "(Template empty or engine offline)", "（テンプレート未入力またはエンジン未接続）", "(Plantilla vacía o motor sin conexión)"],
  "push.charwarn": ["已超過 134 字：VRChat 聊天框上限 144 字，超出內容可能不顯示。僅提示，不會阻擋發送。", "已超过 134 字：VRChat 聊天框上限 144 字，超出内容可能不显示。仅提示，不会阻挡发送。", "Over 134 chars: VRChat caps the ChatBox at 144; excess text may not display. Hint only, sending is not blocked.", "134字を超過：VRChat チャットボックスは144字まで。超過分は表示されない場合があります。通知のみで送信は妨げません。", "Más de 134 caracteres: VRChat limita el ChatBox a 144; el exceso puede no mostrarse. Solo aviso, no bloquea el envío."],
  "vrc.status": ["VRChat 運行狀態", "VRChat 运行状态", "VRChat status", "VRChat ステータス", "Estado de VRChat"],
  "vrc.running": ["執行中", "运行中", "Running", "実行中", "En ejecución"],
  "vrc.notrunning": ["未運行（未偵測到進程）", "未运行（未检测到进程）", "Not running (no process found)", "未実行（プロセス未検出）", "No en ejecución (no se encuentra el proceso)"],
  "vrc.pid": ["PID", "PID", "PID", "PID", "PID"],
  "vrc.cpu": ["CPU", "CPU", "CPU", "CPU", "CPU"],
  "vrc.mem": ["記憶體", "内存", "Memory", "メモリ", "Memoria"],
  "vrc.started": ["啟動時間", "启动时间", "Started at", "起動時刻", "Iniciado a las"],
  "vrc.ok": ["回應正常", "响应正常", "Responding", "応答あり", "Responde"],
  "vrc.stuck": ["無回應", "无响应", "Not responding", "無応答", "Sin respuesta"],
  "vrc.launch": ["啟動 VRChat", "启动 VRChat", "Launch VRChat", "VRChat を起動", "Iniciar VRChat"],
  "vrc.launchhint": ["自動偵測 VRChat 安裝位置並啟動；找不到本機安裝時改用 Steam 啟動。運行中不會重複啟動。", "自动检测 VRChat 安装位置并启动；找不到本机安装时改用 Steam 启动。运行中不会重复启动。", "Detects the local VRChat install and launches it; falls back to Steam when none is found. Never launches a second copy while running.", "VRChat のインストール先を検出して起動します。見つからない場合は Steam 経由で起動。実行中は二重起動しません。", "Detecta la instalación local de VRChat y la inicia; si no existe, usa Steam. No inicia una segunda copia en ejecución."],
  "vrc.launchfail": ["啟動 VRChat 失敗", "启动 VRChat 失败", "Failed to launch VRChat", "VRChat の起動に失敗しました", "No se pudo iniciar VRChat"],
  "dev.connect": ["連線", "连接", "Connect", "接続", "Conectar"],
  "dev.disconnect": ["中斷", "断开", "Disconnect", "切断", "Desconectar"],
  "dev.connected": ["已連線", "已连接", "Connected", "接続済み", "Conectado"],
  "dev.connecting": ["連線中...", "连接中...", "Connecting...", "接続中...", "Conectando..."],
  "dev.disconnected": ["未連線", "未连接", "Not connected", "未接続", "Sin conexión"],
  "dev.signalweak": ["訊號弱", "信号弱", "Weak signal", "信号が弱い", "Señal débil"],
  "dev.signalcritical": ["訊號極弱", "信号极弱", "Critical signal", "信号が非常に弱い", "Señal crítica"],
  "dev.critical": ["極弱閾值", "极弱阈值", "Critical threshold", "極弱しきい値", "Umbral crítico"],
  "dev.autodetect": ["自動偵測", "自动检测", "Auto detect", "自動検出", "Detección automática"],
  "dev.autodetectstop": ["停止偵測", "停止检测", "Stop detect", "検出を停止", "Detener detección"],
  "dev.autodetecthint": ["按綜合分依次試連，找到會回報心率的裝置就保持連線（自動跳過音訊與智慧家居）。", "按综合分依次试连，找到会报告心率的设备就保持连接（自动跳过音频与智能家居）。", "Tries devices by score and keeps the first one reporting heart rate (audio and smart-home devices are skipped).", "総合スコア順に接続を試し、心拍を報告するデバイスで停止（オーディオ・スマートホームは除外）。", "Prueba por puntuación y conserva el primero que reporte ritmo (omite audio y domótica)."],
  "dev.autoconnect": ["啟動時自動連線上次裝置", "启动时自动连接上次设备", "Auto connect last device", "起動時に前回のデバイスへ接続", "Conectar al último dispositivo"],
  "dev.detecttimeout": ["單台超時 (秒)", "单台超时 (秒)", "Per-device timeout (s)", "1台あたりの上限 (秒)", "Tiempo por dispositivo (s)"],
  "dev.detecting": ["偵測中", "检测中", "Detecting", "検出中", "Detectando"],
  "dev.nohrchar": ["無心率特徵", "无心率特征", "No HR characteristic", "心拍特性なし", "Sin característica de ritmo"],
  "dev.notconnected": ["未連線", "未连接", "Not connected", "未接続", "Sin conexión"],
  "dev.save": ["儲存裝置", "保存设备", "Save device", "デバイス保存", "Guardar dispositivo"],
  "dev.unsave": ["移除儲存", "移除保存", "Unsave device", "保存解除", "Quitar guardado"],
  "dev.block": ["封鎖", "屏蔽", "Block", "ブロック", "Bloquear"],
  "dev.unblock": ["解除封鎖", "解除屏蔽", "Unblock", "ブロック解除", "Desbloquear"],
  "dev.blocklist": ["封鎖管理", "屏蔽管理", "Blocked list", "ブロック管理", "Lista bloqueada"],
  "dev.blockedhint": ["被屏蔽的设备不会显示在任何列表（扫描/连接/自动检测均跳过），需要时在此解除。", "被屏蔽的设备不会显示在任何列表（扫描/连接/自动检测均跳过），需要时在此解除。", "Blocked devices stay hidden from every list (scan/connect/auto-detect skip them). Unblock them here.", "ブロックしたデバイスはすべてのリストから隠れます（スキャン/接続/自動検出はスキップ）。ここで解除できます。", "Los dispositivos bloqueados quedan ocultos de toda lista (escaneo/conexión/detección los omiten). Desbloquéalos aquí."],
  "dev.selectAll": ["全選", "全选", "Select all", "すべて選択", "Seleccionar todo"],
  "dev.invert": ["反選", "反选", "Invert selection", "選択を反転", "Invertir selección"],
  "dev.clearSel": ["清空", "清空选择", "Clear selection", "選択解除", "Limpiar selección"],
  "dev.weightsort": ["權重排序", "权重排序", "Weight sort", "重み順で並べ替え", "Orden por peso"],
  "dev.rename": ["重新命名", "重命名", "Rename", "名前変更", "Renombrar"],
  "dev.alias": ["別名", "别名", "Alias", "エイリアス", "Alias"],
  "dev.rssi": ["訊號", "信号", "Signal", "信号", "Señal"],
  "dev.rate": ["回報頻率", "报告频率", "Report rate", "報告頻度", "Frecuencia"],
  "dev.advrate": ["廣播頻率", "广播频率", "Adv. rate", "アドバタイズ頻度", "Frec. anuncio"],
  "dev.notifyrate": ["回報頻率", "报告频率", "Report rate", "報告頻度", "Frec. informe"],
  "dev.advratehint": ["裝置發送廣播封包的速率（僅掃描期間可得）", "设备发送广播包的速率（仅扫描期间可得）", "Rate at which the device broadcasts advertising packets (scan only)", "デバイスがアドバタイズを送る頻度（スキャン中のみ）", "Frecuencia de anuncios del dispositivo (solo al escanear)"],
  "dev.notifyratehint": ["已連線裝置推送心率通知的速率", "已连接设备推送心率通知的速率", "Rate at which a connected device pushes heart-rate notifications", "接続済みデバイスが心拍通知を送る頻度", "Frecuencia de notificaciones de ritmo del dispositivo conectado"],
  "dev.rssihint": ["連線後藍牙堆疊不再回報廣播訊號強度，因此顯示為 —", "连接后蓝牙栈不再上报广播信号强度，因此显示为 —", "After connecting, the Bluetooth stack no longer reports advertising RSSI, so it shows —", "接続後は Bluetooth スタックが広告 RSSI を報告しないため — と表示されます", "Tras conectar, la pila Bluetooth ya no informa el RSSI, por eso muestra —"],
  "dev.type": ["類型", "类型", "Type", "種類", "Tipo"],
  "dev.mac": ["MAC 位址", "MAC 地址", "MAC address", "MAC アドレス", "Dirección MAC"],
  "dev.state": ["狀態", "状态", "State", "状態", "Estado"],
  "dev.ops": ["操作", "操作", "Actions", "操作", "Acciones"],
  "dev.detail": ["裝置詳情", "设备详情", "Device details", "デバイス詳細", "Detalles del dispositivo"],
  "dev.reports": ["回報數", "上报数", "Reports", "報告数", "Reportes"],
  "dev.clickhint": ["單擊：詳情 · 雙擊：連接/斷開", "单击：详情 · 双击：连接/断开", "Single click: details · Double click: connect/disconnect", "クリック：詳細 ・ ダブルクリック：接続/切断", "Clic: detalles · Doble clic: conectar/desconectar"],
  "dev.taboverview": ["概覽", "概览", "Overview", "概要", "Resumen"],
  "dev.tabconn": ["連接記錄", "连接记录", "Connection log", "接続ログ", "Registro de conexión"],
  "dev.tabhr": ["心率歷史", "心率历史", "HR history", "心拍履歴", "Historial de ritmo"],
  "dev.lastreport": ["最近記錄", "最近记录", "Latest entry", "最新の記録", "Último registro"],
  "dev.norecords": ["暫無歷史記錄（需在心率頁開啟「記錄」才會入庫）", "暂无历史记录（需在心率页开启「记录」才会入库）", "No history yet (recording must be enabled on the HR page to store samples)", "履歴なし（心拍ページで「記録」を有効にすると保存されます）", "Sin historial (debes activar el registro en la página de ritmo)"],
  "dev.colreset": ["重設列寬", "重置列宽", "Reset columns", "列幅をリセット", "Restablecer columnas"],
  "dev.colhint": ["拖曳表頭分隔線可調整列寬（自動保存）", "拖动表头分隔线可调整列宽（自动保存）", "Drag the header dividers to resize columns (saved automatically)", "ヘッダーの区切りをドラッグして列幅を変更（自動保存）", "Arrastra los divisores del encabezado para ajustar columnas (se guarda)"],
  "dev.autoreconnect": ["自動重連", "自动重连", "Auto reconnect", "自動再接続", "Reconexión automática"],
  "dev.scaninterval": ["掃描間隔 (ms)", "扫描间隔 (ms)", "Scan interval (ms)", "スキャン間隔 (ms)", "Intervalo (ms)"],
  "dev.continuous": ["持續掃描", "持续扫描", "Continuous scan", "連続スキャン", "Escaneo continuo"],
  "dev.retry": ["重試間隔 (秒)", "重试间隔 (秒)", "Retry interval (s)", "再試行間隔 (秒)", "Reintento (s)"],
  "dev.giveup": ["放棄時限 (分)", "放弃时限 (分)", "Give up after (min)", "諦める時間 (分)", "Abandonar tras (min)"],
  "dev.weak": ["訊號弱閾值", "信号弱阈值", "Weak signal threshold", "弱信号しきい値", "Umbral de señal débil"],
  "dev.saved": ["裝置策略已儲存", "设备策略已保存", "Device policy saved", "デバイス設定を保存しました", "Política de dispositivos guardada"],
  "dev.policy": ["裝置策略", "设备策略", "Device policy", "デバイス設定", "Política de dispositivo"],
  "dev.cfghint": ["持續掃描不設時長上限；刷新間隔用於抑制列表抖動。", "持续扫描不设时长上限；刷新间隔用于抑制列表抖动。", "Continuous scan has no time limit; the refresh interval reduces list flicker.", "連続スキャンに時間制限なし。更新間隔で一覧のちらつきを抑制。", "El escaneo continuo no tiene límite; el intervalo reduce el parpadeo."],
  "dev.history": ["歷史裝置", "历史设备", "Known devices", "履歴デバイス", "Dispositivos conocidos"],
  "dev.empty": ["沒有裝置，請點「開始掃描」。", "没有设备，请点击「开始扫描」。", "No devices. Click \"Start scan\".", "デバイスなし。「スキャン開始」を押してください。", "Sin dispositivos. Pulsa \"Iniciar escaneo\"."],
  "float.lock": ["鎖定懸浮視窗", "锁定悬浮窗", "Lock overlay", "オーバーレイをロック", "Bloquear superposición"],
  "float.main": ["主視窗", "主悬浮窗", "Main overlay", "メインオーバーレイ", "Superposición principal"],
  "float.fmthint": ["文字原樣顯示；{bpm}=實時心率；{img}=背景圖片", "文本原样显示；{bpm}=实时心率；{img}=背景图片", "Text is shown as-is; {bpm}=live heart rate; {img}=background image", "テキストはそのまま表示。{bpm}=リアルタイム心拍、{img}=背景画像", "El texto se muestra tal cual; {bpm}=frecuencia cardíaca; {img}=imagen de fondo"],
  "float.default": ["恢復預設格式", "恢复默认格式", "Reset to default format", "既定の書式に戻す", "Restablecer formato predeterminado"],
  "float.unlock": ["解除鎖定", "解除锁定", "Unlock overlay", "ロック解除", "Desbloquear"],
  "float.source": ["主視窗來源", "主窗数据源", "Main overlay source", "メイン窓のソース", "Fuente principal"],
  "float.refresh": ["刷新間隔 (ms)", "刷新间隔 (ms)", "Refresh interval (ms)", "更新間隔 (ms)", "Intervalo (ms)"],
  "float.perwindow": ["各裝置視窗", "各设备窗口", "Per-device overlays", "デバイス別ウィンドウ", "Ventanas por dispositivo"],
  "float.opendev": ["開啟懸浮視窗", "开启悬浮窗", "Open overlay", "オーバーレイを開く", "Abrir capa"],
  "float.closedev": ["關閉懸浮視窗", "关闭悬浮窗", "Close overlay", "オーバーレイを閉じる", "Cerrar capa"],
  "float.openall": ["開啟全部設備窗", "打开全部设备窗", "Open all device overlays", "全デバイス窓を開く", "Abrir todas las ventanas"],
  "float.closeall": ["關閉全部", "关闭全部", "Close all", "すべて閉じる", "Cerrar todas"],
  "float.format": ["格式（{bpm}/{img}）", "格式（{bpm}/{img}）", "Format ({bpm}/{img})", "書式（{bpm}/{img}）", "Formato ({bpm}/{img})"],
  "float.unlockcolor": ["解鎖顏色", "解锁颜色", "Unlocked color", "ロック解除時の色", "Color desbloqueado"],
  "float.lockcolor": ["鎖定顏色", "锁定颜色", "Locked color", "ロック時の色", "Color bloqueado"],
  "float.geometry": ["幾何（寬x高+X+Y）", "几何（宽x高+X+Y）", "Geometry (WxH+X+Y)", "ジオメトリ（幅x高+X+Y）", "Geometría (AnxAl+X+Y)"],
  "float.image": ["圖片路徑", "图片路径", "Image path", "画像パス", "Ruta de imagen"],
  "float.saved": ["懸浮視窗設定已儲存", "悬浮窗设置已保存", "Overlay settings saved", "オーバーレイ設定を保存しました", "Ajustes de superposición guardados"],
  "web.start": ["啟動 Web 介面", "启动 Web 界面", "Start Web UI", "Web UI 開始", "Iniciar Web UI"],
  "web.stop": ["停止 Web 介面", "停止 Web 界面", "Stop Web UI", "Web UI 停止", "Detener Web UI"],
  "logs.follow": ["自動滾動", "自动滚动", "Auto scroll", "自動スクロール", "Desplazamiento automático"],
  "logs.dump": ["轉存", "转储", "Dump", "ダンプ", "Volcar"],
  "logs.dumped": ["已轉存", "已转储", "Dumped", "ダンプ完了", "Volcado"],
  "logs.dumpfail": ["轉存失敗", "转储失败", "Dump failed", "ダンプ失敗", "Fallo al volcar"],
  "logs.filterhint": ["關鍵字 / 正規表示式", "关键字 / 正则", "Keyword / regex", "キーワード / 正規表現", "Palabra clave / regex"],
  "logs.regex": ["正規表示式", "正则", "Regex", "正規表現", "Regex"],
  "logs.level": ["等級", "等级", "Level", "レベル", "Nivel"],
  "logs.matched": ["命中", "命中", "Matched", "一致", "Coincidencias"],
  "logs.badregex": ["正規表示式錯誤", "正则语法错误", "Invalid regex", "正規表現エラー", "Regex no válida"],
  "logs.exportfiltered": ["匯出篩選結果", "导出筛选结果", "Export filtered", "抽出結果を書き出す", "Exportar filtrados"],
  "logs.exported": ["已匯出日誌", "已导出日志", "Logs exported", "ログを書き出しました", "Registros exportados"],
  "logs.exportfail": ["日誌匯出失敗", "日志导出失败", "Log export failed", "ログの書き出しに失敗", "Fallo al exportar registros"],
  "logs.exporthint": ["匯出至程式目錄 exports/，僅含目前篩選結果", "导出至程序目录 exports/，仅含当前筛选结果", "Exports the current filtered lines to exports/", "現在の抽出結果のみを exports/ に書き出します", "Exporta las líneas filtradas a exports/"],
  "logs.trace": ["Trace 診斷等級", "Trace 诊断等级", "Trace level", "Trace 診断レベル", "Nivel Trace"],
  "logs.tracehint": ["記錄管道 / Web / BLE 的耗時打點到 logs/trace.log，用於定位難以復現的效能問題。", "记录管道 / Web / BLE 的耗时打点到 logs/trace.log，用于定位难以复现的性能问题。", "Writes pipe / Web / BLE timing marks to logs/trace.log for hard-to-repro performance issues.", "パイプ / Web / BLE の所要時間を logs/trace.log に記録し、再現しにくい性能問題を特定します。", "Registra marcas de tiempo de pipe / Web / BLE en logs/trace.log para problemas difíciles de reproducir."],
  "logs.tracerestart": ["需重新啟動程式後生效", "需重启程序后生效", "Takes effect after restart", "再起動後に有効", "Se aplica tras reiniciar"],
  "logs.traceactive": ["本次執行已啟用", "本次运行已启用", "Active in this session", "今回の実行で有効", "Activo en esta sesión"],
  "logs.traceinactive": ["本次執行未啟用", "本次运行未启用", "Inactive in this session", "今回の実行では無効", "Inactivo en esta sesión"],

  // ---- HeartBeat ----
  "hb.current": ["目前心跳", "当前心率", "Current HR", "現在の心拍", "Ritmo actual"],
  "hb.average": ["平均", "平均", "Average", "平均", "Promedio"],
  "hb.min": ["最低", "最低", "Min", "最低", "Mín"],
  "hb.max": ["最高", "最高", "Max", "最高", "Máx"],
  "hb.winstats": ["曲線視窗統計", "曲线窗口统计", "Curve-window stats", "曲線ウィンドウの統計", "Estadísticas de la ventana de curva"],
  "hb.curve": ["心跳曲線", "心率曲线", "HR curve", "心拍カーブ", "Curva de ritmo"],
  "hb.smooth": ["平滑度", "平滑度", "Smoothing", "スムージング", "Suavizado"],
  "hb.mode": ["顯示模式", "显示模式", "Chart mode", "表示モード", "Modo de gráfico"],
  "hb.modearea": ["面積圖", "面积图", "Area", "エリア", "Área"],
  "hb.modeline": ["折線圖", "折线图", "Line", "折れ線", "Línea"],
  "hb.modebars": ["柱狀圖", "柱状图", "Bars", "棒グラフ", "Barras"],
  "hb.modedots": ["散點圖", "散点图", "Dots", "散布図", "Puntos"],
  "hb.modestep": ["階梯圖", "阶梯图", "Step", "ステップ", "Escalera"],
  "hb.modegradient": ["漸層面積", "渐变面积", "Gradient", "グラデーション", "Degradado"],
  "hb.srccurve": ["曲線來源", "曲线来源", "Curve source", "カーブのソース", "Origen de curva"],
  "hb.srcmainhr": ["主顯示來源", "主显示来源", "Main HR source", "メイン表示のソース", "Origen principal"],
  "hb.srcmain": ["主心率", "主心率", "Main HR", "メイン心拍", "Ritmo principal"],
  "hb.window": ["記錄時長 (秒)", "记录时长 (秒)", "History (s)", "記録時間 (秒)", "Historial (s)"],
  "hb.health": ["健康狀態", "健康状态", "Health status", "健康状態", "Estado de salud"],
  "hb.calibrate": ["開始校正（站立靜息 30 秒）", "开始校准（站立静息 30 秒）", "Calibrate (30s standing rest)", "キャリブレーション（30秒安静立位）", "Calibrar (30 s de reposo)"],
  "hb.calibrating": ["校正中...", "校准中...", "Calibrating...", "校正中...", "Calibrando..."],
  "hb.cancelcal": ["取消校正", "取消校准", "Cancel calibration", "校正を中止", "Cancelar calibración"],
  "hb.baseline": ["靜息基準", "静息基准", "Resting baseline", "安静時基準", "Línea base"],
  "hb.advanced": ["進階設定", "高级设置", "Advanced", "詳細設定", "Avanzado"],
  "hb.overlay": ["懸浮視窗", "悬浮窗", "Overlay", "オーバーレイ", "Superposición"],
  "hb.dataexport": ["資料匯出", "数据导出", "Data export", "データ書き出し", "Exportar datos"],
  "hb.pickdevice": ["繪製裝置", "绘制设备", "Plot device", "描画デバイス", "Dispositivo"],
  "hb.status.sleep": ["睡眠", "睡眠", "Sleeping", "睡眠", "Durmiendo"],
  "hb.status.rest": ["靜息", "静息", "Resting", "安静", "Reposo"],
  "hb.status.active": ["活躍", "活跃", "Active", "活動中", "Activo"],
  "hb.status.excited": ["興奮", "兴奋", "Excited", "興奮", "Excitado"],
  "hb.status.unknown": ["未知", "未知", "Unknown", "不明", "Desconocido"],
  "hb.sleepfactor": ["睡眠係數", "睡眠系数", "Sleep factor", "睡眠係数", "Factor de sueño"],
  "hb.activefactor": ["活躍係數", "活跃系数", "Active factor", "活動係数", "Factor activo"],
  "hb.excitedfactor": ["興奮係數", "兴奋系数", "Excited factor", "興奮係数", "Factor de excitación"],
  "hb.spike": ["波動告警 (BPM)", "波动告警 (BPM)", "Spike alert (BPM)", "変動アラート (BPM)", "Alerta de picos (BPM)"],
  "hb.record": ["狀態入庫", "状态入库", "Store status", "状態を保存", "Guardar estado"],
  "hb.saved": ["健康判定參數已儲存", "健康判定参数已保存", "Health parameters saved", "健康判定パラメータを保存しました", "Parámetros de salud guardados"],
  "hb.cached": ["已快取樣本", "已缓存样本", "Cached samples", "キャッシュ済みサンプル", "Muestras en caché"],
  "hb.limit": ["上限", "上限", "limit", "上限", "límite"],
  "hb.waiting": ["等待心跳資料...", "等待心率数据...", "Waiting for heart rate data...", "心拍データ待機中...", "Esperando datos de ritmo..."],

  // ---- HWInfo ----
  "hw.vars": ["變數", "变量", "Variables", "変数", "Variables"],
  "hw.override": ["手動覆寫", "手动覆写", "Override", "上書き", "Sobrescribir"],
  "hw.custom": ["自訂變數", "自定义变量", "Custom variables", "カスタム変数", "Variables personalizadas"],
  "hw.expr": ["運算式", "表达式", "Expression", "式", "Expresión"],
  "hw.kind": ["類型", "类型", "Kind", "種別", "Tipo"],
  "hw.decimals": ["小數位", "小数位", "Decimals", "小数桁", "Decimales"],
  "hw.usefloat": ["輸出浮點", "输出浮点", "Write floats", "浮動小数を出力", "Escribir flotantes"],
  "hw.round": ["四捨五入", "四舍五入", "Round", "四捨五入", "Redondear"],
  "hw.ntp": ["NTP 伺服器", "NTP 服务器", "NTP server", "NTP サーバー", "Servidor NTP"],
  "hw.ntppreset": ["預設伺服器", "预设服务器", "Presets", "プリセット", "Preajustes"],
  "hw.time": ["時間變數", "时间变量", "Time variables", "時間変数", "Variables de tiempo"],
  "hw.interval": ["採集間隔 (ms)", "采集间隔 (ms)", "Sample interval (ms)", "取得間隔 (ms)", "Intervalo de muestreo (ms)"],
  "hw.saved": ["硬體變數設定已儲存", "硬件变量设置已保存", "Hardware settings saved", "ハードウェア設定を保存しました", "Ajustes de hardware guardados"],
  "hw.ovsaved": ["變數覆寫已儲存", "变量覆写已保存", "Override saved", "上書きを保存しました", "Sobrescritura guardada"],
  "hw.cvsaved": ["自訂變數已儲存", "自定义变量已保存", "Custom variable saved", "カスタム変数を保存しました", "Variable personalizada guardada"],
  "hw.ovhint": ["支援 {變數} 與四則運算，如 {RAM_USED}*1024", "支持 {变量} 与四则运算，如 {RAM_USED}*1024", "Supports {vars} and arithmetic, e.g. {RAM_USED}*1024", "{変数} と四則演算に対応（例 {RAM_USED}*1024）", "Admite {variables} y aritmética, p. ej. {RAM_USED}*1024"],
  "hw.kindhint": ["運算＝四則求值；拼接＝僅替換 {變數}；正規＝對拼接結果取第 1 組；命令列＝取 stdout", "运算=四则求值；拼接=仅替换 {变量}；正则=对拼接结果取第 1 组；命令行=取 stdout", "expr = arithmetic; concat = substitute {vars} only; regex = first group of the concatenated text; cmd = stdout", "expr＝四則演算／concat＝{変数}置換のみ／regex＝連結結果の第1グループ／cmd＝stdout", "expr = aritmética; concat = solo sustituye {vars}; regex = primer grupo; cmd = stdout"],
  "hw.kind.expr": ["運算", "运算", "Expression", "演算", "Expresión"],
  "hw.kind.concat": ["拼接", "拼接", "Concat", "連結", "Concatenar"],
  "hw.kind.regex": ["正規", "正则", "Regex", "正規表現", "Regex"],
  "hw.kind.cmd": ["命令列", "命令行", "Command", "コマンド", "Comando"],
  "hw.pattern": ["正規表示式", "正则", "Pattern", "正規表現", "Patrón"],
  "hw.rename": ["變數改名", "变量改名", "Rename variable", "変数の名前変更", "Renombrar variable"],
  "hw.unitset": ["單位後綴", "单位后缀", "Unit suffix", "単位サフィックス", "Sufijo de unidad"],
  "hw.manage": ["變數管理", "变量管理", "Variable management", "変数管理", "Gestión de variables"],
  "hw.clearhint": ["留空即清除該項", "留空即清除该项", "Leave empty to clear", "空にすると削除", "Vacío para borrar"],

  // ---- API Server ----
  "api.enabled": ["啟用對外接口", "启用对外接口", "Enable API", "API を有効化", "Activar API"],
  "api.token": ["存取令牌", "访问令牌", "Access token", "アクセストークン", "Token de acceso"],
  "api.tokenhint": ["留空＝不校驗（僅本機回環可達）", "留空＝不校验（仅本机回环可达）", "Empty = no check (loopback only)", "空＝検証なし（ループバックのみ）", "Vacío = sin verificación (solo local)"],
  "api.endpoint": ["端點", "端点", "Endpoint", "エンドポイント", "Punto final"],
  "api.copy": ["複製", "复制", "Copy", "コピー", "Copiar"],
  "api.copied": ["已複製到剪貼板", "已复制到剪贴板", "Copied to clipboard", "クリップボードにコピー", "Copiado al portapapeles"],
  "api.push": ["定時回傳系統資訊", "定时回传系统信息", "Push system info", "システム情報を定期送信", "Enviar info del sistema"],
  "api.interval": ["回傳間隔 (ms)", "回传间隔 (ms)", "Push interval (ms)", "送信間隔 (ms)", "Intervalo (ms)"],
  "api.vars": ["回傳變數白名單", "回传变量白名单", "Variable whitelist", "変数ホワイトリスト", "Lista de variables"],
  "api.varsall": ["未勾選任何變數＝回傳全部", "未勾选任何变量＝回传全部", "None selected = send all", "未選択＝全て送信", "Sin selección = enviar todo"],
  "api.selectall": ["全選（目前篩選）", "全选（当前筛选）", "Select all (filtered)", "全選択（フィルター）", "Seleccionar todo"],
  "api.throttle": ["WebHook 心跳節流 (ms)", "WebHook 心率节流 (ms)", "WebHook throttle (ms)", "WebHook スロットル (ms)", "Límite WebHook (ms)"],
  "api.throttlehint": ["0＝不節流", "0＝不节流", "0 = no throttle", "0＝制限なし", "0 = sin límite"],
  "api.lastpush": ["最近回傳", "最近回传", "Last push", "最終送信", "Último envío"],
  "api.ws": ["WebSocket 下行指令", "WebSocket 下行命令", "WebSocket commands", "WebSocket コマンド", "Comandos WebSocket"],
  "api.wshint": ["傳送 {\"id\":1,\"cmd\":\"status\"}，回應為 type=response；推播為 type=事件名。", "发送 {\"id\":1,\"cmd\":\"status\"}，响应为 type=response；推送为 type=事件名。", "Send {\"id\":1,\"cmd\":\"status\"}; replies use type=response, pushes use type=<event>.", "{\"id\":1,\"cmd\":\"status\"} を送信。応答は type=response、プッシュは type=<イベント>。", "Envía {\"id\":1,\"cmd\":\"status\"}; respuesta type=response, envíos type=<evento>."],
  "api.webhook": ["WebHook 佔位符", "WebHook 占位符", "WebHook placeholders", "WebHook プレースホルダ", "Marcadores WebHook"],
  "api.webhookhint": ["URL / Headers / Body 均支援 {bpm}、{event} 與全部系統資訊變數。", "URL / Headers / Body 均支持 {bpm}、{event} 与全部系统信息变量。", "URL / headers / body support {bpm}, {event} and all system variables.", "URL / ヘッダー / 本文で {bpm}、{event} と全システム変数が使えます。", "URL / cabeceras / cuerpo admiten {bpm}, {event} y todas las variables."],
  "api.warn": ["安全提示：目前僅綁定 127.0.0.1，令牌為空時任何本機程式都可存取。對外開放前務必設定令牌。", "安全提示：当前仅绑定 127.0.0.1，令牌为空时任何本机程序都可访问。对外开放前务必设置令牌。", "Security: bound to 127.0.0.1 only; with an empty token any local process can call it. Set a token before exposing it.", "セキュリティ：127.0.0.1 のみにバインド。トークンが空だとローカルの全プロセスが利用可能。公開前に必ず設定してください。", "Seguridad: solo enlazado a 127.0.0.1; con token vacío cualquier proceso local puede llamar. Configura un token antes de exponerlo."],

  // ---- Console ----
  "console.hint": ["輸入 help 或 ? 查看可用指令", "输入 help 或 ? 查看可用命令", "Type help or ? for commands", "help または ? でコマンド一覧", "Escribe help o ? para ver comandos"],
  "console.ready": ["主控台就緒。", "控制台就绪。", "Console ready.", "コンソール準備完了。", "Consola lista."],
  "console.failed": ["（指令失敗／未連線引擎）", "（命令失败/未连接引擎）", "(command failed / engine not connected)", "（コマンド失敗／エンジン未接続）", "(comando fallido / motor no conectado)"],
  "console.history": ["↑↓ 瀏覽歷史", "↑↓ 浏览历史", "↑↓ history", "↑↓ 履歴", "↑↓ historial"],
  "console.keys": ["Tab 補全 · Ctrl+L 清屏", "Tab 补全 · Ctrl+L 清屏", "Tab complete · Ctrl+L clear", "Tab 補完 · Ctrl+L クリア", "Tab completar · Ctrl+L limpiar"],

  // ---- Monitor (Phase 10) ----
  "mon.range": ["統計區間", "统计区间", "Range", "期間", "Rango"],
  "mon.buckets": ["分桶數", "分桶数", "Buckets", "分割数", "Grupos"],
  "mon.r1h": ["最近 1 小時", "最近 1 小时", "Last 1h", "直近 1 時間", "Última 1 h"],
  "mon.r6h": ["最近 6 小時", "最近 6 小时", "Last 6h", "直近 6 時間", "Últimas 6 h"],
  "mon.r24h": ["最近 24 小時", "最近 24 小时", "Last 24h", "直近 24 時間", "Últimas 24 h"],
  "mon.r3d": ["最近 3 天", "最近 3 天", "Last 3d", "直近 3 日", "Últimos 3 d"],
  "mon.r7d": ["最近 7 天", "最近 7 天", "Last 7d", "直近 7 日", "Últimos 7 d"],
  "mon.r30d": ["最近 30 天", "最近 30 天", "Last 30d", "直近 30 日", "Últimos 30 d"],
  "mon.rall": ["全部", "全部", "All time", "全期間", "Todo"],
  "mon.samples": ["樣本數", "样本数", "Samples", "サンプル数", "Muestras"],
  "mon.min": ["最低", "最低", "Min", "最低", "Mín"],
  "mon.max": ["最高", "最高", "Max", "最高", "Máx"],
  "mon.median": ["中位數", "中位数", "Median", "中央値", "Mediana"],
  "mon.sd": ["標準差", "标准差", "Std dev", "標準偏差", "Desv. típica"],
  "mon.trend": ["每小時趨勢", "每小时趋势", "Hourly trend", "時間別トレンド", "Tendencia por hora"],
  "mon.histogram": ["心跳分佈直方圖", "心率分布直方图", "BPM histogram", "心拍ヒストグラム", "Histograma de BPM"],
  "mon.healthdist": ["健康狀態時長", "健康状态时长", "Health duration", "健康状態の時間", "Duración por estado"],
  "mon.devicedist": ["裝置分佈", "设备分布", "By device", "デバイス別", "Por dispositivo"],
  "mon.osctop": ["OSC 位址 Top20", "OSC 地址 Top20", "Top 20 OSC addresses", "OSC アドレス Top20", "Top 20 direcciones OSC"],
  "mon.last": ["最後記錄", "最后记录", "Last seen", "最終記録", "Último"],
  "mon.loading": ["讀取統計中...", "读取统计中...", "Loading statistics...", "統計を読み込み中...", "Cargando estadísticas..."],
  "mon.nodata": ["此區間沒有記錄（需先在 OSC 頁開啟「記錄」）。", "此区间没有记录（需先在 OSC 页开启「记录」）。", "No records in this range (enable Recording on the OSC tab first).", "この期間に記録がありません（OSC タブで「記録」を有効化してください）。", "Sin registros en este rango (activa la grabación en la pestaña OSC)."],
  "mon.exportreport": ["匯出報表", "导出报表", "Export report", "レポートを書き出す", "Exportar informe"],
  "mon.exported": ["報表已匯出", "报表已导出", "Report exported", "レポートを書き出しました", "Informe exportado"],
  "mon.exportfail": ["報表匯出失敗", "报表导出失败", "Report export failed", "レポートの書き出しに失敗", "Fallo al exportar informe"],

  // ---- About: project, GitHub statistics, version, runtime, and credits ----
  // Five About cards (#14): Project, Release Information, Runtime Environment, Credits, and Latest Release.
  "about.project": ["專案", "项目", "The Project", "プロジェクト", "El Proyecto"],
  "about.relinfo": ["發佈資訊", "发布信息", "Release Informations", "リリース情報", "Información de la versión"],
  "about.latest": ["最新發佈", "最新发布", "Latest Release", "最新リリース", "Última versión"],
  "about.release": ["版本發布", "版本发布", "Release", "リリース", "Versión"],
  "about.channel": ["發布通道", "发布通道", "Channel", "チャネル", "Canal"],
  "about.published": ["發布日期", "发布日期", "Published", "公開日", "Publicado"],
  "about.changelog": ["更新內容", "更新内容", "Changelog", "変更履歴", "Cambios"],
  "about.links": ["連結", "链接", "Links", "リンク", "Enlaces"],
  "about.repo": ["GitHub 倉庫", "GitHub 仓库", "GitHub repository", "GitHub リポジトリ", "Repositorio GitHub"],
  "about.issues": ["問題回報", "问题反馈", "Issues", "問題報告", "Incidencias"],
  "about.releases": ["下載頁", "下载页", "Releases", "リリース一覧", "Descargas"],
  "about.license": ["授權", "许可", "License", "ライセンス", "Licencia"],
  "about.licensefoot": ["本項目以 MIT 授權條款開源，詳見", "本项目以 MIT 许可证开源，详见", "This project is open source under the MIT License — see", "本プロジェクトは MIT ライセンスで公開されています。詳細は", "Este proyecto es de código abierto bajo la licencia MIT; consulta"],
  "about.buildtime": ["構建時間", "构建时间", "Build time", "ビルド日時", "Fecha de compilación"],
  "about.credits": ["致謝", "致谢", "Credits", "クレジット", "Créditos"],
  "about.runtime": ["運行環境", "运行环境", "Runtime", "実行環境", "Entorno"],
  "about.author": ["作者", "作者", "Author", "作者", "Autor"],
  "about.stars": ["星標", "星标", "Stars", "スター", "Estrellas"],
  "about.forks": ["複刻", "复刻", "Forks", "フォーク", "Bifurcaciones"],
  "about.openissues": ["未解決問題", "未解决问题", "Open issues", "未解決 Issue", "Incidencias abiertas"],
  "about.ghhint": ["GitHub 資料來自後端同源快照；可手動刷新，離線時保留快取。", "GitHub 数据来自后端同源快照；可手动刷新，离线时保留缓存。", "GitHub data comes from the same-origin backend snapshot; refresh manually, with cached data retained offline.", "GitHub データは同一オリジンのバックエンドスナップショットから取得し、手動更新できます。オフライン時はキャッシュを保持します。", "Los datos de GitHub proceden de la instantánea del backend del mismo origen; pueden actualizarse manualmente y se conserva la caché sin conexión."],
  "about.notpublished": ["尚未發布到 GitHub", "尚未发布到 GitHub", "Not published on GitHub yet", "まだ GitHub に公開されていません", "Aún no publicado en GitHub"],
  "about.intro": ["HeartRateMonitor 專案、版本與更新資訊", "HeartRateMonitor 项目、版本与更新信息", "HeartRateMonitor project, release, and update information", "HeartRateMonitor のプロジェクト、リリース、更新情報", "Información del proyecto, la versión y las actualizaciones de HeartRateMonitor"],
  "about.updatecenter": ["更新中心", "更新中心", "Update center", "アップデートセンター", "Centro de actualizaciones"],
  "about.refresh": ["刷新", "刷新", "Refresh", "更新", "Actualizar"],
  "about.refreshing": ["刷新中…", "刷新中…", "Refreshing…", "更新中…", "Actualizando…"],
  "about.refreshfail": ["刷新失敗", "刷新失败", "Refresh failed", "更新に失敗しました", "Error al actualizar"],
  "about.status": ["更新狀態", "更新状态", "Update status", "更新状態", "Estado de actualización"],
  "about.available": ["有新版本", "有新版本", "Update available", "新しいバージョンがあります", "Actualización disponible"],
  "about.current": ["已是最新版本", "已是最新版本", "Up to date", "最新です", "Actualizado"],
  "about.skipped": ["已跳過此版本", "已跳过此版本", "Release skipped", "このバージョンはスキップ済み", "Versión omitida"],
  "about.unknown": ["等待版本資料", "等待版本数据", "Waiting for release data", "リリース情報を待機中", "Esperando datos de la versión"],
  "about.cache": ["快取", "缓存", "Cache", "キャッシュ", "Caché"],
  "about.cachedat": ["快取時間：{time}", "缓存时间：{time}", "Cached at {time}", "キャッシュ日時：{time}", "En caché a las {time}"],
  "about.stale": ["正在使用過期快取", "正在使用过期缓存", "Using stale cache", "古いキャッシュを使用中", "Usando caché obsoleta"],
  "about.waiting": ["等待後端快照", "等待后端快照", "Waiting for backend snapshot", "バックエンドのスナップショットを待機中", "Esperando la instantánea del backend"],
  "about.error": ["錯誤", "错误", "Error", "エラー", "Error"],
  "about.commit": ["最新提交", "最新提交", "Latest commit", "最新コミット", "Último commit"],
  "about.releasename": ["發佈名稱", "发布名称", "Release name", "リリース名", "Nombre de la versión"],
  "about.note": ["構建備註", "构建备注", "Build note", "ビルド注記", "Nota de compilación"],
  "about.target": ["構建目標", "构建目标", "Build target", "ビルドターゲット", "Destino de compilación"],
  "about.components": ["組件版本", "组件版本", "Component versions", "コンポーネントバージョン", "Versiones de componentes"],
  "about.consistent": ["版本一致", "版本一致", "Versions consistent", "バージョン一致", "Versiones coherentes"],
  "about.inconsistent": ["版本不一致", "版本不一致", "Version mismatch", "バージョン不一致", "Versiones no coincidentes"],
  "about.unchecked": ["未檢查", "未检查", "Not checked", "未確認", "Sin comprobar"],
  "about.norelease": ["尚無 GitHub 發佈", "尚无 GitHub 发布", "No GitHub release yet", "GitHub リリースはまだありません", "Aún no hay una versión en GitHub"],
  "tab.toolkit": ["工具箱", "工具箱", "Toolkit", "ツールキット", "Herramientas"],
  "toolkit.desc": ["本機 VRChat 設定、相簿、日誌、快取、遊戲與程序工具", "本机 VRChat 配置、图库、日志、缓存、游戏与进程工具", "Local VRChat config, photo, log, cache, game and process tools", "ローカル VRChat 設定・写真・ログ・キャッシュ・ゲーム・プロセス支援", "Herramientas locales de VRChat: configuración, fotos, registros, caché, juego y procesos"],
  "toolkit.paths": ["路徑狀態", "路径状态", "Path status", "パス状態", "Estado de rutas"],
  "toolkit.config": ["設定編輯器", "配置编辑器", "Config editor", "設定エディター", "Editor de configuración"],
  "toolkit.logs": ["日誌瀏覽器", "日志浏览器", "Log browser", "ログブラウザー", "Navegador de registros"],
  "toolkit.cache": ["快取管理", "缓存管理", "Cache manager", "キャッシュ管理", "Gestor de caché"],
  "toolkit.photos": ["相片圖庫", "图片图库", "Photo gallery", "フォトギャラリー", "Galería de fotos"],
  "toolkit.game": ["遊戲分析", "游戏分析", "Game stats", "ゲーム分析", "Estadísticas de juego"],
  "toolkit.process": ["程序分析", "进程分析", "Process", "プロセス分析", "Proceso"],
  "toolkit.configdesc": ["表格化編輯 VRChat config.json，嚴格 JSON 保存。", "表格化编辑 VRChat config.json，严格 JSON 保存。", "Table-edit VRChat config.json with strict JSON saving.", "VRChat config.json をテーブル編集、厳密な JSON で保存。", "Edita config.json de VRChat en tabla con JSON estricto."],
  "toolkit.logsdesc": ["瀏覽 output_log，Join/Leave/Exception 行高亮。", "浏览 output_log，Join/Leave/Exception 行高亮。", "Browse output_log with Join/Leave/Exception highlights.", "output_log を閲覧、Join/Leave/例外行を強調表示。", "Navega output_log con resaltado Join/Leave/Excepción."],
  "toolkit.cachedesc": ["查看快取佔用分析，VRChat 執行時停用清理。", "查看缓存占用分析，VRChat 运行时停用清理。", "Cache usage analysis; cleaning is disabled while VRChat runs.", "キャッシュ使用量を確認。VRChat 実行中は消去不可。", "Análisis de caché; limpieza bloqueada si VRChat corre."],
  "toolkit.photosdesc": ["手動建立相片索引並以關鍵字搜尋。", "手动建立图片索引并以关键字搜索。", "Manually index photos and search by keywords.", "写真を手動インデックス化しキーワード検索。", "Indexa fotos manualmente y busca por palabras clave."],
  "toolkit.gamedesc": ["按天檢視遊戲時長與心率統計。", "按天查看游戏时长与心率统计。", "Daily playtime and heart-rate statistics.", "日別のプレイ時間と心拍統計。", "Estadísticas diarias de juego y ritmo cardíaco."],
  "toolkit.processdesc": ["VRChat CPU/RAM 即時數值與歷史曲線。", "VRChat CPU/RAM 实时数值与历史曲线。", "Live VRChat CPU/RAM readings with history curves.", "VRChat の CPU/RAM リアルタイム値と履歴グラフ。", "CPU/RAM de VRChat en vivo con curvas históricas."],
  "toolkit.field": ["欄位", "字段", "Field", "フィールド", "Campo"],
  "toolkit.type": ["類型", "类型", "Type", "型", "Tipo"],
  "toolkit.jsonhint": ["嚴格 JSON：數字/布林欄位按類型寫入，路徑欄位支援環境變數。", "严格 JSON：数字/布尔字段按类型写入，路径字段支持环境变量。", "Strict JSON: numeric/boolean fields keep their type; path fields support environment variables.", "厳密な JSON：数値・真偽値は型どおりに保存、パス項目は環境変数をサポート。", "JSON estricto: los campos numéricos/booleanos conservan su tipo; las rutas admiten variables de entorno."],
  "toolkit.jsonerr": ["欄位類型錯誤，請檢查數字/布林輸入。", "字段类型错误，请检查数字/布尔输入。", "Field type error; check numeric/boolean inputs.", "フィールドの型エラー。数値・真偽値を確認してください。", "Error de tipo en un campo; revisa los valores numéricos/booleanos."],
  "toolkit.splitdate": ["相片按日期分資料夾", "图片按日期分文件夹", "Photos split by date", "写真を日付別フォルダに保存", "Fotos separadas por fecha"],
  "toolkit.override": ["已由 config 覆寫", "已由 config 覆盖", "Overridden by config", "config で上書き", "Sobrescrito por config"],
  "toolkit.index": ["手動索引", "手动索引", "Manual index", "手動インデックス", "Índice manual"],
  "toolkit.concurrency": ["並行數", "并发数", "Concurrency", "並列数", "Concurrencia"],
  "toolkit.start": ["開始索引", "开始索引", "Start indexing", "インデックス開始", "Iniciar indexación"],
  "toolkit.scanning": ["索引中", "索引中", "Indexing…", "インデックス中…", "Indexando…"],
  "toolkit.scandone": ["索引完成", "索引完成", "Indexing finished", "インデックス完了", "Indexación terminada"],
  "toolkit.progress": ["進度", "进度", "Progress", "進捗", "Progreso"],
  "toolkit.gallery": ["圖庫", "图库", "Gallery", "ギャラリー", "Galería"],
  "toolkit.searchhint": ["關鍵字或 author=/include=/date=（AND）", "关键词或 author=/include=/date=（AND）", "Keywords or author=/include=/date= (AND)", "キーワードまたは author=/include=/date=（AND）", "Palabras o author=/include=/date= (AND)"],
  "toolkit.file": ["檔案", "文件", "File", "ファイル", "Archivo"],
  "toolkit.author": ["作者", "作者", "Author", "作者", "Autor"],
  "toolkit.world": ["世界", "世界", "World", "ワールド", "Mundo"],
  "toolkit.date": ["日期", "日期", "Date", "日付", "Fecha"],
  "toolkit.size": ["大小", "大小", "Size", "サイズ", "Tamaño"],
  "toolkit.copyid": ["複製 ID", "复制 ID", "Copy ID", "ID をコピー", "Copiar ID"],
  "toolkit.openvr": ["開啟 VRChat 頁面", "打开 VRChat 页面", "Open on vrchat.com", "vrchat.com で開く", "Abrir en vrchat.com"],
  "toolkit.copied": ["已複製", "已复制", "Copied", "コピーしました", "Copiado"],
  "toolkit.picklog": ["選擇日誌檔", "选择日志文件", "Choose a log file", "ログファイルを選択", "Elegir un registro"],
  "toolkit.filterhint": ["本機過濾行", "本地过滤行", "Filter lines locally", "行をローカル絞り込み", "Filtrar líneas localmente"],
  "toolkit.join": ["加入", "加入", "Join", "参加", "Unirse"],
  "toolkit.leave": ["離開", "离开", "Leave", "退出", "Salir"],
  "toolkit.exception": ["例外", "异常", "Exception", "例外", "Excepción"],
  "toolkit.lines": ["行", "行", "lines", "行", "líneas"],
  "toolkit.loglocal": ["VRChat output log 只限本機讀取。", "VRChat output log 仅限本机读取。", "VRChat output logs are loopback-only.", "VRChat output log はローカル限定です。", "Los registros de VRChat solo están disponibles localmente."],
  "toolkit.vrrunning": ["VRChat 執行中，禁止寫入。", "VRChat 正在运行，禁止写入。", "VRChat is running; writes are blocked.", "VRChat 実行中のため書き込み不可。", "VRChat está en ejecución; escritura bloqueada."],
  "toolkit.files": ["個檔案", "个文件", "files", "ファイル", "archivos"],
  "toolkit.analyze": ["佔用分析", "占用分析", "Usage analysis", "使用量分析", "Análisis de uso"],
  "toolkit.clear": ["清除快取", "清理缓存", "Clear cache", "キャッシュ消去", "Limpiar caché"],
  "toolkit.dryrun": ["預覽將清理內容", "预览将清理内容", "Preview what will be cleaned", "消去対象のプレビュー", "Vista previa de la limpieza"],
  "toolkit.willclean": ["將清理", "将清理", "Would clean", "消去対象", "Se limpiaría"],
  "toolkit.cleanhint": ["將刪除快取目錄內的全部內容，VRChat 必須已關閉。", "将删除缓存目录内的全部内容，VRChat 必须已关闭。", "Deletes everything inside the cache directory; VRChat must be closed.", "キャッシュ内の全データを削除します。VRChat は終了している必要があります。", "Elimina todo el contenido de la caché; VRChat debe estar cerrado."],
  "toolkit.cleanconfirm": ["確認清理", "确认清理", "Confirm clean", "消去を確定", "Confirmar limpieza"],
  "toolkit.cleanfail": ["無法預覽或清理快取。", "无法预览或清理缓存。", "Cannot preview or clean the cache.", "キャッシュの確認・消去に失敗しました。", "No se puede previsualizar ni limpiar la caché."],
  "toolkit.cleared": ["快取已清除", "缓存已清理", "Cache cleared", "キャッシュ消去済み", "Caché limpiada"],
  "toolkit.days": ["天數", "天数", "Days", "日数", "Días"],
  "toolkit.d7": ["7 天", "7 天", "7 days", "7 日", "7 días"],
  "toolkit.d30": ["30 天", "30 天", "30 days", "30 日", "30 días"],
  "toolkit.d90": ["90 天", "90 天", "90 days", "90 日", "90 días"],
  "toolkit.hours": ["遊戲時長（小時）", "游戏时长（小时）", "Playtime (hours)", "プレイ時間（時間）", "Tiempo de juego (horas)"],
  "toolkit.avgbpm": ["平均心率", "平均心率", "Average HR", "平均心拍", "FC media"],
  "toolkit.maxbpm": ["峰值心率", "峰值心率", "Peak HR", "最大心拍", "FC máxima"],
  "toolkit.total": ["總計", "总计", "Total", "合計", "Total"],
  "toolkit.nodata": ["暫無資料", "暂无数据", "No data yet", "データなし", "Sin datos"],
  "toolkit.cpu": ["CPU", "CPU", "CPU", "CPU", "CPU"],
  "toolkit.ram": ["記憶體", "内存", "RAM", "メモリ", "RAM"],
  "toolkit.uptime": ["執行時間", "运行时间", "Uptime", "稼働時間", "Tiempo activo"],
  "toolkit.pid": ["PID", "PID", "PID", "PID", "PID"],
  "toolkit.vrnotrunning": ["VRChat 未執行", "VRChat 未运行", "VRChat is not running", "VRChat は未実行です", "VRChat no está en ejecución"],
  "toolkit.cpuhist": ["CPU 歷史", "CPU 历史", "CPU history", "CPU 履歴", "Historial de CPU"],
  "toolkit.ramhist": ["記憶體歷史", "内存历史", "RAM history", "メモリ履歴", "Historial de RAM"],
  "common.search": ["搜尋", "搜索", "Search", "検索", "Buscar"],
  "common.read": ["讀取", "读取", "Read", "読む", "Leer"],
};

/** 表内全部 key（供测试校验生成的 locales/*.json 与本表键集一致）。 */
export const TABLE_KEYS = Object.keys(TABLE);
