using System.Collections.Generic;

namespace HeartRateMonitor.Core;

/// <summary>
/// Engine-side console and CLI message catalog, selected by App.Lang for the ten supported locales.
/// Base rows contain Chinese, English, Japanese, and Spanish. Hong Kong locales use Chinese; Korean, German, and French use the supplemental
/// ExtraKo, ExtraDe, and ExtraFr dictionaries below, falling back to English when a key is absent.
/// Missing keys are returned unchanged to make omissions visible.
/// </summary>
public static class Txt
{
    private static readonly Dictionary<string, string[]> Table = new(StringComparer.Ordinal)
    {
        // ---- General command output ----
        ["err.prefix"] = new[] { "[错误] {0}", "[Error] {0}", "[エラー] {0}", "[Error] {0}" },
        ["cli.usage"] = new[] { "用法: {0}", "Usage: {0}", "使い方: {0}", "Uso: {0}" },
        ["help.title"] = new[] { "可用命令:", "Available commands:", "使用可能なコマンド:", "Comandos disponibles:" },
        ["cmd.unknown"] = new[] { "未知命令: {0}（输入 help 或 ? 查看帮助）", "Unknown command: {0} (type \"help\" or \"?\" for help)", "不明なコマンド: {0}（help または ? を入力してください）", "Comando desconocido: {0} (escribe \"help\" o \"?\" para obtener ayuda)" },
        ["cmd.bpm"] = new[] { "当前心率 {0} bpm（平均 {1}）", "Current HR {0} bpm (avg {1})", "現在の心拍 {0} bpm（平均 {1}）", "FC actual {0} bpm (media {1})" },

        // ---- Status values and Boolean labels ----
        ["st.loaded"] = new[] { "已加载", "Loaded", "読み込み済み", "Cargado" },
        ["st.not_loaded"] = new[] { "未加载", "Not loaded", "未読み込み", "No cargado" },
        ["st.connected"] = new[] { "已连接", "Connected", "接続済み", "Conectado" },
        ["st.not_connected"] = new[] { "未连接", "Not connected", "未接続", "No conectado" },
        ["st.conn_devices"] = new[] { "已连接设备", "Devices connected", "接続済みデバイス", "Dispositivos conectados" },
        ["st.no_conn"] = new[] { "无连接", "No connection", "接続なし", "Sin conexión" },
        ["st.scanning"] = new[] { "进行中", "Scanning", "スキャン中", "Escaneando" },
        ["st.scan_stopped"] = new[] { "已停止", "Stopped", "停止", "Detenido" },
        ["st.on"] = new[] { "开启", "On", "オン", "On" },
        ["st.off"] = new[] { "关闭", "Off", "オフ", "Off" },
        ["sw.on"] = new[] { "开", "On", "オン", "On" },
        ["sw.off"] = new[] { "关", "Off", "オフ", "Off" },
        ["st.running"] = new[] { "运行中", "Running", "実行中", "En ejecución" },
        ["st.not_started"] = new[] { "未启动", "Not started", "未起動", "No iniciado" },
        ["v.enabled"] = new[] { "已启用", "Enabled", "有効", "Habilitado" },
        ["v.disabled"] = new[] { "未启用", "Not enabled", "無効", "No habilitado" },
        ["v.set"] = new[] { "已设置", "Set", "設定済み", "Establecido" },
        ["v.empty_no_check"] = new[] { "空（不校验）", "Empty (no auth)", "空（認証なし）", "Vacío (sin verificación)" },
        ["v.default"] = new[] { "默认", "Default", "デフォルト", "Predeterminado" },

        // ---- about / banner ----
        ["about.start"] = new[] { "启动 {0}   宿主 {1}   引擎 {2}", "Started {0}   Host {1}   Engine {2}", "起動 {0}   ホスト {1}   エンジン {2}", "Iniciado {0}   Host {1}   Motor {2}" },
        ["about.web"] = new[] { "本地界面 http://127.0.0.1:{0}/webui/   {1}", "Local UI: http://127.0.0.1:{0}/webui/   {1}", "ローカル UI: http://127.0.0.1:{0}/webui/   {1}", "Interfaz local: http://127.0.0.1:{0}/webui/   {1}" },
        ["about.remote"] = new[] { "第二前端 {0}   {1}", "Remote UI {0}   {1}", "リモート UI {0}   {1}", "UI remota {0}   {1}" },
        ["about.dir"] = new[] { "目录 {0}", "Dir {0}", "Dir {0}", "Dir {0}" },
        ["cli.banner.engine"] = new[] { "引擎 {0}   目录 {1}", "Engine {0}   Dir {1}", "エンジン {0}   ディレクトリ {1}", "Motor {0}   Directorio {1}" },
        ["cli.banner.hint"] = new[] { "help 查看命令 · web start 开界面 · selftest 自检 · exit 退出", "Type \"help\" for commands · \"web start\" for the UI · \"selftest\" for self-test · \"exit\" to quit", "コマンドは help · UI は web start · 自己診断は selftest · 終了は exit", "\"help\" para comandos · \"web start\" para la interfaz · \"selftest\" para autocomprobación · \"exit\" para salir" },

        // ---- Status and configuration summaries ----
        ["status.engine"] = new[] { "引擎: {0}   模式: {1}   版本: {2}", "Engine: {0}   Mode: {1}   Version: {2}", "エンジン: {0}   モード: {1}   バージョン: {2}", "Motor: {0}   Modo: {1}   Versión: {2}" },
        ["status.osc"] = new[] { "OSC : {0}   推送 {1} / 失败 {2} / 接收 {3}", "OSC : {0}   Sent {1} / Failed {2} / Received {3}", "OSC : {0}   送信 {1} / 失敗 {2} / 受信 {3}", "OSC : {0}   Enviados {1} / Fallos {2} / Recibidos {3}" },
        ["status.ble"] = new[] { "蓝牙: {0}   扫描 {1}   当前心率 {2} bpm", "Bluetooth: {0}   Scanning {1}   Current HR {2} bpm", "Bluetooth: {0}   スキャン {1}   現在の心拍 {2} bpm", "Bluetooth: {0}   Escaneo {1}   FC actual {2} bpm" },
        ["status.health"] = new[] { "健康: {0}   记录: {1}   变量 {2} 项", "Health: {0}   Recording: {1}   {2} variables", "健康: {0}   記録: {1}   変数 {2}", "Salud: {0}   Grabación: {1}   {2} variables" },
        ["cfg.osc"] = new[] { "OSC   : {0}:{1} {2}   间隔 {3}ms   接收 {4}", "OSC   : {0}:{1} {2}   Interval {3}ms   Recv {4}", "OSC   : {0}:{1} {2}   間隔 {3}ms   受信 {4}", "OSC   : {0}:{1} {2}   Intervalo {3}ms   Recibido {4}" },
        ["cfg.hw"] = new[] { "硬件  : 采集 {0}ms   浮点 {1}   小数位 {2}   NTP {3}", "HW     : Poll {0}ms   Float {1}   Decimals {2}   NTP {3}", "HW     : 収集 {0}ms   浮動小数点 {1}   小数桁 {2}   NTP {3}", "HW     : Muestreo {0}ms   Flotante {1}   Decimales {2}   NTP {3}" },
        ["cfg.devices"] = new[] { "设备  : 持续扫描 {0}   节流 {1}ms   自动重连 {2}", "Devices: Continuous scan {0}   Throttle {1}ms   Auto-reconnect {2}", "Devices: 継続スキャン {0}   スロットル {1}ms   自動再接続 {2}", "Devices: Escaneo continuo {0}   Límite {1}ms   Reconexión automática {2}" },
        ["cfg.api"] = new[] { "接口  : API {0}   令牌 {1}   Web 端口 {2}", "API    : API {0}   Token {1}   Web port {2}", "API    : API {0}   トークン {1}   Web ポート {2}", "API    : API {0}   Token {1}   Puerto web {2}" },
        ["cfg.dir"] = new[] { "目录  : {0}", "Dir    : {0}", "Dir    : {0}", "Dir    : {0}" },

        // ---- Devices, scanning, detection, and connection ----
        ["dev.none_hint"] = new[] { "（暂无设备，先执行 scan start）", "(No devices yet — run \"scan start\")", "（デバイスがありません。scan start を実行してください）", "(Sin dispositivos; ejecuta \"scan start\")" },
        ["dev.count"] = new[] { "共 {0} 台（按综合分降序）:", "{0} device(s), best score first:", "全 {0} 台（スコア順）:", "{0} dispositivo(s), mejor puntuación primero:" },
        ["dev.connected_hr"] = new[] { "已连接 {0}bpm", "Connected {0} bpm", "接続済み {0} bpm", "Conectado {0} bpm" },
        ["dev.none"] = new[] { "（暂无设备）", "(No devices)", "（デバイスがありません）", "(Sin dispositivos)" },
        ["dev.score"] = new[] { "分", "score", "スコア", "punt" },
        ["score.total"] = new[] { "合计 {0}", "Total {0}", "合計 {0}", "Total {0}" },
        ["scan.stopped"] = new[] { "已停止扫描", "Scan stopped", "スキャンを停止しました", "Escaneo detenido" },
        ["scan.continuous"] = new[] { "开始持续扫描", "Continuous scanning started", "継続スキャンを開始しました", "Escaneo continuo iniciado" },
        ["scan.sec"] = new[] { "开始扫描（{0} 秒）", "Scanning started ({0} s)", "{0} 秒間スキャンを開始しました", "Escaneo iniciado ({0} s)" },
        ["detect.stop_requested"] = new[] { "已请求停止自动检测", "Auto-detect stop requested", "自動検出の停止を要求しました", "Detención de autodetección solicitada" },
        ["detect.progress"] = new[] { "自动检测进行中: {0}/{1} 当前 {2}", "Auto-detect in progress: {0}/{1} current {2}", "自動検出中: {0}/{1} 現在 {2}", "Autodetección en curso: {0}/{1} actual {2}" },
        ["detect.started"] = new[] { "自动检测已启动（{0} 台候选，进度见日志）", "Auto-detect started ({0} candidate(s); progress in logs)", "自動検出を開始しました（候補 {0} 台、進捗はログ参照）", "Autodetección iniciada ({0} candidato(s); progreso en logs)" },
        ["connect.connecting"] = new[] { "正在连接 {0} ...", "Connecting to {0} ...", "{0} に接続しています ...", "Conectando a {0} ..." },
        ["disconnect.done"] = new[] { "已断开 {0}", "Disconnected {0}", "{0} を切断しました", "Desconectado {0}" },
        ["rename.cleared"] = new[] { "已清除别名: {0}", "Alias cleared: {0}", "エイリアスを解除しました: {0}", "Alias eliminado: {0}" },
        ["rename.done"] = new[] { "已重命名: {0} → {1}", "Renamed: {0} → {1}", "名前を変更しました: {0} → {1}", "Renombrado: {0} → {1}" },
        ["save.remembered"] = new[] { "已记住 {0}", "Remembered {0}", "{0} を記憶しました", "Recordado {0}" },
        ["save.forgotten"] = new[] { "已取消记住 {0}", "No longer remembering {0}", "{0} の記憶を解除しました", "Olvidado {0}" },
        ["block.done"] = new[] { "已屏蔽并断开 {0}", "Blocked and disconnected {0}", "{0} をブロックして切断しました", "Bloqueado y desconectado {0}" },

        // ---- Health, recording, export, and reports ----
        ["health.cal_start"] = new[] { "已开始校准（站立静息 30 秒）", "Calibration started (stand still 30 s)", "キャリブレーションを開始しました（立ったまま 30 秒静止）", "Calibración iniciada (permanece quieto 30 s)" },
        ["health.cal_cancel"] = new[] { "已取消校准", "Calibration cancelled", "キャリブレーションを中止しました", "Calibración cancelada" },
        ["health.state"] = new[] { "健康状态: {0}", "Health status: {0}", "健康状態: {0}", "Estado de salud: {0}" },
        ["record.state"] = new[] { "记录: {0}   心率 {1} 条 / OSC {2} 条", "Recording: {0}   HR {1} entries / OSC {2} entries", "記録: {0}   心拍 {1} 件 / OSC {2} 件", "Grabación: {0}   FC {1} registros / OSC {2} registros" },
        ["export.ok"] = new[] { "已导出: {0}", "Exported: {0}", "エクスポートしました: {0}", "Exportado: {0}" },
        ["export.fail"] = new[] { "导出失败: {0}", "Export failed: {0}", "エクスポートに失敗しました: {0}", "Error al exportar: {0}" },
        ["monitor.exported"] = new[] { "报表已导出: {0}", "Report exported: {0}", "レポートをエクスポートしました: {0}", "Informe exportado: {0}" },
        ["monitor.range"] = new[] { "区间: {0}   心率样本 {1} 条", "Range: {0}   HR samples {1}", "範囲: {0}   心拍サンプル {1}", "Rango: {0}   Muestras de FC {1}" },
        ["mon.hours.all"] = new[] { "全部", "All time", "すべて", "Todo el período" },
        ["mon.hours.recent"] = new[] { "最近 {0} 小时", "Last {0} h", "直近 {0} 時間", "Últimas {0} h" },
        ["monitor.hr_stats"] = new[] { "心率: 最低 {0} / 平均 {1} / 中位 {2} / 最高 {3}   标准差 {4}", "HR: min {0} / avg {1} / median {2} / max {3}   SD {4}", "心拍: 最低 {0} / 平均 {1} / 中央値 {2} / 最高 {3}   標準偏差 {4}", "FC: mín {0} / media {1} / mediana {2} / máx {3}   desv. {4}" },
        ["monitor.period"] = new[] { "区间: {0} ~ {1}", "Period: {0} ~ {1}", "期間: {0} ~ {1}", "Período: {0} ~ {1}" },
        ["monitor.device"] = new[] { "  设备 {0} {1,6} 条   均 {2}   {3}~{4}", "  Device {0} {1,6} entries   avg {2}   {3}~{4}", "  デバイス {0} {1,6} 件   平均 {2}   {3}~{4}", "  Dispositivo {0} {1,6} registros   media {2}   {3}~{4}" },
        ["monitor.health_row"] = new[] { "  状态 {0} {1}%   {2} 分钟   {3} 次", "  Status {0} {1}%   {2} min   {3} times", "  状態 {0} {1}%   {2} 分   {3} 回", "  Estado {0} {1}%   {2} min   {3} veces" },
        ["monitor.osc"] = new[] { "OSC 记录 {0} 条   地址 {1} 个（Top20）", "OSC records {0}   addresses {1} (Top20)", "OSC 記録 {0} 件   アドレス {1} 個（Top20）", "Registros OSC {0}   direcciones {1} (Top20)" },

        // ---- Hardware and variables ----
        ["hw.none"] = new[] { "（无匹配变量）", "(No matching variables)", "（一致する変数がありません）", "(Sin variables coincidentes)" },
        ["info.full_done"] = new[] { "已触发 full 采集（注册表 + wmic + Get-ComputerInfo + systeminfo，后台执行）", "Full sampling triggered (registry + wmic + Get-ComputerInfo + systeminfo, in background)", "full 収集を実行しました（レジストリ + wmic + Get-ComputerInfo + systeminfo、バックグラウンド）", "Muestreo completo iniciado (registro + wmic + Get-ComputerInfo + systeminfo, en segundo plano)" },
        ["info.fast_done"] = new[] { "（fast 采集耗时 {0}ms）", "(fast sampling took {0} ms)", "（fast 収集の所要時間 {0}ms）", "(el muestreo rápido tardó {0} ms)" },
        ["var.cleared"] = new[] { "已清除覆写: {0}", "Override cleared: {0}", "上書きを解除しました: {0}", "Sobrescritura eliminada: {0}" },
        ["var.overridden"] = new[] { "已覆写 {0} = {1}", "Overridden {0} = {1}", "上書きしました {0} = {1}", "Sobrescrito {0} = {1}" },

        // ---- OSC, sending, and logs ----
        ["osc.on_done"] = new[] { "OSC 推送已开启", "OSC push enabled", "OSC 送信をオンにしました", "Envío OSC activado" },
        ["osc.off_done"] = new[] { "OSC 推送已关闭", "OSC push disabled", "OSC 送信をオフにしました", "Envío OSC desactivado" },
        ["osc.state"] = new[] { "OSC 推送: {0}   用法: osc on|off", "OSC push: {0}   Usage: osc on|off", "OSC 送信: {0}   使い方: osc on|off", "Envío OSC: {0}   Uso: osc on|off" },
        ["send.ok"] = new[] { "OK", "OK", "OK", "OK" },
        ["send.fail"] = new[] { "失败", "Failed", "失敗", "Fallo" },
        ["send.result"] = new[] { "发送 {0}   {1}   (阻塞 {2}ms)", "Sent {0}   {1}   (blocked {2} ms)", "送信 {0}   {1}   (ブロック {2}ms)", "Envío {0}   {1}   (bloqueado {2} ms)" },
        ["logs.cleared"] = new[] { "日志缓冲已清空", "Log buffer cleared", "ログバッファをクリアしました", "Búfer de logs limpiado" },
        ["logs.dumped"] = new[] { "已转储: {0}", "Dumped: {0}", "ダンプしました: {0}", "Volcado: {0}" },
        ["logs.exported"] = new[] { "已导出 {0} 行: {1}", "Exported {0} line(s): {1}", "{0} 行をエクスポートしました: {1}", "Exportadas {0} línea(s): {1}" },
        ["logs.none"] = new[] { "（无匹配日志）", "(No matching logs)", "（一致するログはありません）", "(Sin logs coincidentes)" },

        // ---- Rows and other short labels ----
        ["unit.items"] = new[] { "{0} 项", "{0} item(s)", "{0} 件", "{0} elemento(s)" },
        ["cli.unknown_key"] = new[] { "未知键: {0}", "Unknown key: {0}", "不明なキー: {0}", "Clave desconocida: {0}" },
        ["cli.unknown_subcmd"] = new[] { "未知子命令: {0}", "Unknown subcommand: {0}", "不明なサブコマンド: {0}", "Subcomando desconocido: {0}" },
        ["oscfg.saved"] = new[] { "OSC 配置已保存", "OSC config saved", "OSC 設定を保存しました", "Configuración OSC guardada" },
        ["params.cleared"] = new[] { "参数表已清空", "Param table cleared", "パラメータ表をクリアしました", "Tabla de parámetros vaciada" },
        ["params.none"] = new[] { "（暂无收到的 OSC 参数）", "(No OSC parameters received yet)", "（受信した OSC パラメータはまだありません）", "(Aún no hay parámetros OSC recibidos)" },
        ["params.count"] = new[] { "共 {0} 个地址（累计接收 {1} 条）:", "{0} address(es) ({1} received in total):", "全 {0} アドレス（累計受信 {1} 件）:", "{0} dirección(es) ({1} recibidas en total):" },

        // ---- WebHook / Web / API ----
        ["wh.master"] = new[] { "WebHook 总开关: {0}", "WebHook master switch: {0}", "WebHook 全体スイッチ: {0}", "Interruptor general WebHook: {0}" },
        ["wh.idx_range"] = new[] { "序号超出范围（0~{0}）", "Index out of range (0~{0})", "番号が範囲外です（0~{0}）", "Índice fuera de rango (0~{0})" },
        ["wh.triggered"] = new[] { "已触发 #{0}   HTTP {1}", "Triggered #{0}   HTTP {1}", "実行しました #{0}   HTTP {1}", "Disparado #{0}   HTTP {1}" },
        ["wh.trigger_fail"] = new[] { "触发失败: {0}", "Trigger failed: {0}", "実行に失敗しました: {0}", "Fallo al disparar: {0}" },
        ["wh.list_head"] = new[] { "总开关 {0}   共 {1} 条:", "Master switch {0}   {1} item(s):", "全体スイッチ {0}   全 {1} 件:", "Interruptor general {0}   {1} elemento(s):" },
        ["wh.item_on"] = new[] { "[开]", "[On]", "[オン]", "[On]" },
        ["wh.item_off"] = new[] { "[关]", "[Off]", "[オフ]", "[Off]" },
        ["web.err_no_host"] = new[] { "[错误] Web 宿主不可用", "[Error] Web host unavailable", "[エラー] Web ホストを利用できません", "[Error] Host web no disponible" },
        ["web.started"] = new[] { "Web 服务已启动: {0}", "Web server started: {0}", "Web サーバーを起動しました: {0}", "Servidor web iniciado: {0}" },
        ["web.start_failed"] = new[] { "启动失败（端口可能被占用，见日志）", "Start failed (port may be in use; see logs)", "起動に失敗しました（ポートが使用中かも。ログ参照）", "Error al iniciar (el puerto puede estar ocupado; ver logs)" },
        ["web.started_ui"] = new[] { "Web 服务已启动并打开界面: {0}", "Web server started and UI opened: {0}", "Web サーバーを起動し UI を開きました: {0}", "Servidor web iniciado e interfaz abierta: {0}" },
        ["web.stopped"] = new[] { "Web 服务已停止", "Web server stopped", "Web サーバーを停止しました", "Servidor web detenido" },
        ["web.state"] = new[] { "Web 服务: {0}   {1}", "Web server: {0}   {1}", "Web サーバー: {0}   {1}", "Servidor web: {0}   {1}" },
        ["web.off"] = new[] { "（Web 服务未启动）", "(Web server not running)", "（Web サーバー未起動）", "(Servidor web no iniciado)" },

        // ---- Remote frontend ----
        ["remote.state"] = new[] { "远程访问: {0}", "Remote access: {0}", "リモートアクセス: {0}", "Acceso remoto: {0}" },
        ["remote.off"] = new[] { "已停用", "Disabled", "無効", "Desactivado" },
        ["remote.wan"] = new[] { "WAN(公网)访问: {0}", "WAN (public) access: {0}", "WAN（パブリック）アクセス: {0}", "Acceso WAN (público): {0}" },
        ["remote.wan_blocked"] = new[] { "WAN 开启被拒绝：管理员密码未初始化/为默认/强度不足（≥8位且含字母和数字）", "WAN refused: admin password uninitialized, default, or too weak (>=8 chars with letters and digits)", "WAN は拒否されました：管理者パスワードが未初期化・デフォルト・脆弱です（8文字以上で英数字を含む）", "WAN rechazado: contraseña de admin sin inicializar, predeterminada o débil (≥8 con letras y dígitos)" },
        ["remote.idle"] = new[] { "会话空闲过期: {0} 分钟", "Session idle timeout: {0} min", "セッションアイドル期限: {0} 分", "Caducidad por inactividad: {0} min" },
        ["remote.users_none"] = new[] { "（Web 服务未启动，用户库未加载）", "(Web server not running; user store not loaded)", "（Web サーバー未起動のためユーザー未読込）", "(Servidor web no iniciado; usuarios no cargados)" },
        ["remote.users_count"] = new[] { "共 {0} 个用户:", "{0} user(s):", "全 {0} ユーザー:", "{0} usuario(s):" },
        ["remote.tab_label"] = new[] { "板块", "tabs", "タブ", "pestañas" },
        ["remote.sessions_none"] = new[] { "（无在线会话）", "(No active sessions)", "（アクティブなセッションなし）", "(Sin sesiones activas)" },
        ["remote.sessions_count"] = new[] { "共 {0} 个在线会话:", "{0} active session(s):", "全 {0} のアクティブセッション:", "{0} sesión(es) activa(s):" },
        ["remote.last_active"] = new[] { "最后活动", "last active", "最終アクティブ", "última actividad" },
        ["remote.session_not_found"] = new[] { "未找到会话: {0}", "Session not found: {0}", "セッションが見つかりません: {0}", "Sesión no encontrada: {0}" },
        ["remote.session_killed"] = new[] { "已销毁会话 {0}（{1}）", "Session destroyed {0} ({1})", "セッションを破棄しました {0}（{1}）", "Sesión destruida {0} ({1})" },
        ["remote.kill_fail"] = new[] { "销毁失败", "Failed to destroy", "破棄に失敗しました", "No se pudo destruir" },
        ["remote.cred_error"] = new[] { "[错误] 出于凭据安全，新增用户与改密只能在界面里操作（避免明文密码进入命令历史）", "[Error] For credential security, adding users and changing passwords is only possible in the UI (to keep plaintext passwords out of the command history)", "[エラー] 資格情報の安全のため、ユーザー追加とパスワード変更は UI でのみ行えます（平文パスワードがコマンド履歴に残らないように）", "[Error] Por seguridad de credenciales, añadir usuarios y cambiar contraseñas solo es posible en la interfaz (para evitar contraseñas en el historial de comandos)" },
        ["remote.user_deleted"] = new[] { "已删除用户 {0}", "Deleted user {0}", "ユーザーを削除しました {0}", "Usuario eliminado {0}" },
        ["remote.user_del_fail"] = new[] { "删除失败（用户不存在或这是最后一个 admin）", "Delete failed (user missing or this is the last admin)", "削除に失敗しました（ユーザーが存在しないか、最後の admin）", "No se pudo eliminar (usuario inexistente o es el último admin)" },
        ["remote.role_changed"] = new[] { "{0} 角色改为 {1}", "{0} role set to {1}", "{0} のロールを {1} に変更しました", "Rol de {0} cambiado a {1}" },
        ["remote.change_fail"] = new[] { "修改失败", "Change failed", "変更に失敗しました", "No se pudo cambiar" },
        ["remote.tabs_set"] = new[] { "{0} 板块白名单: {1}", "{0} tab whitelist: {1}", "{0} のタブ許可リスト: {1}", "Lista blanca de pestañas de {0}: {1}" },

        // ---- UI, floating windows, and log settings ----
        ["ui.brand_default"] = new[] { "（默认）", "(default)", "（デフォルト）", "(predeterminado)" },
        ["float.err_no_gui"] = new[] { "[错误] 悬浮窗需要 GUI 宿主（在 hrmcli 里不可用，请先 web ui 打开界面）", "[Error] Floating windows need a GUI host (unavailable in hrmcli — open the UI with \"web ui\" first)", "[エラー] フローティングウィンドウには GUI ホストが必要です（hrmcli では不可。先に web ui で UI を開いてください）", "[Error] Las ventanas flotantes requieren un host GUI (no disponible en hrmcli; abre la interfaz con \"web ui\" primero)" },
        ["float.opened"] = new[] { "已打开悬浮窗", "Floating window opened", "フローティングウィンドウを開きました", "Ventana flotante abierta" },
        ["float.all_closed"] = new[] { "已关闭全部悬浮窗", "All floating windows closed", "フローティングウィンドウをすべて閉じました", "Ventanas flotantes cerradas" },
        ["float.locked"] = new[] { "悬浮窗已锁定", "Floating windows locked", "フローティングウィンドウをロックしました", "Ventanas flotantes bloqueadas" },
        ["float.unlocked"] = new[] { "悬浮窗已解锁", "Floating windows unlocked", "フローティングウィンドウのロックを解除しました", "Ventanas flotantes desbloqueadas" },
        ["logcfg.interval"] = new[] { "  interval = {0} 分钟", "  interval = {0} min", "  interval = {0} 分", "  interval = {0} min" },
        ["logcfg.trace"] = new[] { "  trace    = {0}（当前进程 {1}，改动下次启动生效）", "  trace    = {0} (current process {1}; applies after restart)", "  trace    = {0}（現在のプロセス {1}。次回起動時に有効）", "  trace    = {0} (proceso actual {1}; se aplica al reiniciar)" },

        // ---- CLI event labels ----
        ["evt.found"] = new[] { "发现", "Found", "発見", "Encontrado" },
        ["evt.connected"] = new[] { "已连接", "Connected", "接続", "Conectado" },
        ["evt.disconnected"] = new[] { "已断开", "Disconnected", "切断", "Desconectado" },
        ["evt.hr"] = new[] { "心率", "HR", "心拍", "FC" },
        ["evt.ble_error"] = new[] { "[BLE错误] {0}", "[BLE error] {0}", "[BLEエラー] {0}", "[Error BLE] {0}" },

        // ---- Self-test header, overview, and summary ----
        ["selftest.title"] = new[] { "========== Self-Test（模拟真实用户视角）==========", "========== Self-Test (simulating a real user) ==========", "========== セルフテスト（実ユーザー視点のシミュレーション）==========", "========== Autocomprobación (perspectiva de usuario real) ==========" },
        ["selftest.constraint"] = new[] { "约束: 最长的单次阻塞型操作 ≤ {0}ms", "Constraint: longest single blocking operation ≤ {0} ms", "制約: 単一ブロッキング操作の最大時間 ≤ {0}ms", "Restricción: la operación de bloqueo más larga ≤ {0} ms" },
        ["selftest.detail_head"] = new[] { "---- 延迟明细 ----", "---- Latency details ----", "---- 遅延の詳細 ----", "---- Detalles de latencia ----" },
        ["selftest.max_blocking"] = new[] { "最长阻塞型操作: {0}ms  上限: {1}ms  ->  {2}", "Longest blocking op: {0} ms   limit: {1} ms  ->  {2}", "最長ブロッキング操作: {0}ms  上限: {1}ms  ->  {2}", "Operación de bloqueo más larga: {0} ms   límite: {1} ms  ->  {2}" },
        ["selftest.over_limit"] = new[] { "超限!", "Over limit!", "上限超過!", "¡Límite superado!" },
        ["selftest.result"] = new[] { "========== Self-Test 结果: {0} ==========", "========== Self-Test result: {0} ==========", "========== セルフテスト結果: {0} ==========", "========== Resultado del Self-Test: {0} ==========" },

        // ---- Command descriptions; rows contain zh, en, ja, and es ----
        ["dsc.help"] = new[] { "显示本帮助", "Show this help", "このヘルプを表示", "Mostrar esta ayuda" },
        ["dsc.status"] = new[] { "引擎 / OSC / 蓝牙 / 配置概览", "Engine / OSC / Bluetooth / config overview", "エンジン / OSC / Bluetooth / 設定の概要", "Motor / OSC / Bluetooth / resumen de configuración" },
        ["dsc.about"] = new[] { "版本 / 目录 / 端口", "Version / directory / port", "バージョン / ディレクトリ / ポート", "Versión / directorio / puerto" },
        ["dsc.devices"] = new[] { "设备列表（含排序综合分）", "Device list (with ranking score)", "デバイス一覧（スコア順）", "Lista de dispositivos (con puntuación)" },
        ["dsc.score"] = new[] { "排序评分明细（省略 mac = 全部设备）", "Ranking score details (no mac = all devices)", "スコア明細（mac 省略時は全デバイス）", "Detalles de puntuación (sin mac = todos los dispositivos)" },
        ["dsc.scan"] = new[] { "开始 / 停止扫描", "Start / stop scanning", "スキャンの開始 / 停止", "Iniciar / detener escaneo" },
        ["dsc.detect"] = new[] { "自动检测：按综合分依次试连心率设备", "Auto-detect: try heart-rate devices in score order", "自動検出：スコア順に心拍デバイスを試行", "Autodetección: probar dispositivos de FC por puntuación" },
        ["dsc.connect"] = new[] { "连接设备", "Connect to a device", "デバイスに接続", "Conectar dispositivo" },
        ["dsc.disconnect"] = new[] { "断开设备", "Disconnect a device", "デバイスを切断", "Desconectar dispositivo" },
        ["dsc.save"] = new[] { "记住 / 取消记住设备", "Remember / forget a device", "デバイスを記憶 / 解除", "Recordar / olvidar dispositivo" },
        ["dsc.block"] = new[] { "屏蔽设备（同时断开）", "Block a device (and disconnect)", "デバイスをブロック（切断も行う）", "Bloquear dispositivo (y desconectar)" },
        ["dsc.rename"] = new[] { "设备重命名（省略别名 = 清除）", "Rename a device (no alias = clear)", "デバイスの名前変更（エイリアス省略時は解除）", "Renombrar dispositivo (sin alias = limpiar)" },
        ["dsc.devcfg"] = new[] { "设备策略：scan/throttle/reconnect/interval/giveup/autoconnect/autodetect/timeout", "Device policy: scan/throttle/reconnect/interval/giveup/autoconnect/autodetect/timeout", "デバイス設定：scan/throttle/reconnect/interval/giveup/autoconnect/autodetect/timeout", "Política de dispositivo: scan/throttle/reconnect/interval/giveup/autoconnect/autodetect/timeout" },
        ["dsc.bpm"] = new[] { "当前心率与平均值", "Current HR and average", "現在の心拍と平均", "FC actual y promedio" },
        ["dsc.health"] = new[] { "健康状态 / 校准", "Health status / calibration", "健康状態 / キャリブレーション", "Estado de salud / calibración" },
        ["dsc.hcfg"] = new[] { "健康参数：sleep/active/excited/spike/record/resting", "Health params: sleep/active/excited/spike/record/resting", "健康パラメータ：sleep/active/excited/spike/record/resting", "Parámetros de salud: sleep/active/excited/spike/record/resting" },
        ["dsc.record"] = new[] { "SQLite 记录开关", "SQLite recording switch", "SQLite 記録のオン・オフ", "Interruptor de grabación SQLite" },
        ["dsc.export"] = new[] { "导出数据（json/yaml/csv/sqlite）", "Export data (json/yaml/csv/sqlite)", "データをエクスポート（json/yaml/csv/sqlite）", "Exportar datos (json/yaml/csv/sqlite)" },
        ["dsc.monitor"] = new[] { "历史统计报表（默认 24 小时）", "Historical stats report (default 24 h)", "履歴統計レポート（既定 24 時間）", "Informe estadístico histórico (24 h por defecto)" },
        ["dsc.hw"] = new[] { "硬件变量表", "Hardware variable list", "ハードウェア変数一覧", "Tabla de variables de hardware" },
        ["dsc.info"] = new[] { "触发一次硬件采集", "Trigger one hardware sample", "ハードウェア情報を一度収集", "Realizar una muestra de hardware" },
        ["dsc.var"] = new[] { "变量覆写（省略值 = 清除）", "Override a variable (no value = clear)", "変数の上書き（値省略時は解除）", "Sobrescribir variable (sin valor = limpiar)" },
        ["dsc.hwcfg"] = new[] { "硬件采集：interval/float/decimals/round/ntp", "Hardware sampling: interval/float/decimals/round/ntp", "ハードウェア収集：interval/float/decimals/round/ntp", "Muestreo de hardware: interval/float/decimals/round/ntp" },
        ["dsc.sysinfo"] = new[] { "变量模板预览（如 \"{BPM} {CPU_USAGE}%\"）", "Variable template preview (e.g. \"{BPM} {CPU_USAGE}%\")", "変数テンプレートのプレビュー（例 \"{BPM} {CPU_USAGE}%\"）", "Vista previa de plantilla de variables (p. ej. \"{BPM} {CPU_USAGE}%\")" },
        ["dsc.osc"] = new[] { "OSC 推送开关", "OSC push switch", "OSC 送信のオン・オフ", "Interruptor de envío OSC" },
        ["dsc.oscfg"] = new[] { "OSC 配置：ip/port/address/interval/recv/template", "OSC config: ip/port/address/interval/recv/template", "OSC 設定：ip/port/address/interval/recv/template", "Config OSC: ip/port/address/interval/recv/template" },
        ["dsc.params"] = new[] { "OSC 收到的参数表", "Parameters received via OSC", "OSC で受信したパラメータ表", "Parámetros recibidos por OSC" },
        ["dsc.send"] = new[] { "发送一条 OSC 消息", "Send one OSC message", "OSC メッセージを 1 件送信", "Enviar un mensaje OSC" },
        ["dsc.webhook"] = new[] { "WebHook 列表 / 总开关 / 触发一次", "WebHook list / master switch / trigger once", "WebHook 一覧 / 全体スイッチ / 一度だけ実行", "Lista WebHook / interruptor general / disparar una vez" },
        ["dsc.api"] = new[] { "API Server 配置", "API Server config", "API Server 設定", "Configuración del API Server" },
        ["dsc.web"] = new[] { "本地 Web 界面服务（ui = 顺带开窗口）", "Local web UI service (ui = also open the window)", "ローカル Web UI サービス（ui でウィンドウも開く）", "Servicio de interfaz web local (ui = abrir también la ventana)" },
        ["dsc.remote"] = new[] { "第二前端（远程 Web）", "Second frontend (remote web)", "セカンドフロントエンド（リモート Web）", "Segundo frontend (web remota)" },
        ["dsc.autostart"] = new[] { "登录自启（on/off + task,run,startup + silent）", "Login autostart (on/off + task,run,startup + silent)", "ログイン時自動起動（on/off + task,run,startup + silent）", "Inicio automático (on/off + task,run,startup + silent)" },
        ["autostart.applied"] = new[] { "开机自启已更新: {0}", "Login autostart updated: {0}", "自動起動を更新しました: {0}", "Inicio automático actualizado: {0}" },
        ["autostart.badmethods"] = new[] { "无效的注册方式（可用: task,run,startup）", "Invalid method(s) (available: task,run,startup)", "無効な登録方式（利用可能: task,run,startup）", "Métodos no válidos (disponibles: task,run,startup)" },
        ["autostart.silentflag"] = new[] { "静默启动: {0}", "Silent start: {0}", "サイレント起動: {0}", "Inicio silencioso: {0}" },
        ["autostart.reg"] = new[] { "已注册", "registered", "登録済み", "registrado" },
        ["autostart.unreg"] = new[] { "未注册", "not registered", "未登録", "no registrado" },
        ["autostart.staleitem"] = new[] { "（指向其他位置，重新 on 修复）", " (points elsewhere; run on again to repair)", "（別の場所を指すため、on を再実行で修復）", " (apunta a otra ubicación; ejecuta on de nuevo para reparar)" },
        ["comp.mismatch"] = new[] { "组件版本不一致（安装可能损坏）", "Component version mismatch (installation may be broken)", "コンポーネントのバージョン不一致（インストールが破損している可能性）", "Versiones de componentes inconsistentes (la instalación puede estar dañada)" },
        ["comp.line"] = new[] { "{0}: 实际 {1}，清单 {2}", "{0}: actual {1}, manifest {2}", "{0}: 実際 {1}、マニフェスト {2}", "{0}: real {1}, manifiesto {2}" },
        ["comp.missing"] = new[] { "{0}: 文件缺失", "{0}: file missing", "{0}: ファイルがありません", "{0}: archivo ausente" },
        ["comp.continue"] = new[] { "仍然继续？[Y/n] ", "Continue anyway? [Y/n] ", "続行しますか？[Y/n] ", "¿Continuar? [Y/n] " },
        ["comp.exited"] = new[] { "已退出，请重新下载或修复安装。", "Exited; please redownload or repair the installation.", "終了しました。再ダウンロードまたは修復してください。", "Se cerró; vuelve a descargar o repara la instalación." },
        ["gh.project"] = new[] { "项目: {0}", "Project: {0}", "プロジェクト: {0}", "Proyecto: {0}" },
        ["gh.release"] = new[] { "发布: {0}（v{1}）  构建 {2}", "Release: {0} (v{1})  built {2}", "リリース: {0}（v{1}）  ビルド {2}", "Lanzamiento: {0} (v{1})  compilado {2}" },
        ["gh.note"] = new[] { "备注: {0}", "Note: {0}", "备注: {0}", "Nota: {0}" },
        ["gh.target"] = new[] { "平台: {0}", "Target: {0}", "ターゲット: {0}", "Plataforma: {0}" },
        ["gh.github"] = new[] { "GitHub: ★{0}  issues {1}/{2}  commit {3}{4}", "GitHub: stars {0}  issues {1}/{2}  commit {3}{4}", "GitHub: ★{0}  issues {1}/{2}  commit {3}{4}", "GitHub: ★{0}  issues {1}/{2}  commit {3}{4}" },
        ["gh.stale"] = new[] { "（缓存）", " (cached)", "（キャッシュ）", " (en caché)" },
        ["gh.uptodate"] = new[] { "已是最新", "up to date", "最新です", "actualizado" },
        ["gh.skipped"] = new[] { "已跳过提示", "prompt skipped", "通知をスキップ済み", "aviso omitido" },
        ["gh.newer"] = new[] { "有更新 {0}", "update {0} available", "更新 {0} あり", "actualización {0} disponible" },
        ["gh.latest"] = new[] { "最新发布: {0} {1}（{2}）", "Latest release: {0} {1} ({2})", "最新リリース: {0} {1}（{2}）", "Último lanzamiento: {0} {1} ({2})" },
        ["dsc.ui"] = new[] { "界面：lang/mode/palette/corner/density/anim/brand/close", "UI: lang/mode/palette/corner/density/anim/brand/close", "画面設定：lang/mode/palette/corner/density/anim/brand/close", "Interfaz: lang/mode/palette/corner/density/anim/brand/close" },
        ["dsc.float"] = new[] { "悬浮窗（需 GUI 宿主）", "Floating window (requires GUI host)", "フローティングウィンドウ（GUI ホストが必要）", "Ventana flotante (requiere host GUI)" },
        ["dsc.logs"] = new[] { "最近日志 / 清空 / 转储 / 导出", "Recent logs / clear / dump / export", "最近のログ / クリア / ダンプ / エクスポート", "Logs recientes / limpiar / volcar / exportar" },
        ["dsc.logcfg"] = new[] { "日志：autodump/interval/trace", "Logging: autodump/interval/trace", "ログ設定：autodump/interval/trace", "Registro: autodump/interval/trace" },
        ["dsc.config"] = new[] { "当前配置摘要", "Current config summary", "現在の設定概要", "Resumen de configuración actual" },
        ["dsc.selftest"] = new[] { "自检", "Self-test", "セルフテスト", "Autocomprobación" },
        ["dsc.clear"] = new[] { "清屏", "Clear screen", "画面クリア", "Limpiar pantalla" },
        ["dsc.exit"] = new[] { "退出", "Exit", "終了", "Salir" },
        ["dsc.reboot"] = new[] { "重启引擎(快速回连)", "Reboot engine", "エンジンを再起動", "Reiniciar motor" },
        ["reboot.ok"] = new[] { "正在重启后端并回连上次设备 ...", "Restarting engine and reconnecting last device(s) ...", "エンジンを再起動し、前回のデバイスへ接続しています ...", "Reiniciando el motor y reconectando el último dispositivo ..." },
        ["reboot.gui_only"] = new[] { "reboot 仅在界面/后台(GUI)模式下可用", "reboot is only available in GUI/background mode", "reboot は GUI/バックグラウンド モードでのみ利用できます", "reboot solo está disponible en modo GUI/fondo" },
        ["dsc.crash"] = new[] { "崩溃测试", "Crash test", "クラッシュテスト", "Prueba de caída" },

        // ---- Complete localized usage lines with translated prefixes ----
        ["usage.rename"] = new[] { "用法: rename <mac> [别名]（省略别名 = 清除）", "Usage: rename <mac> [alias] (no alias = clear)", "使い方: rename <mac> [エイリアス]（省略時は解除）", "Uso: rename <mac> [alias] (sin alias = limpiar)" },
        ["usage.var"] = new[] { "用法: var <变量名> [值]（省略值 = 清除覆写）", "Usage: var <name> [value] (no value = clear override)", "使い方: var <変数名> [値]（値省略時は上書き解除）", "Uso: var <nombre> [valor] (sin valor = quitar sobrescritura)" },
        ["usage.send"] = new[] { "用法: send <地址> <文本>", "Usage: send <address> <text>", "使い方: send <アドレス> <テキスト>", "Uso: send <dirección> <texto>" },
        ["usage.sysinfo"] = new[] { "用法: sysinfo <模板>（如 sysinfo \"{BPM} bpm / CPU {CPU_USAGE}%\"）", "Usage: sysinfo <template> (e.g. sysinfo \"{BPM} bpm / CPU {CPU_USAGE}%\")", "使い方: sysinfo <テンプレート>（例: sysinfo \"{BPM} bpm / CPU {CPU_USAGE}%\"）", "Uso: sysinfo <plantilla> (p. ej. sysinfo \"{BPM} bpm / CPU {CPU_USAGE}%\")" },
        ["usage.devcfg"] = new[] { "用法: devcfg <scan|throttle|reconnect|interval|giveup|weak|critical|autoconnect|autodetect|timeout> <值>", "Usage: devcfg <scan|throttle|reconnect|interval|giveup|weak|critical|autoconnect|autodetect|timeout> <value>", "使い方: devcfg <scan|throttle|reconnect|interval|giveup|weak|critical|autoconnect|autodetect|timeout> <値>", "Uso: devcfg <scan|throttle|reconnect|interval|giveup|weak|critical|autoconnect|autodetect|timeout> <valor>" },
        ["usage.hcfg"] = new[] { "用法: hcfg <sleep|active|excited|spike|record|resting> <值>", "Usage: hcfg <sleep|active|excited|spike|record|resting> <value>", "使い方: hcfg <sleep|active|excited|spike|record|resting> <値>", "Uso: hcfg <sleep|active|excited|spike|record|resting> <valor>" },
        ["usage.hwcfg"] = new[] { "用法: hwcfg <interval|float|decimals|round|ntp> <值>", "Usage: hwcfg <interval|float|decimals|round|ntp> <value>", "使い方: hwcfg <interval|float|decimals|round|ntp> <値>", "Uso: hwcfg <interval|float|decimals|round|ntp> <valor>" },
        ["usage.oscfg"] = new[] { "用法: oscfg <ip|port|address|interval|recv|template> <值>", "Usage: oscfg <ip|port|address|interval|recv|template> <value>", "使い方: oscfg <ip|port|address|interval|recv|template> <値>", "Uso: oscfg <ip|port|address|interval|recv|template> <valor>" },
        ["usage.api"] = new[] { "用法: api <on|off|token 值|push on|off|interval ms|throttle ms>", "Usage: api <on|off|token value|push on|off|interval ms|throttle ms>", "使い方: api <on|off|token 値|push on|off|interval ms|throttle ms>", "Uso: api <on|off|token valor|push on|off|interval ms|throttle ms>" },
        ["usage.ui"] = new[] { "用法: ui <lang|mode|palette|corner|density|anim|brand|close> <值>", "Usage: ui <lang|mode|palette|corner|density|anim|brand|close> <value>", "使い方: ui <lang|mode|palette|corner|density|anim|brand|close> <値>", "Uso: ui <lang|mode|palette|corner|density|anim|brand|close> <valor>" },
        ["usage.logcfg"] = new[] { "用法: logcfg <autodump|interval|trace> <值>", "Usage: logcfg <autodump|interval|trace> <value>", "使い方: logcfg <autodump|interval|trace> <値>", "Uso: logcfg <autodump|interval|trace> <valor>" },
        ["usage.webhook_test"] = new[] { "用法: webhook test <序号>", "Usage: webhook test <index>", "使い方: webhook test <番号>", "Uso: webhook test <índice>" },
        ["usage.remote_idle"] = new[] { "用法: remote idle <分钟，0=永不过期>", "Usage: remote idle <minutes, 0 = never expire>", "使い方: remote idle <分、0 = 期限なし>", "Uso: remote idle <minutos, 0 = sin caducidad>" },
        ["usage.remote_kick"] = new[] { "用法: remote kick <会话 id 前缀，见 remote sessions>", "Usage: remote kick <session id prefix, see \"remote sessions\">", "使い方: remote kick <セッション ID プレフィックス。remote sessions 参照>", "Uso: remote kick <prefijo de id de sesión; ver \"remote sessions\">" },
        ["usage.remote_deluser"] = new[] { "用法: remote deluser <用户名>", "Usage: remote deluser <username>", "使い方: remote deluser <ユーザー名>", "Uso: remote deluser <nombre de usuario>" },
        ["usage.remote_role"] = new[] { "用法: remote role <用户名> <admin|user>", "Usage: remote role <username> <admin|user>", "使い方: remote role <ユーザー名> <admin|user>", "Uso: remote role <nombre de usuario> <admin|user>" },
        ["usage.remote_tabs"] = new[] { "用法: remote tabs <用户名> [板块,逗号分隔；留空=默认]", "Usage: remote tabs <username> [tabs, comma-separated; empty = default]", "使い方: remote tabs <ユーザー名> [タブ,カンマ区切り；空 = デフォルト]", "Uso: remote tabs <nombre de usuario> [pestañas, separadas por comas; vacío = predeterminado]" },
        ["usage.crash"] = new[] { "用法: crash <exit1|null|kill>", "Usage: crash <exit1|null|kill>", "使い方: crash <exit1|null|kill>", "Uso: crash <exit1|null|kill>" },
        ["crash.started"] = new[] { "已触发崩溃测试: {0}", "Crash test triggered: {0}", "クラッシュテストを実行しました: {0}", "Prueba de caída iniciada: {0}" },

        // ---- exit and --force console behavior----
        ["exit.gui"] = new[] { "界面内退出需带 --force 才会结束整个程序（输入: exit --force）", "In the GUI you need \"exit --force\" to quit the whole app", "GUI 内ではアプリ全体を終了するには \"exit --force\" と入力してください", "Para salir de la aplicación completa usa \"exit --force\"" },
        ["exit.repl"] = new[] { "退出终端（CLI 中 exit 不带参数即可）", "Exits the terminal (plain \"exit\" works in the CLI)", "端末を終了（CLI では exit だけで終了します）", "Salir de la terminal (basta \"exit\" en la CLI)" },
        ["exit.force"] = new[] { "正在强行退出整个程序 ...", "Force quitting the whole app ...", "アプリ全体を強制終了します ...", "Forzando la salida de la aplicación ..." },
    };

    // ---- Supplemental dictionaries for Korean, German, and French; the engine console does not add columns for these languages,
    // so translations are provided per key. T() prefers them and falls back to English (en=1) when missing.
    private static readonly Dictionary<string, string> ExtraKo = new(StringComparer.Ordinal)
    {
        ["err.prefix"] = "[오류] {0}",
        ["cli.usage"] = "사용법: {0}",
        ["help.title"] = "사용 가능한 명령:",
        ["cmd.unknown"] = "알 수 없는 명령: {0}(help 또는 ? 입력)",
        ["cmd.bpm"] = "현재 심박수 {0} bpm(평균 {1})",
        ["st.loaded"] = "불러옴",
        ["st.not_loaded"] = "불러오지 않음",
        ["st.connected"] = "연결됨",
        ["st.not_connected"] = "연결 안 됨",
        ["st.conn_devices"] = "연결된 장치",
        ["st.no_conn"] = "연결 없음",
        ["st.scanning"] = "스캔 중",
        ["st.scan_stopped"] = "중지됨",
        ["st.on"] = "켜짐",
        ["st.off"] = "꺼짐",
        ["sw.on"] = "켜기",
        ["sw.off"] = "끄기",
        ["st.running"] = "실행 중",
        ["st.not_started"] = "시작 안 됨",
        ["v.enabled"] = "활성화됨",
        ["v.disabled"] = "비활성화됨",
        ["v.set"] = "설정됨",
        ["v.empty_no_check"] = "비어 있음(검증 안 함)",
        ["v.default"] = "기본",
        ["about.start"] = "시작 {0}   호스트 {1}   엔진 {2}",
        ["about.web"] = "로컬 UI: http://127.0.0.1:{0}/webui/   {1}",
        ["about.remote"] = "원격 UI {0}   {1}",
        ["about.dir"] = "디렉터리 {0}",
        ["cli.banner.engine"] = "엔진 {0}   디렉터리 {1}",
        ["cli.banner.hint"] = "명령은 help · UI는 web start · 자체 점검은 selftest · 종료는 exit",
        ["status.engine"] = "엔진: {0}   모드: {1}   버전: {2}",
        ["status.osc"] = "OSC: {0}   전송 {1} / 실패 {2} / 수신 {3}",
        ["status.ble"] = "Bluetooth: {0}   스캔 {1}   현재 심박수 {2} bpm",
        ["status.health"] = "건강: {0}   기록: {1}   변수 {2}개",
        ["cfg.osc"] = "OSC   : {0}:{1} {2}   간격 {3}ms   수신 {4}",
        ["cfg.hw"] = "HW     : 수집 {0}ms   부동 소수점 {1}   소수 자릿수 {2}   NTP {3}",
        ["cfg.devices"] = "Devices: 연속 스캔 {0}   스로틀 {1}ms   자동 재연결 {2}",
        ["cfg.api"] = "API    : API {0}   토큰 {1}   웹 포트 {2}",
        ["cfg.dir"] = "Dir    : {0}",
        ["dev.none_hint"] = "(장치가 없습니다. scan start 실행)",
        ["dev.count"] = "전체 {0}대(종합 점수순):",
        ["dev.connected_hr"] = "연결됨 {0} bpm",
        ["dev.none"] = "(장치 없음)",
        ["dev.score"] = "점수",
        ["score.total"] = "합계 {0}",
        ["scan.stopped"] = "스캔을 중지했습니다",
        ["scan.continuous"] = "연속 스캔을 시작했습니다",
        ["scan.sec"] = "{0}초간 스캔을 시작했습니다",
        ["detect.stop_requested"] = "자동 감지 중지를 요청했습니다",
        ["detect.progress"] = "자동 감지 중: {0}/{1} 현재 {2}",
        ["detect.started"] = "자동 감지를 시작했습니다(후보 {0}대, 진행률은 로그 참조)",
        ["connect.connecting"] = "{0}에 연결 중 ...",
        ["disconnect.done"] = "{0} 연결을 끊었습니다",
        ["rename.cleared"] = "별칭을 해제했습니다: {0}",
        ["rename.done"] = "이름을 변경했습니다: {0} → {1}",
        ["save.remembered"] = "{0}을(를) 기억했습니다",
        ["save.forgotten"] = "{0} 기억을 해제했습니다",
        ["block.done"] = "{0}을(를) 차단하고 연결을 끊었습니다",
        ["health.cal_start"] = "캘리브레이션을 시작했습니다(서서 안정 30초)",
        ["health.cal_cancel"] = "캘리브레이션을 취소했습니다",
        ["health.state"] = "건강 상태: {0}",
        ["record.state"] = "기록: {0}   심박수 {1}건 / OSC {2}건",
        ["export.ok"] = "내보냄: {0}",
        ["export.fail"] = "내보내기 실패: {0}",
        ["monitor.exported"] = "보고서를 내보냈습니다: {0}",
        ["monitor.range"] = "구간: {0}   심박수 샘플 {1}개",
        ["mon.hours.all"] = "전체",
        ["mon.hours.recent"] = "최근 {0}시간",
        ["monitor.hr_stats"] = "심박: 최저 {0} / 평균 {1} / 중앙값 {2} / 최고 {3}   표준편차 {4}",
        ["monitor.period"] = "기간: {0} ~ {1}",
        ["monitor.device"] = "  장치 {0} {1,6}건   평균 {2}   {3}~{4}",
        ["monitor.health_row"] = "  상태 {0} {1}%   {2}분   {3}회",
        ["monitor.osc"] = "OSC 기록 {0}건   주소 {1}개(Top20)",
        ["hw.none"] = "(일치하는 변수 없음)",
        ["info.full_done"] = "full 수집을 실행했습니다(레지스트리 + wmic + Get-ComputerInfo + systeminfo, 백그라운드)",
        ["info.fast_done"] = "(fast 수집 소요 {0}ms)",
        ["var.cleared"] = "덮어쓰기를 해제했습니다: {0}",
        ["var.overridden"] = "덮어썼습니다 {0} = {1}",
        ["osc.on_done"] = "OSC 전송을 켰습니다",
        ["osc.off_done"] = "OSC 전송을 껐습니다",
        ["osc.state"] = "OSC 전송: {0}   사용법: osc on|off",
        ["send.ok"] = "OK",
        ["send.fail"] = "실패",
        ["send.result"] = "전송 {0}   {1}   (블로킹 {2}ms)",
        ["logs.cleared"] = "로그 버퍼를 비웠습니다",
        ["logs.dumped"] = "덤프했습니다: {0}",
        ["logs.exported"] = "{0}줄을 내보냈습니다: {1}",
        ["logs.none"] = "(일치하는 로그 없음)",
        ["unit.items"] = "{0}개",
        ["cli.unknown_key"] = "알 수 없는 키: {0}",
        ["cli.unknown_subcmd"] = "알 수 없는 하위 명령: {0}",
        ["oscfg.saved"] = "OSC 설정을 저장했습니다",
        ["params.cleared"] = "매개변수 표를 비웠습니다",
        ["params.none"] = "(수신 OSC 매개변수가 아직 없음)",
        ["params.count"] = "전체 {0}개 주소(누적 수신 {1}건):",
        ["wh.master"] = "WebHook 전체 스위치: {0}",
        ["wh.idx_range"] = "번호가 범위를 벗어났습니다(0~{0})",
        ["wh.triggered"] = "실행했습니다 #{0}   HTTP {1}",
        ["wh.trigger_fail"] = "실행 실패: {0}",
        ["wh.list_head"] = "전체 스위치 {0}   전체 {1}건:",
        ["wh.item_on"] = "[켜짐]",
        ["wh.item_off"] = "[꺼짐]",
        ["web.err_no_host"] = "[오류] Web 호스트를 사용할 수 없습니다",
        ["web.started"] = "웹 서버를 시작했습니다: {0}",
        ["web.start_failed"] = "시작 실패(포트가 사용 중일 수 있음. 로그 참조)",
        ["web.started_ui"] = "웹 서버를 시작하고 UI를 열었습니다: {0}",
        ["web.stopped"] = "웹 서버를 중지했습니다",
        ["web.state"] = "웹 서버: {0}   {1}",
        ["web.off"] = "(웹 서버가 실행 중이 아님)",
        ["remote.state"] = "원격 액세스: {0}",
        ["remote.off"] = "비활성화됨",
        ["remote.wan"] = "WAN(공용) 액세스: {0}",
        ["remote.wan_blocked"] = "WAN이 거부됨: 관리자 비밀번호가 초기화되지 않았거나 기본값이거나 약합니다(8자 이상, 영문+숫자)",
        ["remote.idle"] = "세션 유휴 만료: {0}분",
        ["remote.users_none"] = "(웹 서버가 실행 중이 아니므로 사용자 저장소를 불러오지 못함)",
        ["remote.users_count"] = "전체 {0}명의 사용자:",
        ["remote.tab_label"] = "탭",
        ["remote.sessions_none"] = "(활성 세션 없음)",
        ["remote.sessions_count"] = "전체 {0}개의 활성 세션:",
        ["remote.last_active"] = "마지막 활동",
        ["remote.session_not_found"] = "세션을 찾을 수 없음: {0}",
        ["remote.session_killed"] = "세션을 파기했습니다 {0} ({1})",
        ["remote.kill_fail"] = "파기 실패",
        ["remote.cred_error"] = "[오류] 자격 증명 보안을 위해 사용자 추가와 비밀번호 변경은 UI에서만 할 수 있습니다(평문 비밀번호가 명령 기록에 남지 않도록)",
        ["remote.user_deleted"] = "사용자를 삭제했습니다 {0}",
        ["remote.user_del_fail"] = "삭제 실패(사용자가 없거나 마지막 admin)",
        ["remote.role_changed"] = "{0}의 역할을 {1}(으)로 변경했습니다",
        ["remote.change_fail"] = "변경 실패",
        ["remote.tabs_set"] = "{0} 탭 허용 목록: {1}",
        ["ui.brand_default"] = "(기본)",
        ["float.err_no_gui"] = "[오류] 오버레이 창에는 GUI 호스트가 필요합니다(hrmcli에서는 불가. 먼저 web ui로 UI를 여세요)",
        ["float.opened"] = "오버레이 창을 열었습니다",
        ["float.all_closed"] = "모든 오버레이 창을 닫았습니다",
        ["float.locked"] = "오버레이 창을 잠갔습니다",
        ["float.unlocked"] = "오버레이 창 잠금을 해제했습니다",
        ["logcfg.interval"] = "  interval = {0}분",
        ["logcfg.trace"] = "  trace    = {0}(현재 프로세스 {1}. 다음 시작 시 적용)",
        ["evt.found"] = "발견",
        ["evt.connected"] = "연결됨",
        ["evt.disconnected"] = "연결 끊김",
        ["evt.hr"] = "심박수",
        ["evt.ble_error"] = "[BLE 오류] {0}",
        ["selftest.title"] = "========== 자체 점검(실사용자 관점 시뮬레이션) ==========",
        ["selftest.constraint"] = "제약: 가장 긴 단일 블로킹 작업 ≤ {0}ms",
        ["selftest.detail_head"] = "---- 지연 상세 ----",
        ["selftest.max_blocking"] = "가장 긴 블로킹 작업: {0}ms   상한: {1}ms  ->  {2}",
        ["selftest.over_limit"] = "상한 초과!",
        ["selftest.result"] = "========== 자체 점검 결과: {0} ==========",
        ["dsc.help"] = "이 도움말 표시",
        ["dsc.status"] = "엔진 / OSC / Bluetooth / 설정 개요",
        ["dsc.about"] = "버전 / 디렉터리 / 포트",
        ["dsc.devices"] = "장치 목록(순위 점수 포함)",
        ["dsc.score"] = "순위 점수 세부 정보(mac 생략 시 전체 장치)",
        ["dsc.scan"] = "스캔 시작 / 중지",
        ["dsc.detect"] = "자동 감지: 종합 점수순으로 심박 장치를 시도",
        ["dsc.connect"] = "장치에 연결",
        ["dsc.disconnect"] = "장치 연결 끊기",
        ["dsc.save"] = "장치 기억 / 기억 해제",
        ["dsc.block"] = "장치 차단(연결도 끊음)",
        ["dsc.rename"] = "장치 이름 변경(별칭 생략 시 해제)",
        ["dsc.devcfg"] = "장치 설정: scan/throttle/reconnect/interval/giveup/autoconnect/autodetect/timeout",
        ["dsc.bpm"] = "현재 심박수와 평균",
        ["dsc.health"] = "건강 상태 / 캘리브레이션",
        ["dsc.hcfg"] = "건강 매개변수: sleep/active/excited/spike/record/resting",
        ["dsc.record"] = "SQLite 기록 켜기·끄기",
        ["dsc.export"] = "데이터 내보내기(json/yaml/csv/sqlite)",
        ["dsc.monitor"] = "기록 통계 보고서(기본 24시간)",
        ["dsc.hw"] = "하드웨어 변수 표",
        ["dsc.info"] = "하드웨어 수집 한 번 실행",
        ["dsc.var"] = "변수 덮어쓰기(값 생략 시 해제)",
        ["dsc.hwcfg"] = "하드웨어 수집: interval/float/decimals/round/ntp",
        ["dsc.sysinfo"] = "변수 템플릿 미리보기(예: \"{BPM} {CPU_USAGE}%\")",
        ["dsc.osc"] = "OSC 전송 켜기·끄기",
        ["dsc.oscfg"] = "OSC 설정: ip/port/address/interval/recv/template",
        ["dsc.params"] = "OSC로 수신한 매개변수 표",
        ["dsc.send"] = "OSC 메시지 한 개 보내기",
        ["dsc.webhook"] = "WebHook 목록 / 전체 스위치 / 한 번 실행",
        ["dsc.api"] = "API Server 설정",
        ["dsc.web"] = "로컬 웹 UI 서비스(ui = 창도 열기)",
        ["dsc.remote"] = "두 번째 프런트엔드(원격 웹)",
        ["dsc.ui"] = "화면 설정: lang/mode/palette/corner/density/anim/brand/close",
        ["dsc.float"] = "오버레이 창(GUI 호스트 필요)",
        ["dsc.logs"] = "최근 로그 / 지우기 / 덤프 / 내보내기",
        ["dsc.logcfg"] = "로그 설정: autodump/interval/trace",
        ["dsc.config"] = "현재 설정 요약",
        ["dsc.selftest"] = "자체 점검",
        ["dsc.clear"] = "화면 지우기",
        ["dsc.exit"] = "종료",
        ["dsc.reboot"] = "엔진 재시작",
        ["reboot.ok"] = "엔진을 재시작하고 마지막 기기로 다시 연결합니다 ...",
        ["reboot.gui_only"] = "reboot는 GUI/백그라운드 모드에서만 사용할 수 있습니다",
        ["dsc.crash"] = "크래시 테스트",
        ["usage.rename"] = "사용법: rename <mac> [별칭](생략 시 해제)",
        ["usage.var"] = "사용법: var <변수 이름> [값](값 생략 시 덮어쓰기 해제)",
        ["usage.send"] = "사용법: send <주소> <텍스트>",
        ["usage.sysinfo"] = "사용법: sysinfo <템플릿>(예: sysinfo \"{BPM} bpm / CPU {CPU_USAGE}%\")",
        ["usage.devcfg"] = "사용법: devcfg <scan|throttle|reconnect|interval|giveup|weak|critical|autoconnect|autodetect|timeout> <값>",
        ["usage.hcfg"] = "사용법: hcfg <sleep|active|excited|spike|record|resting> <값>",
        ["usage.hwcfg"] = "사용법: hwcfg <interval|float|decimals|round|ntp> <값>",
        ["usage.oscfg"] = "사용법: oscfg <ip|port|address|interval|recv|template> <값>",
        ["usage.api"] = "사용법: api <on|off|token 값|push on|off|interval ms|throttle ms>",
        ["usage.ui"] = "사용법: ui <lang|mode|palette|corner|density|anim|brand|close> <값>",
        ["usage.logcfg"] = "사용법: logcfg <autodump|interval|trace> <값>",
        ["usage.webhook_test"] = "사용법: webhook test <번호>",
        ["usage.remote_host"] = "사용법: remote host <주소>",
        ["usage.remote_idle"] = "사용법: remote idle <분, 0=만료 없음>",
        ["usage.remote_kick"] = "사용법: remote kick <세션 ID 접두사. remote sessions 참조>",
        ["usage.remote_deluser"] = "사용법: remote deluser <사용자 이름>",
        ["usage.remote_role"] = "사용법: remote role <사용자 이름> <admin|user>",
        ["usage.remote_tabs"] = "사용법: remote tabs <사용자 이름> [탭,쉼표 구분; 비우면 기본]",
        ["usage.crash"] = "사용법: crash <exit1|null|kill>",
        ["crash.started"] = "크래시 테스트를 실행했습니다: {0}",
        ["exit.gui"] = "GUI에서는 \"exit --force\"를 입력해야 앱 전체가 종료됩니다",
        ["exit.repl"] = "터미널을 종료합니다(CLI에서는 exit 만으로 종료)",
        ["exit.force"] = "앱 전체를 강제 종료합니다 ...",
    };

    private static readonly Dictionary<string, string> ExtraDe = new(StringComparer.Ordinal)
    {
        ["err.prefix"] = "[Fehler] {0}",
        ["cli.usage"] = "Verwendung: {0}",
        ["help.title"] = "Verfügbare Befehle:",
        ["cmd.unknown"] = "Unbekannter Befehl: {0} („help“ oder „?“ eingeben)",
        ["cmd.bpm"] = "Aktuelle HF {0} bpm (Ø {1})",
        ["st.loaded"] = "Geladen",
        ["st.not_loaded"] = "Nicht geladen",
        ["st.connected"] = "Verbunden",
        ["st.not_connected"] = "Nicht verbunden",
        ["st.conn_devices"] = "Geräte verbunden",
        ["st.no_conn"] = "Keine Verbindung",
        ["st.scanning"] = "Suche läuft",
        ["st.scan_stopped"] = "Gestoppt",
        ["st.on"] = "Ein",
        ["st.off"] = "Aus",
        ["sw.on"] = "Ein",
        ["sw.off"] = "Aus",
        ["st.running"] = "Läuft",
        ["st.not_started"] = "Nicht gestartet",
        ["v.enabled"] = "Aktiviert",
        ["v.disabled"] = "Deaktiviert",
        ["v.set"] = "Gesetzt",
        ["v.empty_no_check"] = "Leer (keine Prüfung)",
        ["v.default"] = "Standard",
        ["about.start"] = "Gestartet {0}   Host {1}   Engine {2}",
        ["about.web"] = "Lokale UI: http://127.0.0.1:{0}/webui/   {1}",
        ["about.remote"] = "Remote-UI {0}   {1}",
        ["about.dir"] = "Verzeichnis {0}",
        ["cli.banner.engine"] = "Engine {0}   Verzeichnis {1}",
        ["cli.banner.hint"] = "„help“ für Befehle · „web start“ für die UI · „selftest“ für den Selbsttest · „exit“ zum Beenden",
        ["status.engine"] = "Engine: {0}   Modus: {1}   Version: {2}",
        ["status.osc"] = "OSC: {0}   Gesendet {1} / Fehler {2} / Empfangen {3}",
        ["status.ble"] = "Bluetooth: {0}   Scan {1}   Aktuelle HF {2} bpm",
        ["status.health"] = "Gesundheit: {0}   Aufzeichnung: {1}   {2} Variablen",
        ["cfg.osc"] = "OSC   : {0}:{1} {2}   Intervall {3}ms   Empfang {4}",
        ["cfg.hw"] = "HW     : Abtastung {0}ms   Float {1}   Dezimalstellen {2}   NTP {3}",
        ["cfg.devices"] = "Devices: Dauerscan {0}   Throttle {1}ms   Auto-Reconnect {2}",
        ["cfg.api"] = "API    : API {0}   Token {1}   Web-Port {2}",
        ["cfg.dir"] = "Dir    : {0}",
        ["dev.none_hint"] = "(Keine Geräte — zuerst „scan start“ ausführen)",
        ["dev.count"] = "{0} Gerät(e), beste Punktzahl zuerst:",
        ["dev.connected_hr"] = "Verbunden {0} bpm",
        ["dev.none"] = "(Keine Geräte)",
        ["dev.score"] = "Punktzahl",
        ["score.total"] = "Summe {0}",
        ["scan.stopped"] = "Scan gestoppt",
        ["scan.continuous"] = "Dauerscan gestartet",
        ["scan.sec"] = "Scan gestartet ({0} s)",
        ["detect.stop_requested"] = "Stopp der Auto-Erkennung angefordert",
        ["detect.progress"] = "Auto-Erkennung läuft: {0}/{1} aktuell {2}",
        ["detect.started"] = "Auto-Erkennung gestartet ({0} Kandidat(en); Fortschritt im Log)",
        ["connect.connecting"] = "Verbinde mit {0} ...",
        ["disconnect.done"] = "{0} getrennt",
        ["rename.cleared"] = "Alias entfernt: {0}",
        ["rename.done"] = "Umbenannt: {0} → {1}",
        ["save.remembered"] = "{0} gemerkt",
        ["save.forgotten"] = "{0} nicht mehr gemerkt",
        ["block.done"] = "{0} blockiert und getrennt",
        ["health.cal_start"] = "Kalibrierung gestartet (30 s ruhig stehen)",
        ["health.cal_cancel"] = "Kalibrierung abgebrochen",
        ["health.state"] = "Gesundheitsstatus: {0}",
        ["record.state"] = "Aufzeichnung: {0}   HF {1} Einträge / OSC {2} Einträge",
        ["export.ok"] = "Exportiert: {0}",
        ["export.fail"] = "Export fehlgeschlagen: {0}",
        ["monitor.exported"] = "Bericht exportiert: {0}",
        ["monitor.range"] = "Bereich: {0}   HF-Proben {1}",
        ["mon.hours.all"] = "Gesamter Zeitraum",
        ["mon.hours.recent"] = "Letzte {0} Std.",
        ["monitor.hr_stats"] = "HF: min {0} / Ø {1} / Median {2} / max {3}   SD {4}",
        ["monitor.period"] = "Zeitraum: {0} ~ {1}",
        ["monitor.device"] = "  Gerät {0} {1,6} Einträge   Ø {2}   {3}~{4}",
        ["monitor.health_row"] = "  Status {0} {1}%   {2} Min   {3}×",
        ["monitor.osc"] = "OSC-Einträge {0}   Adressen {1} (Top20)",
        ["hw.none"] = "(Keine passenden Variablen)",
        ["info.full_done"] = "Vollständige Abtastung ausgelöst (Registry + wmic + Get-ComputerInfo + systeminfo, im Hintergrund)",
        ["info.fast_done"] = "(schnelle Abtastung dauerte {0} ms)",
        ["var.cleared"] = "Überschreibung entfernt: {0}",
        ["var.overridden"] = "Überschrieben {0} = {1}",
        ["osc.on_done"] = "OSC-Versand aktiviert",
        ["osc.off_done"] = "OSC-Versand deaktiviert",
        ["osc.state"] = "OSC-Versand: {0}   Verwendung: osc on|off",
        ["send.ok"] = "OK",
        ["send.fail"] = "Fehlgeschlagen",
        ["send.result"] = "Gesendet {0}   {1}   (blockierend {2} ms)",
        ["logs.cleared"] = "Logpuffer geleert",
        ["logs.dumped"] = "Dump: {0}",
        ["logs.exported"] = "{0} Zeile(n) exportiert: {1}",
        ["logs.none"] = "(Keine passenden Logs)",
        ["unit.items"] = "{0} Element(e)",
        ["cli.unknown_key"] = "Unbekannter Schlüssel: {0}",
        ["cli.unknown_subcmd"] = "Unbekannter Unterbefehl: {0}",
        ["oscfg.saved"] = "OSC-Konfiguration gespeichert",
        ["params.cleared"] = "Parametertabelle geleert",
        ["params.none"] = "(Noch keine OSC-Parameter empfangen)",
        ["params.count"] = "{0} Adresse(n) ({1} insgesamt empfangen):",
        ["wh.master"] = "WebHook-Hauptschalter: {0}",
        ["wh.idx_range"] = "Index außerhalb des Bereichs (0~{0})",
        ["wh.triggered"] = "Ausgelöst #{0}   HTTP {1}",
        ["wh.trigger_fail"] = "Auslösung fehlgeschlagen: {0}",
        ["wh.list_head"] = "Hauptschalter {0}   {1} Element(e):",
        ["wh.item_on"] = "[Ein]",
        ["wh.item_off"] = "[Aus]",
        ["web.err_no_host"] = "[Fehler] Web-Host nicht verfügbar",
        ["web.started"] = "Webserver gestartet: {0}",
        ["web.start_failed"] = "Start fehlgeschlagen (Port evtl. belegt; siehe Logs)",
        ["web.started_ui"] = "Webserver gestartet und UI geöffnet: {0}",
        ["web.stopped"] = "Webserver gestoppt",
        ["web.state"] = "Webserver: {0}   {1}",
        ["web.off"] = "(Webserver läuft nicht)",
        ["remote.state"] = "Remote-Frontend: {0}",
        ["remote.off"] = "Deaktiviert",
        ["remote.host"] = "Lauschadresse: {0}",
        ["remote.port"] = "Lauschport: {0}",
        ["remote.loopback"] = "Loopback-Einschränkung: {0}",
        ["remote.idle"] = "Sitzungs-Timeout bei Inaktivität: {0} Min",
        ["remote.users_none"] = "(Webserver läuft nicht; Benutzer nicht geladen)",
        ["remote.users_count"] = "{0} Benutzer:",
        ["remote.tab_label"] = "Tabs",
        ["remote.sessions_none"] = "(Keine aktiven Sitzungen)",
        ["remote.sessions_count"] = "{0} aktive Sitzung(en):",
        ["remote.last_active"] = "zuletzt aktiv",
        ["remote.session_not_found"] = "Sitzung nicht gefunden: {0}",
        ["remote.session_killed"] = "Sitzung zerstört {0} ({1})",
        ["remote.kill_fail"] = "Zerstören fehlgeschlagen",
        ["remote.cred_error"] = "[Fehler] Aus Sicherheitsgründen können Benutzer nur in der UI hinzugefügt und Passwörter nur dort geändert werden (kein Klartext im Befehlsverlauf)",
        ["remote.user_deleted"] = "Benutzer {0} gelöscht",
        ["remote.user_del_fail"] = "Löschen fehlgeschlagen (Benutzer fehlt oder letzter Admin)",
        ["remote.role_changed"] = "Rolle von {0} auf {1} gesetzt",
        ["remote.change_fail"] = "Änderung fehlgeschlagen",
        ["remote.tabs_set"] = "Tab-Whitelist von {0}: {1}",
        ["ui.brand_default"] = "(Standard)",
        ["float.err_no_gui"] = "[Fehler] Overlays benötigen einen GUI-Host (in hrmcli nicht verfügbar — UI zuerst mit „web ui“ öffnen)",
        ["float.opened"] = "Overlay geöffnet",
        ["float.all_closed"] = "Alle Overlays geschlossen",
        ["float.locked"] = "Overlays gesperrt",
        ["float.unlocked"] = "Overlays entsperrt",
        ["logcfg.interval"] = "  interval = {0} Min",
        ["logcfg.trace"] = "  trace    = {0} (aktueller Prozess {1}; wirkt nach Neustart)",
        ["evt.found"] = "Gefunden",
        ["evt.connected"] = "Verbunden",
        ["evt.disconnected"] = "Getrennt",
        ["evt.hr"] = "HF",
        ["evt.ble_error"] = "[BLE-Fehler] {0}",
        ["selftest.title"] = "========== Selbsttest (reale Benutzersicht) ==========",
        ["selftest.constraint"] = "Randbedingung: längste einzelne blockierende Operation ≤ {0} ms",
        ["selftest.detail_head"] = "---- Latenzdetails ----",
        ["selftest.max_blocking"] = "Längste blockierende Operation: {0} ms   Limit: {1} ms  ->  {2}",
        ["selftest.over_limit"] = "Limit überschritten!",
        ["selftest.result"] = "========== Selbsttest-Ergebnis: {0} ==========",
        ["dsc.help"] = "Diese Hilfe anzeigen",
        ["dsc.status"] = "Engine / OSC / Bluetooth / Konfigurationsübersicht",
        ["dsc.about"] = "Version / Verzeichnis / Port",
        ["dsc.devices"] = "Geräteliste (mit Ranking-Punktzahl)",
        ["dsc.score"] = "Punktzahldetails (kein mac = alle Geräte)",
        ["dsc.scan"] = "Scan starten / stoppen",
        ["dsc.detect"] = "Auto-Erkennung: HF-Geräte in Punktzahlreihenfolge probieren",
        ["dsc.connect"] = "Mit Gerät verbinden",
        ["dsc.disconnect"] = "Gerät trennen",
        ["dsc.save"] = "Gerät merken / vergessen",
        ["dsc.block"] = "Gerät blockieren (und trennen)",
        ["dsc.rename"] = "Gerät umbenennen (kein Alias = löschen)",
        ["dsc.devcfg"] = "Geräterichtlinie: scan/throttle/reconnect/interval/giveup/autoconnect/autodetect/timeout",
        ["dsc.bpm"] = "Aktuelle HF und Durchschnitt",
        ["dsc.health"] = "Gesundheitsstatus / Kalibrierung",
        ["dsc.hcfg"] = "Gesundheitsparameter: sleep/active/excited/spike/record/resting",
        ["dsc.record"] = "SQLite-Aufzeichnung ein/aus",
        ["dsc.export"] = "Daten exportieren (json/yaml/csv/sqlite)",
        ["dsc.monitor"] = "Statistikbericht (Standard 24 h)",
        ["dsc.hw"] = "Hardware-Variablentabelle",
        ["dsc.info"] = "Eine Hardware-Abtastung auslösen",
        ["dsc.var"] = "Variable überschreiben (kein Wert = löschen)",
        ["dsc.hwcfg"] = "Hardware-Abtastung: interval/float/decimals/round/ntp",
        ["dsc.sysinfo"] = "Variablenvorlage anzeigen (z. B. \"{BPM} {CPU_USAGE}%\")",
        ["dsc.osc"] = "OSC-Versand ein/aus",
        ["dsc.oscfg"] = "OSC-Konfiguration: ip/port/address/interval/recv/template",
        ["dsc.params"] = "Über OSC empfangene Parameter",
        ["dsc.send"] = "Eine OSC-Nachricht senden",
        ["dsc.webhook"] = "WebHook-Liste / Hauptschalter / einmal auslösen",
        ["dsc.api"] = "API-Server-Konfiguration",
        ["dsc.web"] = "Lokaler Web-UI-Dienst (ui = auch Fenster öffnen)",
        ["dsc.remote"] = "Zweites Frontend (Remote-Web)",
        ["dsc.ui"] = "UI: lang/mode/palette/corner/density/anim/brand/close",
        ["dsc.float"] = "Overlay (benötigt GUI-Host)",
        ["dsc.logs"] = "Letzte Logs / leeren / Dump / exportieren",
        ["dsc.logcfg"] = "Protokollierung: autodump/interval/trace",
        ["dsc.config"] = "Aktuelle Konfigurationsübersicht",
        ["dsc.selftest"] = "Selbsttest",
        ["dsc.clear"] = "Bildschirm leeren",
        ["dsc.exit"] = "Beenden",
        ["dsc.reboot"] = "Motor neu starten",
        ["reboot.ok"] = "Motor wird neu gestartet und mit dem letzten Gerät verbunden ...",
        ["reboot.gui_only"] = "reboot ist nur im GUI-/Hintergrundmodus verfügbar",
        ["dsc.crash"] = "Absturztest",
        ["usage.rename"] = "Verwendung: rename <mac> [alias] (kein Alias = löschen)",
        ["usage.var"] = "Verwendung: var <name> [wert] (kein Wert = Überschreibung löschen)",
        ["usage.send"] = "Verwendung: send <adresse> <text>",
        ["usage.sysinfo"] = "Verwendung: sysinfo <vorlage> (z. B. sysinfo \"{BPM} bpm / CPU {CPU_USAGE}%\")",
        ["usage.devcfg"] = "Verwendung: devcfg <scan|throttle|reconnect|interval|giveup|weak|critical|autoconnect|autodetect|timeout> <wert>",
        ["usage.hcfg"] = "Verwendung: hcfg <sleep|active|excited|spike|record|resting> <wert>",
        ["usage.hwcfg"] = "Verwendung: hwcfg <interval|float|decimals|round|ntp> <wert>",
        ["usage.oscfg"] = "Verwendung: oscfg <ip|port|address|interval|recv|template> <wert>",
        ["usage.api"] = "Verwendung: api <on|off|token wert|push on|off|interval ms|throttle ms>",
        ["usage.ui"] = "Verwendung: ui <lang|mode|palette|corner|density|anim|brand|close> <wert>",
        ["usage.logcfg"] = "Verwendung: logcfg <autodump|interval|trace> <wert>",
        ["usage.webhook_test"] = "Verwendung: webhook test <index>",
        ["usage.remote_host"] = "Verwendung: remote host <adresse>",
        ["usage.remote_idle"] = "Verwendung: remote idle <minuten, 0 = nie>",
        ["usage.remote_kick"] = "Verwendung: remote kick <sitzungs-id-präfix; siehe remote sessions>",
        ["usage.remote_deluser"] = "Verwendung: remote deluser <benutzername>",
        ["usage.remote_role"] = "Verwendung: remote role <benutzername> <admin|user>",
        ["usage.remote_tabs"] = "Verwendung: remote tabs <benutzername> [tabs, kommagetrennt; leer = Standard]",
        ["usage.crash"] = "Verwendung: crash <exit1|null|kill>",
        ["crash.started"] = "Absturztest ausgelöst: {0}",
        ["exit.gui"] = "In der GUI benötigen Sie \"exit --force\", um die gesamte App zu beenden",
        ["exit.repl"] = "Beendet das Terminal („exit“ allein genügt in der CLI)",
        ["exit.force"] = "App wird vollständig beendet ...",
    };

    private static readonly Dictionary<string, string> ExtraFr = new(StringComparer.Ordinal)
    {
        ["err.prefix"] = "[Erreur] {0}",
        ["cli.usage"] = "Utilisation : {0}",
        ["help.title"] = "Commandes disponibles :",
        ["cmd.unknown"] = "Commande inconnue : {0} (tapez « help » ou « ? »)",
        ["cmd.bpm"] = "FC actuelle {0} bpm (moyenne {1})",
        ["st.loaded"] = "Chargé",
        ["st.not_loaded"] = "Non chargé",
        ["st.connected"] = "Connecté",
        ["st.not_connected"] = "Non connecté",
        ["st.conn_devices"] = "Appareils connectés",
        ["st.no_conn"] = "Aucune connexion",
        ["st.scanning"] = "Scan en cours",
        ["st.scan_stopped"] = "Arrêté",
        ["st.on"] = "On",
        ["st.off"] = "Off",
        ["sw.on"] = "On",
        ["sw.off"] = "Off",
        ["st.running"] = "En cours",
        ["st.not_started"] = "Non démarré",
        ["v.enabled"] = "Activé",
        ["v.disabled"] = "Désactivé",
        ["v.set"] = "Défini",
        ["v.empty_no_check"] = "Vide (aucune vérification)",
        ["v.default"] = "Par défaut",
        ["about.start"] = "Démarré {0}   Hôte {1}   Moteur {2}",
        ["about.web"] = "Interface locale : http://127.0.0.1:{0}/webui/   {1}",
        ["about.remote"] = "Interface distante {0}   {1}",
        ["about.dir"] = "Répertoire {0}",
        ["cli.banner.engine"] = "Moteur {0}   Répertoire {1}",
        ["cli.banner.hint"] = "« help » pour les commandes · « web start » pour l'interface · « selftest » pour l'autotest · « exit » pour quitter",
        ["status.engine"] = "Moteur : {0}   Mode : {1}   Version : {2}",
        ["status.osc"] = "OSC : {0}   Envoyés {1} / Échecs {2} / Reçus {3}",
        ["status.ble"] = "Bluetooth : {0}   Scan {1}   FC actuelle {2} bpm",
        ["status.health"] = "Santé : {0}   Enregistrement : {1}   {2} variables",
        ["cfg.osc"] = "OSC   : {0}:{1} {2}   Intervalle {3}ms   Réception {4}",
        ["cfg.hw"] = "HW     : Échantillonnage {0}ms   Flottant {1}   Décimales {2}   NTP {3}",
        ["cfg.devices"] = "Appareils : scan continu {0}   Limite {1}ms   Reconnexion auto {2}",
        ["cfg.api"] = "API    : API {0}   Jeton {1}   Port web {2}",
        ["cfg.dir"] = "Dir    : {0}",
        ["dev.none_hint"] = "(Aucun appareil — lancez « scan start »)",
        ["dev.count"] = "{0} appareil(s), meilleur score d'abord :",
        ["dev.connected_hr"] = "Connecté {0} bpm",
        ["dev.none"] = "(Aucun appareil)",
        ["dev.score"] = "score",
        ["score.total"] = "Total {0}",
        ["scan.stopped"] = "Scan arrêté",
        ["scan.continuous"] = "Scan continu démarré",
        ["scan.sec"] = "Scan démarré ({0} s)",
        ["detect.stop_requested"] = "Arrêt de la détection automatique demandé",
        ["detect.progress"] = "Détection automatique en cours : {0}/{1} actuel {2}",
        ["detect.started"] = "Détection automatique démarrée ({0} candidat(s) ; progression dans les journaux)",
        ["connect.connecting"] = "Connexion à {0} ...",
        ["disconnect.done"] = "{0} déconnecté",
        ["rename.cleared"] = "Alias effacé : {0}",
        ["rename.done"] = "Renommé : {0} → {1}",
        ["save.remembered"] = "{0} mémorisé",
        ["save.forgotten"] = "{0} ne plus mémoriser",
        ["block.done"] = "{0} bloqué et déconnecté",
        ["health.cal_start"] = "Calibrage démarré (30 s debout au repos)",
        ["health.cal_cancel"] = "Calibrage annulé",
        ["health.state"] = "État de santé : {0}",
        ["record.state"] = "Enregistrement : {0}   FC {1} entrées / OSC {2} entrées",
        ["export.ok"] = "Exporté : {0}",
        ["export.fail"] = "Échec de l'export : {0}",
        ["monitor.exported"] = "Rapport exporté : {0}",
        ["monitor.range"] = "Plage : {0}   Échantillons FC {1}",
        ["mon.hours.all"] = "Tout",
        ["mon.hours.recent"] = "Dernières {0} h",
        ["monitor.hr_stats"] = "FC : min {0} / moyenne {1} / médiane {2} / max {3}   écart type {4}",
        ["monitor.period"] = "Période : {0} ~ {1}",
        ["monitor.device"] = "  Appareil {0} {1,6} entrées   moyenne {2}   {3}~{4}",
        ["monitor.health_row"] = "  État {0} {1}%   {2} min   {3} fois",
        ["monitor.osc"] = "Enregistrements OSC {0}   adresses {1} (Top20)",
        ["hw.none"] = "(Aucune variable correspondante)",
        ["info.full_done"] = "Échantillonnage complet déclenché (registre + wmic + Get-ComputerInfo + systeminfo, en arrière-plan)",
        ["info.fast_done"] = "(l'échantillonnage rapide a pris {0} ms)",
        ["var.cleared"] = "Remplacement effacé : {0}",
        ["var.overridden"] = "Remplacé {0} = {1}",
        ["osc.on_done"] = "Envoi OSC activé",
        ["osc.off_done"] = "Envoi OSC désactivé",
        ["osc.state"] = "Envoi OSC : {0}   Utilisation : osc on|off",
        ["send.ok"] = "OK",
        ["send.fail"] = "Échec",
        ["send.result"] = "Envoyé {0}   {1}   (bloquant {2} ms)",
        ["logs.cleared"] = "Tampon de journaux vidé",
        ["logs.dumped"] = "Dump : {0}",
        ["logs.exported"] = "{0} ligne(s) exportée(s) : {1}",
        ["logs.none"] = "(Aucun journal correspondant)",
        ["unit.items"] = "{0} élément(s)",
        ["cli.unknown_key"] = "Clé inconnue : {0}",
        ["cli.unknown_subcmd"] = "Sous-commande inconnue : {0}",
        ["oscfg.saved"] = "Configuration OSC enregistrée",
        ["params.cleared"] = "Table des paramètres vidée",
        ["params.none"] = "(Aucun paramètre OSC reçu pour l'instant)",
        ["params.count"] = "{0} adresse(s) ({1} reçues au total) :",
        ["wh.master"] = "Interrupteur général WebHook : {0}",
        ["wh.idx_range"] = "Index hors limites (0~{0})",
        ["wh.triggered"] = "Déclenché #{0}   HTTP {1}",
        ["wh.trigger_fail"] = "Échec du déclenchement : {0}",
        ["wh.list_head"] = "Interrupteur général {0}   {1} élément(s) :",
        ["wh.item_on"] = "[On]",
        ["wh.item_off"] = "[Off]",
        ["web.err_no_host"] = "[Erreur] Hôte web indisponible",
        ["web.started"] = "Serveur web démarré : {0}",
        ["web.start_failed"] = "Échec du démarrage (port peut-être occupé ; voir les journaux)",
        ["web.started_ui"] = "Serveur web démarré et interface ouverte : {0}",
        ["web.stopped"] = "Serveur web arrêté",
        ["web.state"] = "Serveur web : {0}   {1}",
        ["web.off"] = "(Serveur web non démarré)",
        ["remote.state"] = "Accès distant : {0}",
        ["remote.off"] = "Désactivé",
        ["remote.wan"] = "Accès WAN (public) : {0}",
        ["remote.wan_blocked"] = "WAN refusé : mot de passe admin non initialisé, par défaut ou trop faible (≥8 caractères avec lettres et chiffres)",
        ["remote.idle"] = "Expiration par inactivité : {0} min",
        ["remote.users_none"] = "(Serveur web non démarré ; utilisateurs non chargés)",
        ["remote.users_count"] = "{0} utilisateur(s) :",
        ["remote.tab_label"] = "onglets",
        ["remote.sessions_none"] = "(Aucune session active)",
        ["remote.sessions_count"] = "{0} session(s) active(s) :",
        ["remote.last_active"] = "dernière activité",
        ["remote.session_not_found"] = "Session introuvable : {0}",
        ["remote.session_killed"] = "Session détruite {0} ({1})",
        ["remote.kill_fail"] = "Échec de la destruction",
        ["remote.cred_error"] = "[Erreur] Pour la sécurité des identifiants, l'ajout d'utilisateurs et le changement de mot de passe ne se font que dans l'interface (pas de mot de passe en clair dans l'historique)",
        ["remote.user_deleted"] = "Utilisateur {0} supprimé",
        ["remote.user_del_fail"] = "Échec de la suppression (utilisateur absent ou dernier admin)",
        ["remote.role_changed"] = "Rôle de {0} défini sur {1}",
        ["remote.change_fail"] = "Échec de la modification",
        ["remote.tabs_set"] = "Liste blanche d'onglets de {0} : {1}",
        ["ui.brand_default"] = "(par défaut)",
        ["float.err_no_gui"] = "[Erreur] Les superpositions nécessitent un hôte GUI (indisponible dans hrmcli — ouvrez d'abord l'interface avec « web ui »)",
        ["float.opened"] = "Superposition ouverte",
        ["float.all_closed"] = "Toutes les superpositions fermées",
        ["float.locked"] = "Superpositions verrouillées",
        ["float.unlocked"] = "Superpositions déverrouillées",
        ["logcfg.interval"] = "  intervalle = {0} min",
        ["logcfg.trace"] = "  trace    = {0} (processus actuel {1} ; effet au prochain démarrage)",
        ["evt.found"] = "Trouvé",
        ["evt.connected"] = "Connecté",
        ["evt.disconnected"] = "Déconnecté",
        ["evt.hr"] = "FC",
        ["evt.ble_error"] = "[Erreur BLE] {0}",
        ["selftest.title"] = "========== Auto-test (simulation d'un utilisateur réel) ==========",
        ["selftest.constraint"] = "Contrainte : opération bloquante la plus longue ≤ {0} ms",
        ["selftest.detail_head"] = "---- Détails de latence ----",
        ["selftest.max_blocking"] = "Opération bloquante la plus longue : {0} ms   limite : {1} ms  ->  {2}",
        ["selftest.over_limit"] = "Limite dépassée !",
        ["selftest.result"] = "========== Résultat de l'auto-test : {0} ==========",
        ["dsc.help"] = "Afficher cette aide",
        ["dsc.status"] = "Aperçu moteur / OSC / Bluetooth / configuration",
        ["dsc.about"] = "Version / répertoire / port",
        ["dsc.devices"] = "Liste des appareils (avec score de classement)",
        ["dsc.score"] = "Détails des scores (sans mac = tous les appareils)",
        ["dsc.scan"] = "Démarrer / arrêter le scan",
        ["dsc.detect"] = "Détection auto : essayer les appareils FC par score",
        ["dsc.connect"] = "Connecter un appareil",
        ["dsc.disconnect"] = "Déconnecter un appareil",
        ["dsc.save"] = "Mémoriser / oublier un appareil",
        ["dsc.block"] = "Bloquer un appareil (et déconnecter)",
        ["dsc.rename"] = "Renommer un appareil (sans alias = effacer)",
        ["dsc.devcfg"] = "Politique appareils : scan/throttle/reconnect/interval/giveup/autoconnect/autodetect/timeout",
        ["dsc.bpm"] = "FC actuelle et moyenne",
        ["dsc.health"] = "État de santé / calibrage",
        ["dsc.hcfg"] = "Paramètres santé : sleep/active/excited/spike/record/resting",
        ["dsc.record"] = "Interrupteur d'enregistrement SQLite",
        ["dsc.export"] = "Exporter les données (json/yaml/csv/sqlite)",
        ["dsc.monitor"] = "Rapport statistique (24 h par défaut)",
        ["dsc.hw"] = "Table des variables matérielles",
        ["dsc.info"] = "Déclencher un échantillonnage matériel",
        ["dsc.var"] = "Remplacer une variable (sans valeur = effacer)",
        ["dsc.hwcfg"] = "Échantillonnage matériel : interval/float/decimals/round/ntp",
        ["dsc.sysinfo"] = "Aperçu du modèle de variables (p. ex. \"{BPM} {CPU_USAGE}%\")",
        ["dsc.osc"] = "Interrupteur d'envoi OSC",
        ["dsc.oscfg"] = "Config OSC : ip/port/address/interval/recv/template",
        ["dsc.params"] = "Table des paramètres reçus par OSC",
        ["dsc.send"] = "Envoyer un message OSC",
        ["dsc.webhook"] = "Liste WebHook / interrupteur général / déclencher une fois",
        ["dsc.api"] = "Configuration du serveur API",
        ["dsc.web"] = "Service d'interface web local (ui = ouvrir aussi la fenêtre)",
        ["dsc.remote"] = "Second frontend (web distant)",
        ["dsc.ui"] = "Interface : lang/mode/palette/corner/density/anim/brand/close",
        ["dsc.float"] = "Superposition (nécessite un hôte GUI)",
        ["dsc.logs"] = "Journaux récents / vider / dump / exporter",
        ["dsc.logcfg"] = "Journalisation : autodump/interval/trace",
        ["dsc.config"] = "Résumé de la configuration actuelle",
        ["dsc.selftest"] = "Auto-test",
        ["dsc.clear"] = "Effacer l'écran",
        ["dsc.exit"] = "Quitter",
        ["dsc.reboot"] = "Redémarrer le moteur",
        ["reboot.ok"] = "Redémarrage du moteur et reconnexion du dernier appareil ...",
        ["reboot.gui_only"] = "reboot n'est disponible qu'en mode GUI/fond",
        ["dsc.crash"] = "Test de crash",
        ["usage.rename"] = "Utilisation : rename <mac> [alias] (sans alias = effacer)",
        ["usage.var"] = "Utilisation : var <nom> [valeur] (sans valeur = retirer le remplacement)",
        ["usage.send"] = "Utilisation : send <adresse> <texte>",
        ["usage.sysinfo"] = "Utilisation : sysinfo <modèle> (p. ex. sysinfo \"{BPM} bpm / CPU {CPU_USAGE}%\")",
        ["usage.devcfg"] = "Utilisation : devcfg <scan|throttle|reconnect|interval|giveup|weak|critical|autoconnect|autodetect|timeout> <valeur>",
        ["usage.hcfg"] = "Utilisation : hcfg <sleep|active|excited|spike|record|resting> <valeur>",
        ["usage.hwcfg"] = "Utilisation : hwcfg <interval|float|decimals|round|ntp> <valeur>",
        ["usage.oscfg"] = "Utilisation : oscfg <ip|port|address|interval|recv|template> <valeur>",
        ["usage.api"] = "Utilisation : api <on|off|token valeur|push on|off|interval ms|throttle ms>",
        ["usage.ui"] = "Utilisation : ui <lang|mode|palette|corner|density|anim|brand|close> <valeur>",
        ["usage.logcfg"] = "Utilisation : logcfg <autodump|interval|trace> <valeur>",
        ["usage.webhook_test"] = "Utilisation : webhook test <index>",
        ["usage.remote_host"] = "Utilisation : remote host <adresse>",
        ["usage.remote_idle"] = "Utilisation : remote idle <minutes, 0 = jamais>",
        ["usage.remote_kick"] = "Utilisation : remote kick <préfixe d'id de session ; voir remote sessions>",
        ["usage.remote_deluser"] = "Utilisation : remote deluser <utilisateur>",
        ["usage.remote_role"] = "Utilisation : remote role <utilisateur> <admin|user>",
        ["usage.remote_tabs"] = "Utilisation : remote tabs <utilisateur> [onglets, séparés par des virgules ; vide = défaut]",
        ["usage.crash"] = "Utilisation : crash <exit1|null|kill>",
        ["crash.started"] = "Test de crash déclenché : {0}",
        ["exit.gui"] = "Dans l'interface, tapez \"exit --force\" pour quitter toute l'application",
        ["exit.repl"] = "Quitte le terminal (« exit » seul suffit dans la CLI)",
        ["exit.force"] = "Arrêt forcé de toute l'application ...",
    };

    /// <summary>Resolve text for the current language. Without arguments, return the literal text without string.Format so braces remain safe;
    /// with arguments, fill placeholders such as {0}. Return missing keys unchanged to make omissions visible.</summary>
    public static string T(string key, params object?[] args)
    {
        if (!Table.TryGetValue(key, out var row)) return key;
        var s = App.Lang switch
        {
            "ko" => ExtraKo.TryGetValue(key, out var a) ? a : row[1],
            "de" => ExtraDe.TryGetValue(key, out var b) ? b : row[1],
            "fr" => ExtraFr.TryGetValue(key, out var c) ? c : row[1],
            "en" => row[1],
            "ja" => row[2],
            "es" => row[3],
            _ => row[0], // zh-cn, zh-tw, zh-hk, yue-hk, or unknown language
        };
        return args.Length == 0 ? s : string.Format(s, args);
    }
}
